extends RefCounted
## Deterministic catalog compiler and validator, per BAL-CAT-001 and GDD §4.2's closing paragraph.
##
## Every domain (SpeciesDefinition, ItemDefinition, RecipeDefinition, BuildingDefinition,
## CropDefinition, EventDefinition, ...) is compiled independently: its own StringName keys are
## sorted into ascending ASCII order and assigned int32 IDs 0..n-1 in that order, so the same key
## set always compiles to the same IDs regardless of the order the keys were declared or
## discovered in. Dictionary insertion order never leaks into an ID.
##
## The handful of gameplay enums that GDD §4.3 gives explicit numeric values (Speed, Activity,
## JobKind, JobState, ZoneType, Season, Soil, CropState, OrderMode, Quality, Severity) are fixed
## data here, never run through the compiler: they must never be renumbered, including the
## intentionally reserved gaps (JobKind.RESERVED_3, ZoneType.RESERVED_1).
##
## Decision 0018 fixes the rule: every enum §4.3 numbers explicitly lives in
## PROTECTED_ENUM_DOMAINS, because the protected table is the thing that REFUSES a recompile. A
## module needing one of these numbers reads it from here (`const X: int = Catalog.ACTIVITY[...]`
## is a valid GDScript constant expression) rather than mirroring it locally, so there is exactly
## one copy of every specified value and no drift is possible.
##
## The COMPILED enum domains below are the other half of that rule, and are NOT protected. GDD
## §4.2's closing paragraph -- "All gameplay enum numeric values not individually listed are
## generated once from the lexicographically sorted ASCII catalog keys within their own domain"
## -- and BAL-CAT-002, which names crop-family explicitly, already number CropFamily,
## EventDefinition and HabitatType. Three modules missed that paragraph and used their display
## table's printed order instead; the ruling in docs/rulings/2026-09-09_ready06_open_item_answers.md
## §2 settles it. They are declared here so the numbering lives in ONE place, and
## verify_compiled_enum() proves each table is exactly what compile_domain() produces from its own
## keys -- these are transcriptions of a generated result, never hand-chosen ordinals. They stay
## OUT of PROTECTED_ENUM_DOMAINS on purpose: protection means "§4.3 stated this number, never
## regenerate it", and §4.3 states none of these three.
##
## A compile_catalog() batch is all-or-nothing: if any domain in the batch fails validation, no
## domain's IDs are produced, matching GDD §4.2's "a registry validation failure aborts loading
## before mutating the current world."
##
## Persistence note (blocker U1): `catalog_ids.json` emission and its load-time hash check are
## unspecified (document shape, canonical serialization, and hash relationship to save-header
## offset 72 are not defined anywhere in the architecture doc) and are therefore NOT implemented
## here. This module compiles and validates in memory only; a future task adds the file once U1
## is resolved.

const ITEM_DEFINITION_DOMAIN: String = "ItemDefinition"
const ITEM_DEFINITION_MAX_KEYS: int = 256

## GDD §4.3 explicit enums: fixed data, never regenerated by the compiler below.
const SPEED: Dictionary = {"PAUSED": 0, "NORMAL": 1, "DOUBLE": 2, "QUADRUPLE": 4}
## §4.3: "Activity | SLEEP=0, ANYTHING=1, WORK=2, SOCIAL=3". Four values, no reserved gap.
const ACTIVITY: Dictionary = {"SLEEP": 0, "ANYTHING": 1, "WORK": 2, "SOCIAL": 3}
const JOB_KIND: Dictionary = {
	"HAUL": 0, "BUILD": 1, "FISH": 2, "RESERVED_3": 3, "FORAGE": 4, "FARM": 5,
	"COOK": 6, "PRESERVE": 7, "CRAFT": 8, "TEND": 9, "KEEP": 10, "HEAL": 11,
}
## §4.3: "JobState | QUEUED=0, RESERVED=1, TRAVEL=2, WORK=3, HAUL_OUTPUT=4, COMPLETE=5,
## BLOCKED=6, CANCELLED=7". WORK=3 here is a JobState, unrelated to Activity.WORK=2.
const JOB_STATE: Dictionary = {
	"QUEUED": 0, "RESERVED": 1, "TRAVEL": 2, "WORK": 3,
	"HAUL_OUTPUT": 4, "COMPLETE": 5, "BLOCKED": 6, "CANCELLED": 7,
}
const ZONE_TYPE: Dictionary = {
	"FISH": 0, "RESERVED_1": 1, "FORAGE": 2, "FARM": 3, "ORCHARD": 4,
	"FORESTRY": 5, "QUARRY": 6, "STOCKPILE": 7, "CONSERVATION": 8,
}
const SEASON: Dictionary = {"SPRING": 0, "SUMMER": 1, "AUTUMN": 2, "WINTER": 3}
## §4.3: "Soil | LOAM=0, CLAY=1, SAND=2". GDD §5.6 and BAL-CROP-001 build `allowed_soils` as
## `1<<Soil` from exactly these ordinals, so renumbering them silently repoints every crop's
## soil mask at a different soil.
const SOIL: Dictionary = {"LOAM": 0, "CLAY": 1, "SAND": 2}
## §4.3: "CropState | EMPTY=0, SOWN=1, GROWING=2, RIPE=3, WITHERED=4". `FarmPlot.state` is
## persisted state, so these five are save-carried.
const CROP_STATE: Dictionary = {
	"EMPTY": 0, "SOWN": 1, "GROWING": 2, "RIPE": 3, "WITHERED": 4,
}
## §4.3: "OrderMode | ONCE=0, REPEAT=1, MAINTAIN_STOCK=2". `ProductionOrder.mode` in §4.2.
const ORDER_MODE: Dictionary = {"ONCE": 0, "REPEAT": 1, "MAINTAIN_STOCK": 2}
const QUALITY: Dictionary = {"POOR": 0, "PLAIN": 1, "GOOD": 2, "EXCELLENT": 3}
const SEVERITY: Dictionary = {"INFO": 0, "ADVISORY": 1, "WARNING": 2, "CRITICAL": 3}

const PROTECTED_ENUM_DOMAINS: Array[String] = [
	"Speed", "Activity", "JobKind", "JobState", "ZoneType", "Season", "Soil", "CropState",
	"OrderMode", "Quality", "Severity",
]

# --- compiled enum domains (GDD §4.2 closing paragraph, BAL-CAT-001/002) -------------------------

const CROP_FAMILY_DOMAIN: String = "CropFamily"
const EVENT_DEFINITION_DOMAIN: String = "EventDefinition"
const HABITAT_TYPE_DOMAIN: String = "HabitatType"

## GDD §4.2: "empty catalog IDs are -1". Absence, never a refusal channel and never a key.
const EMPTY_CATALOG_ID: int = -1

## BAL-CAT-002: "Category, effect, recipe-family, crop-family, and station domains use the keys
## printed in these tables and numeric IDs generated by BAL-CAT-001." The keys are §5.6's own
## uppercase family names; the IDs are their ascending ASCII order, not §5.6's printed order.
const CROP_FAMILY: Dictionary = {"CEREAL": 0, "FIBER": 1, "LEAF": 2, "LEGUME": 3, "ROOT": 4}

## §5.10's seven event rows, keyed by their snake_case names. `Weather.event` stores THESE ids;
## §5.10's printed order governs only the weighted selection scan, which weather.gd keeps.
const EVENT_DEFINITION: Dictionary = {
	"blight": 0, "calm_days": 1, "drought": 2, "early_frost": 3,
	"hard_freeze": 4, "heavy_rain": 5, "ideal_spell": 6,
}

## `FishHabitat.type`'s domain. The uppercase key spelling is the ruling's explicit choice; the
## resulting order is inherited from the ASCII rule, and disagrees with §5.4's printed
## River/Lake/Coast table order on every value.
const HABITAT_TYPE: Dictionary = {"COAST": 0, "LAKE": 1, "RIVER": 2}

const COMPILED_ENUM_DOMAINS: Array[String] = [
	CROP_FAMILY_DOMAIN, EVENT_DEFINITION_DOMAIN, HABITAT_TYPE_DOMAIN,
]

# --- legacy ordinal conversion (ruling §2: translate or refuse, never reinterpret) ---------------

## Old provisional module-local ordinal -> compiled id, indexed by the OLD ordinal.
## fishing.gd's §5.4 table order was RIVER=0, LAKE=1, COAST=2.
const HABITAT_TYPE_LEGACY_IDS: Array[int] = [2, 1, 0]
## weather.gd's §5.10 printed order was ideal_spell=0, heavy_rain=1, drought=2, blight=3,
## early_frost=4, hard_freeze=5, calm_days=6.
const EVENT_DEFINITION_LEGACY_IDS: Array[int] = [6, 5, 2, 0, 3, 4, 1]
## farming.gd's §5.6 printed order was CEREAL=0, ROOT=1, LEGUME=2, LEAF=3, FIBER=4.
const CROP_FAMILY_LEGACY_IDS: Array[int] = [0, 4, 3, 2, 1]


class DomainResult:
	"""Outcome of compiling one catalog domain: success flag, key->int32 id map, refusal reason."""
	var ok: bool
	var ids: Dictionary
	var error: String

	func _init(p_ok: bool, p_ids: Dictionary, p_error: String) -> void:
		"""Store the outcome fields for this domain compilation attempt."""
		ok = p_ok
		ids = p_ids
		error = p_error


class CompileReport:
	"""Outcome of compiling a whole batch of domains together, all-or-nothing.

	When ok is false, `domains` is empty: no partial result is ever produced, so a caller can
	never mutate its world state from a half-compiled catalog.
	"""
	var ok: bool
	var domains: Dictionary
	var error: String

	func _init(p_ok: bool, p_domains: Dictionary, p_error: String) -> void:
		"""Store the outcome fields for this batch compilation attempt."""
		ok = p_ok
		domains = p_domains
		error = p_error


class EnumLookup:
	"""Outcome of one compiled-enum lookup: success flag, resolved key, resolved id, refusal.

	`.ok` MUST be inspected first. A refusal carries no usable key or id -- there is no sentinel
	to mistake for an answer -- and `error` names what was rejected.
	"""
	var ok: bool
	var key: StringName
	var id: int
	var error: String

	func _init(p_ok: bool, p_key: StringName, p_id: int, p_error: String) -> void:
		"""Store the outcome fields for this lookup attempt."""
		ok = p_ok
		key = p_key
		id = p_id
		error = p_error


static func fixed_enum(domain_name: String) -> Dictionary:
	"""Return the explicitly numbered GDD §4.3 enum table for a protected domain name.

	Returns an empty Dictionary for any name that is not one of the protected enums.
	"""
	match domain_name:
		"Speed":
			return SPEED
		"Activity":
			return ACTIVITY
		"JobKind":
			return JOB_KIND
		"JobState":
			return JOB_STATE
		"ZoneType":
			return ZONE_TYPE
		"Season":
			return SEASON
		"Soil":
			return SOIL
		"CropState":
			return CROP_STATE
		"OrderMode":
			return ORDER_MODE
		"Quality":
			return QUALITY
		"Severity":
			return SEVERITY
		_:
			return {}


static func compiled_enum(domain_name: String) -> Dictionary:
	"""Return the ASCII-generated id table for one compiled enum domain.

	Returns an empty Dictionary for any name that is not a compiled domain, matching
	fixed_enum()'s treatment of a name it does not own.
	"""
	match domain_name:
		CROP_FAMILY_DOMAIN:
			return CROP_FAMILY
		EVENT_DEFINITION_DOMAIN:
			return EVENT_DEFINITION
		HABITAT_TYPE_DOMAIN:
			return HABITAT_TYPE
		_:
			return {}


static func compiled_enum_keys(domain_name: String) -> Array[StringName]:
	"""One compiled domain's keys in the form compile_domain() takes. Empty when unknown."""
	var table: Dictionary = compiled_enum(domain_name)
	var keys: Array[StringName] = []
	for key: String in table.keys():
		keys.append(StringName(key))
	return keys


static func verify_compiled_enum(domain_name: String) -> DomainResult:
	"""Prove a compiled domain's table IS what the ASCII compiler produces from its own keys.

	This is what makes those tables a transcription of a generated result rather than a second
	set of hand-chosen ordinals: every owning module calls it from `_init()`, so an edited number
	fails loudly instead of silently repointing persisted state at a different key.
	"""
	var table: Dictionary = compiled_enum(domain_name)
	if table.is_empty():
		return DomainResult.new(false, {}, "'%s' is not a compiled enum domain" % domain_name)
	var compiled: DomainResult = compile_domain(domain_name, compiled_enum_keys(domain_name))
	if not compiled.ok:
		return compiled
	for key: String in table.keys():
		var expected: int = int(compiled.ids[StringName(key)])
		if int(table[key]) != expected:
			var message: String = "'%s' key '%s' is %d but ascending ASCII order generates %d"
			return DomainResult.new(false, {},
				message % [domain_name, key, int(table[key]), expected])
	return DomainResult.new(true, compiled.ids, "")


static func compiled_id_of(domain_name: String, key: StringName) -> EnumLookup:
	"""The compiled id one key carries. Refuses an unknown domain and an unknown key."""
	var table: Dictionary = compiled_enum(domain_name)
	if table.is_empty():
		return EnumLookup.new(false, &"", 0, "'%s' is not a compiled enum domain" % domain_name)
	var name: String = String(key)
	if not table.has(name):
		return EnumLookup.new(false, &"", 0, "'%s' has no key '%s'" % [domain_name, name])
	return EnumLookup.new(true, key, int(table[name]), "")


static func compiled_key_of(domain_name: String, id: int) -> EnumLookup:
	"""The key one compiled id names. Refuses an unknown domain and an id no key carries."""
	var table: Dictionary = compiled_enum(domain_name)
	if table.is_empty():
		return EnumLookup.new(false, &"", 0, "'%s' is not a compiled enum domain" % domain_name)
	for name: String in table.keys():
		if int(table[name]) == id:
			return EnumLookup.new(true, StringName(name), id, "")
	return EnumLookup.new(false, &"", 0, "'%s' has no id %d" % [domain_name, id])


static func legacy_ids_of(domain_name: String) -> Array[int]:
	"""One compiled domain's old-ordinal -> compiled-id map. Empty when the name is unknown."""
	match domain_name:
		CROP_FAMILY_DOMAIN:
			return CROP_FAMILY_LEGACY_IDS
		EVENT_DEFINITION_DOMAIN:
			return EVENT_DEFINITION_LEGACY_IDS
		HABITAT_TYPE_DOMAIN:
			return HABITAT_TYPE_LEGACY_IDS
		_:
			return [] as Array[int]


static func convert_legacy_id(domain_name: String, legacy_id: int) -> EnumLookup:
	"""Translate one pre-ruling module-local ordinal into its compiled id, or refuse.

	The old provisional numbers are not interchangeable with these, so a retained development
	snapshot or replay fixture is translated here or rejected with an unsupported-schema message;
	it is never reinterpreted. §4.2's empty catalog id -1 means absence in both schemas and
	converts to itself, carrying no key because absence names none.
	"""
	var map: Array[int] = legacy_ids_of(domain_name)
	if map.is_empty():
		return EnumLookup.new(false, &"", 0, "'%s' is not a compiled enum domain" % domain_name)
	if legacy_id == EMPTY_CATALOG_ID:
		return EnumLookup.new(true, &"", EMPTY_CATALOG_ID, "")
	if legacy_id < 0 or legacy_id >= map.size():
		var message: String = "unsupported schema/catalog: '%s' has no legacy ordinal %d"
		return EnumLookup.new(false, &"", 0, message % [domain_name, legacy_id])
	return compiled_key_of(domain_name, map[legacy_id])


static func compile_domain(domain_name: String, keys: Array[StringName]) -> DomainResult:
	"""Compile one domain's keys into ascending-ASCII-ordered, insertion-order-independent IDs.

	Refuses without producing any IDs when: the domain name is a protected fixed enum, a key
	repeats, or the domain is ItemDefinition with more than 256 keys.
	"""
	var validation: DomainResult = _validate_domain(domain_name, keys)
	if not validation.ok:
		return validation
	return DomainResult.new(true, _assign_ascending_ids(keys), "")


static func compile_catalog(domains: Dictionary) -> CompileReport:
	"""Compile every domain in `domains` (domain name -> an Array of per-domain keys).

	Each domain's keys may be a plain untyped Array, as a data-driven loader (e.g. one reading
	item ids out of JSON) naturally produces, not only an `Array[StringName]` literal. Every
	element must be a StringName or a String (converted to StringName here); anything else, or a
	non-Array value, refuses the whole batch with a CompileReport instead of throwing.

	All-or-nothing: the first domain that fails aborts the whole batch and no domain's IDs are
	returned, per GDD §4.2's abort-before-mutate rule. Domain names are visited in their own
	ascending order purely for deterministic error reporting; each domain's IDs depend only on
	that domain's own key set.
	"""
	var domain_names: Array = domains.keys()
	domain_names.sort()
	var result_domains: Dictionary = {}
	for domain_name: String in domain_names:
		var raw_keys: Variant = domains[domain_name]
		if not (raw_keys is Array):
			return CompileReport.new(false, {}, "domain '%s' keys must be an Array" % domain_name)
		var coerced: Dictionary = _coerce_keys(domain_name, raw_keys)
		if not bool(coerced["ok"]):
			return CompileReport.new(false, {}, String(coerced["error"]))
		var keys: Array[StringName] = coerced["keys"]
		var result: DomainResult = compile_domain(domain_name, keys)
		if not result.ok:
			return CompileReport.new(false, {}, "domain '%s' failed: %s" % [domain_name, result.error])
		result_domains[domain_name] = result.ids
	return CompileReport.new(true, result_domains, "")


static func _coerce_keys(domain_name: String, raw_keys: Array) -> Dictionary:
	"""Convert an untyped Array of per-domain keys into a strict Array[StringName].

	Assigning a plain untyped Array straight into an `Array[StringName]` variable throws a
	SCRIPT ERROR in Godot even when every element is already a StringName, so each element is
	appended individually instead. A String element converts to StringName; any other element
	type refuses. Returns `{"ok": bool, "keys": Array[StringName], "error": String}`.
	"""
	var keys: Array[StringName] = []
	for index: int in raw_keys.size():
		var element: Variant = raw_keys[index]
		if element is StringName:
			keys.append(element)
		elif element is String:
			keys.append(StringName(element))
		else:
			var message: String = "domain '%s' key at index %d is not a String or StringName (got %s)"
			return {"ok": false, "keys": [] as Array[StringName], "error": message % [domain_name, index, type_string(typeof(element))]}
	return {"ok": true, "keys": keys, "error": ""}


static func _validate_domain(domain_name: String, keys: Array[StringName]) -> DomainResult:
	"""Reject a protected enum name, a duplicate key, or an oversized ItemDefinition catalog."""
	if PROTECTED_ENUM_DOMAINS.has(domain_name):
		return DomainResult.new(false, {}, "'%s' is a fixed enum and cannot be recompiled" % domain_name)
	var seen: Dictionary = {}
	for key: StringName in keys:
		if seen.has(key):
			return DomainResult.new(false, {}, "duplicate key '%s' in domain '%s'" % [key, domain_name])
		seen[key] = true
	if domain_name == ITEM_DEFINITION_DOMAIN and keys.size() > ITEM_DEFINITION_MAX_KEYS:
		var message: String = "ItemDefinition catalog exceeds %d keys (%d given)"
		return DomainResult.new(false, {}, message % [ITEM_DEFINITION_MAX_KEYS, keys.size()])
	return DomainResult.new(true, {}, "")


static func _assign_ascending_ids(keys: Array[StringName]) -> Dictionary:
	"""Map each key to its index in ascending ASCII order, independent of input order.

	StringName's own default comparator does not sort by string content (it may order by an
	internal interning detail instead), so keys are compared as String explicitly.
	"""
	var string_keys: Array[String] = []
	for key: StringName in keys:
		string_keys.append(String(key))
	string_keys.sort()
	var ids: Dictionary = {}
	for index: int in string_keys.size():
		ids[StringName(string_keys[index])] = index
	return ids
