extends RefCounted
## Deterministic catalog compiler and validator, per BAL-CAT-001 and GDD §4.2's closing paragraph.
##
## Every domain (SpeciesDefinition, ItemDefinition, RecipeDefinition, BuildingDefinition,
## CropDefinition, EventDefinition, ...) is compiled independently: its own StringName keys are
## sorted into ascending ASCII order and assigned int32 IDs 0..n-1 in that order, so the same key
## set always compiles to the same IDs regardless of the order the keys were declared or
## discovered in. Dictionary insertion order never leaks into an ID.
##
## The gameplay enums that GDD §4.3 gives explicit numeric values (Speed, Activity, JobKind,
## JobState, ZoneType, Season, Soil, CropState, OrderMode, Quality, Severity, RoomType,
## BuildingState) are fixed data here, never run through the compiler: they must never be
## renumbered, including the intentionally reserved gaps (JobKind.RESERVED_3, ZoneType.RESERVED_1).
## Milestone joined them on 2026-09-11 (decision 0074): §4.3 does not print it, but BAL-CAT-002
## numbers M0..M4 individually, which is the same "individually listed" test §4.2's closing
## paragraph applies -- so it is protected data, not compiler output.
## InjuryKind joined them on 2026-09-12 (decision 0108) under SET-MOVE-ECON-001 HAZ-001, which
## says in terms "Use integer state and existing GDD InjuryKind: NONE=0, CUT=1, BITE=2, FALL=3,
## EXPOSURE=4, EXHAUSTION=5. No new injury-kind enum ... is introduced." That was always an
## intentional artifact/digest change rather than a fix, and it moved both.
## §4.3 numbers three more that this module does not yet carry -- WorldMode, ResidentStatus,
## Role, FeastState -- so adding one is an intentional artifact/digest change, not a fix.
##
## Decision 0018 fixes the rule: every enum §4.3 numbers explicitly lives in
## PROTECTED_ENUM_DOMAINS, because the protected table is the thing that REFUSES a recompile. A
## module needing one of these numbers reads it from here (`const X: int = Catalog.ACTIVITY[...]`
## is a valid GDScript constant expression) rather than mirroring it locally, so there is exactly
## one copy of every specified value and no drift is possible.
##
## The COMPILED enum domains below are the other half of that rule, and are NOT protected. GDD
## §4.2's closing paragraph -- "All gameplay enum numeric values not individually listed are
## generated once from the lexicographically sorted ASCII catalog keys within their own domain"
## -- and BAL-CAT-002, which names crop-family explicitly, already number CropFamily,
## EventDefinition and HabitatType. Three modules missed that paragraph and used their display
## table's printed order instead; the ruling in docs/rulings/2026-09-09_ready06_open_item_answers.md
## §2 settles it. ARCH-CMD-003's CommandKind is the fourth, and the only one that was compiled
## from its owning specification the day it was implemented rather than corrected afterwards.
## BuildingDefinition and FurnitureDefinition are the fifth and sixth, added under decision 0056
## from gameplay_balance.md §4.1/§4.3 -- the owning full catalog -- COMPLETE rather than partial,
## because a domain published with only the starter colony's seven buildings renumbers every
## building the moment an eighth is implemented. RoomType and BuildingState arrived in the same
## change and went the other way, into PROTECTED_ENUM_DOMAINS: §4.3 numbers both individually.
## Station is the seventh compiled domain, added under decision 0074 from BAL-CAT-011's eleven
## service keys. It is a SEPARATE domain from BuildingDefinition even though eight keys are
## spelled the same, and the ids differ; see STATION below.
## They are declared here so the numbering lives in ONE place, and
## verify_compiled_enum() proves each table is exactly what compile_domain() produces from its own
## keys -- these are transcriptions of a generated result, never hand-chosen ordinals. They stay
## OUT of PROTECTED_ENUM_DOMAINS on purpose: protection means "§4.3 stated this number, never
## regenerate it", and §4.3 states none of these six.
##
## A compile_catalog() batch is all-or-nothing: if any domain in the batch fails validation, no
## domain's IDs are produced, matching GDD §4.2's "a registry validation failure aborts loading
## before mutating the current world."
##
## Persistence note (blocker U1): `catalog_ids.json` emission and its load-time hash check are
## unspecified (document shape, canonical serialization, and hash relationship to save-header
## offset 72 are not defined anywhere in the architecture doc) and are therefore NOT implemented
## here. This module compiles and validates in memory only; a future task adds the file once U1
## is resolved.

const ITEM_DEFINITION_DOMAIN: String = "ItemDefinition"
const ITEM_DEFINITION_MAX_KEYS: int = 256

## GDD §4.3 explicit enums: fixed data, never regenerated by the compiler below.
const SPEED: Dictionary = {"PAUSED": 0, "NORMAL": 1, "DOUBLE": 2, "QUADRUPLE": 4}
## §4.3: "Activity | SLEEP=0, ANYTHING=1, WORK=2, SOCIAL=3". Four values, no reserved gap.
const ACTIVITY: Dictionary = {"SLEEP": 0, "ANYTHING": 1, "WORK": 2, "SOCIAL": 3}
const JOB_KIND: Dictionary = {
	"HAUL": 0, "BUILD": 1, "FISH": 2, "RESERVED_3": 3, "FORAGE": 4, "FARM": 5,
	"COOK": 6, "PRESERVE": 7, "CRAFT": 8, "TEND": 9, "KEEP": 10, "HEAL": 11,
}
## §4.3: "JobState | QUEUED=0, RESERVED=1, TRAVEL=2, WORK=3, HAUL_OUTPUT=4, COMPLETE=5,
## BLOCKED=6, CANCELLED=7". WORK=3 here is a JobState, unrelated to Activity.WORK=2.
const JOB_STATE: Dictionary = {
	"QUEUED": 0, "RESERVED": 1, "TRAVEL": 2, "WORK": 3,
	"HAUL_OUTPUT": 4, "COMPLETE": 5, "BLOCKED": 6, "CANCELLED": 7,
}
const ZONE_TYPE: Dictionary = {
	"FISH": 0, "RESERVED_1": 1, "FORAGE": 2, "FARM": 3, "ORCHARD": 4,
	"FORESTRY": 5, "QUARRY": 6, "STOCKPILE": 7, "CONSERVATION": 8,
}
const SEASON: Dictionary = {"SPRING": 0, "SUMMER": 1, "AUTUMN": 2, "WINTER": 3}
## §4.3: "Soil | LOAM=0, CLAY=1, SAND=2". GDD §5.6 and BAL-CROP-001 build `allowed_soils` as
## `1<<Soil` from exactly these ordinals, so renumbering them silently repoints every crop's
## soil mask at a different soil.
const SOIL: Dictionary = {"LOAM": 0, "CLAY": 1, "SAND": 2}
## §4.3: "CropState | EMPTY=0, SOWN=1, GROWING=2, RIPE=3, WITHERED=4". `FarmPlot.state` is
## persisted state, so these five are save-carried.
const CROP_STATE: Dictionary = {
	"EMPTY": 0, "SOWN": 1, "GROWING": 2, "RIPE": 3, "WITHERED": 4,
}
## §4.3: "OrderMode | ONCE=0, REPEAT=1, MAINTAIN_STOCK=2". `ProductionOrder.mode` in §4.2.
const ORDER_MODE: Dictionary = {"ONCE": 0, "REPEAT": 1, "MAINTAIN_STOCK": 2}
const QUALITY: Dictionary = {"POOR": 0, "PLAIN": 1, "GOOD": 2, "EXCELLENT": 3}
## §4.3: "InjuryKind | NONE=0, CUT=1, BITE=2, FALL=3, EXPOSURE=4, EXHAUSTION=5" (game_gdd.md:215).
## `Injury.kind` in §4.2 is persisted state, so these six are save-carried, and they are NOT the
## ascending ASCII order of their own keys (that would be BITE=0, CUT=1, EXHAUSTION=2,
## EXPOSURE=3, FALL=4, NONE=5). §4.2's closing paragraph therefore does not reach them: §4.3
## lists them individually and they are protected, per decision 0018.
##
## SET-MOVE-ECON-001 HAZ-002/HAZ-003 bind three of these six to new hazard outcomes -- airless
## submergence raises EXPOSURE, rest-zero raises EXHAUSTION, a declared drop raises FALL -- by
## REUSING these numbers. No parallel kind domain exists and none may be created; a module that
## needs one of these values reads `Catalog.INJURY_KIND[...]` rather than mirroring it. Severity
## values, hourly drains, care work and the aggregate Injury store are NOT here: they belong to
## the injury/care owner (task 08), and this table carries identity only.
const INJURY_KIND: Dictionary = {
	"NONE": 0, "CUT": 1, "BITE": 2, "FALL": 3, "EXPOSURE": 4, "EXHAUSTION": 5,
}
const SEVERITY: Dictionary = {"INFO": 0, "ADVISORY": 1, "WARNING": 2, "CRITICAL": 3}
## §4.3: "RoomType | DORMITORY=0, PRIVATE_ROOM=1, KITCHEN=2, DINING=3, COMMON=4, INFIRMARY=5,
## PANTRY=6, CORRIDOR=7". `Room.type` in §4.2 is persisted, and these numbers are NOT the
## ascending ASCII order of their own keys (that would be COMMON=0, CORRIDOR=1, DINING=2,
## DORMITORY=3, INFIRMARY=4, KITCHEN=5, PANTRY=6, PRIVATE_ROOM=7), so §4.2's closing paragraph
## does not reach them: §4.3 lists them individually and they are protected, per decision 0018.
const ROOM_TYPE: Dictionary = {
	"DORMITORY": 0, "PRIVATE_ROOM": 1, "KITCHEN": 2, "DINING": 3,
	"COMMON": 4, "INFIRMARY": 5, "PANTRY": 6, "CORRIDOR": 7,
}
## §4.3: "BuildingState | BLUEPRINT=0, BUILDING=1, ACTIVE=2, PAUSED=3, DAMAGED=4, DEMOLISHING=5".
## `Building.state` in §4.2, likewise persisted and likewise not in its own keys' ASCII order.
const BUILDING_STATE: Dictionary = {
	"BLUEPRINT": 0, "BUILDING": 1, "ACTIVE": 2, "PAUSED": 3, "DAMAGED": 4, "DEMOLISHING": 5,
}

## The unlock domain of `BuildingDefinition.unlock`, `RecipeDefinition.unlock` and
## `Progress.milestone`, published under R-BUILD-DOM-001 (decision 0074).
##
## PROTECTED, NOT COMPILED, and that distinction decides the numbers. GDD §4.2's closing
## paragraph generates only the values "not individually listed"; BAL-CAT-002 lists these
## individually -- "Unlock values are M0=0, M1=1, M2=2, M3=3, M4=4" (gameplay_balance.md:43) --
## so §4.2's ASCII rule does not reach them. Here the two happen to agree, because "M0".."M4"
## sort into the same order; that coincidence is exactly why the domain must be PROTECTED
## anyway. A protected table REFUSES recompilation, so a later key ("M10", or a renamed
## "HEARTH_CHARTER") cannot silently renumber a persisted ordinal by re-sorting.
##
## The keys are the milestone identifiers GDD §5.11 prints in its own condition table
## ("M0 Refuge", "M1 Settled Hearth", ... "M4 Hearth Charter", game_gdd.md:781-786). §5.9's
## building table prints `Start` in the unlock column; R-BUILD-DOM-001 rules that "`Start` is a
## source-table label mapping to M0, not a sixth catalog key", so it is NOT a key here and is
## normalized at source import only -- `milestones.gd`'s `id_of_source_label()` is the one place
## that translates it.
##
## Bit m of `World.milestone_mask` / `Progress.unlocked_mask` means milestone m was AWARDED.
## `milestones.gd` owns that binding and the unlock gate; this table owns only the five ordinals.
const MILESTONE: Dictionary = {"M0": 0, "M1": 1, "M2": 2, "M3": 3, "M4": 4}

const PROTECTED_ENUM_DOMAINS: Array[String] = [
	"Speed", "Activity", "JobKind", "JobState", "ZoneType", "Season", "Soil", "CropState",
	"OrderMode", "Quality", "InjuryKind", "Severity", "RoomType", "BuildingState", "Milestone",
]

## Domain name -> its §4.3 table, so that adding a protected enum is one entry rather than one
## more `match` arm in a function that would then exceed the 30-line limit. The two lists are
## checked against each other by the suite: a name here that is absent from
## PROTECTED_ENUM_DOMAINS would be recompilable, which is the drift decision 0018 prevents.
const FIXED_ENUM_TABLES: Dictionary = {
	"Speed": SPEED, "Activity": ACTIVITY, "JobKind": JOB_KIND, "JobState": JOB_STATE,
	"ZoneType": ZONE_TYPE, "Season": SEASON, "Soil": SOIL, "CropState": CROP_STATE,
	"OrderMode": ORDER_MODE, "Quality": QUALITY, "InjuryKind": INJURY_KIND,
	"Severity": SEVERITY, "RoomType": ROOM_TYPE,
	"BuildingState": BUILDING_STATE, "Milestone": MILESTONE,
}

# --- compiled enum domains (GDD §4.2 closing paragraph, BAL-CAT-001/002) -------------------------

const BUILDING_DEFINITION_DOMAIN: String = "BuildingDefinition"
const COMMAND_KIND_DOMAIN: String = "CommandKind"
const CROP_FAMILY_DOMAIN: String = "CropFamily"
const EVENT_DEFINITION_DOMAIN: String = "EventDefinition"
const FURNITURE_DEFINITION_DOMAIN: String = "FurnitureDefinition"
const HABITAT_TYPE_DOMAIN: String = "HabitatType"
const STATION_DOMAIN: String = "Station"

## The protected Milestone domain's own name, used wherever a caller asks for it by string.
const MILESTONE_DOMAIN: String = "Milestone"

## The protected InjuryKind domain's own name. SET-MOVE-ECON-001 HAZ-001/002/003 and the
## aggregate injury/care owner ask for it by string; nothing else may spell it.
const INJURY_KIND_DOMAIN: String = "InjuryKind"

## GDD §4.2: "empty catalog IDs are -1". Absence, never a refusal channel and never a key.
const EMPTY_CATALOG_ID: int = -1

## ARCH-CMD-003's 24 settlement command kinds. The architecture prints them as a "`[NEW sorted
## ASCII domain]`" and says "compile IDs from this exact list; reject unknown kinds", so the list
## IS the domain and its order is the ASCII rule's own output, proven by verify_compiled_enum()
## like the three below. The ids are save- and replay-carried (§8.1's command record field at
## offset 20), so renumbering one silently re-points every stored command at a different action.
## ARCH-CMD-002's speed/pause scheduler events are deliberately ABSENT: task 04.1 requires them
## queued separately and says in terms "retain ARCH-CMD-003's 24 stable command IDs unchanged. Do
## not insert speed/pause keys into the sorted catalog" -- inserting one would renumber every kind
## that sorts after it.
const COMMAND_KIND: Dictionary = {
	"ACCEPT_CANDIDATES": 0, "APPOINT_WARDEN": 1, "ASSIGN_BED": 2, "CANCEL_JOB": 3,
	"CANCEL_MANUAL": 4, "CONFIRM_FEAST": 5, "DEMOLISH": 6, "DESIGNATE_ROOM": 7,
	"DESIGNATE_ZONE": 8, "EDIT_ORDER": 9, "EQUIP": 10, "NAME_RESIDENT": 11,
	"PLACE_BLUEPRINT": 12, "PLACE_FURNITURE": 13, "REQUEST_RELIEF_SEEDS": 14,
	"SET_ACTIVITY_SCHEDULE": 15, "SET_DOOR_OPEN": 16, "SET_FIELD_ROTATION": 17,
	"SET_JOB_PRIORITIES": 18, "SET_MANUAL_TASK": 19, "SET_POLICY": 20, "SET_STORE_FILTER": 21,
	"SET_STORE_MINIMUM": 22, "UPGRADE": 23,
}

## BAL-CAT-002: "Category, effect, recipe-family, crop-family, and station domains use the keys
## printed in these tables and numeric IDs generated by BAL-CAT-001." The keys are §5.6's own
## uppercase family names; the IDs are their ascending ASCII order, not §5.6's printed order.
const CROP_FAMILY: Dictionary = {"CEREAL": 0, "FIBER": 1, "LEAF": 2, "LEGUME": 3, "ROOT": 4}

## §5.10's seven event rows, keyed by their snake_case names. `Weather.event` stores THESE ids;
## §5.10's printed order governs only the weighted selection scan, which weather.gd keeps.
const EVENT_DEFINITION: Dictionary = {
	"blight": 0, "calm_days": 1, "drought": 2, "early_frost": 3,
	"hard_freeze": 4, "heavy_rain": 5, "ideal_spell": 6,
}

## `FishHabitat.type`'s domain. The uppercase key spelling is the ruling's explicit choice; the
## resulting order is inherited from the ASCII rule, and disagrees with §5.4's printed
## River/Lake/Coast table order on every value.
const HABITAT_TYPE: Dictionary = {"COAST": 0, "LAKE": 1, "RIVER": 2}

## `Building.type_id`'s domain: ALL THIRTY of the owning catalog's BuildingDefinition rows
## (gameplay_balance.md §4.1, whose normalized keys join GDD §5.9's thirty printed building rows
## and are the stable identifiers BAL-CAT-006/007 build definitions from). The complete domain is
## published here rather than the seven keys the starter colony happens to place, because a
## partial domain renumbers every building the moment an eighth is implemented -- and these ids
## are persisted in `Building.type_id`.
##
## The keys are identifiers, never display names: §5.9 prints "Refuge/community hall",
## "Workbench shelter" and "Preserver/smokehouse" while the owning rows key them `hall`,
## `workbench` and `preserver`. Ordering is the ASCII rule's output over those keys, proven by
## verify_compiled_enum(), and has nothing to do with either printed order.
##
## This domain carries IDENTITY ONLY. Footprints, materials, work, slots, managed_interior,
## room_tiles, unlock, base_store_g, passive_slots and max_builders live in the owning catalog's
## §4.1/§4.2 rows and belong to the packed Building store that reads them; none of them is
## transcribed here, so there is no second copy of a value to drift.
const BUILDING_DEFINITION: Dictionary = {
	"apiary": 0, "boathouse": 1, "brewery": 2,
	"cellar": 3, "composter": 4, "covered_store": 5,
	"dirt_path": 6, "dryer": 7, "fence": 8,
	"fisher_shelter": 9, "forester_lodge": 10, "gate": 11,
	"hall": 12, "infirmary": 13, "kitchen": 14,
	"lookout": 15, "memorial_garden": 16, "mill": 17,
	"nursery": 18, "open_stockpile": 19, "paved_path": 20,
	"preserver": 21, "quarry_shed": 22, "residence": 23,
	"saltpan": 24, "stone_wall": 25, "weir": 26,
	"well": 27, "workbench": 28, "workshop": 29,
}

## `Furniture.type_id`'s domain: all NINE of the owning catalog's FurnitureDefinition rows
## (gameplay_balance.md §4.3, joining GDD §5.9's nine printed furniture rows). BAL-CAT-007: "a
## building ID denotes its exterior structure. Furniture definitions occupy a separate domain" --
## so this is its own domain and a furniture id is never a building id. Identity only, on the
## same terms as BUILDING_DEFINITION above.
const FURNITURE_DEFINITION: Dictionary = {
	"bed": 0, "decoration": 1, "hearth": 2,
	"interior_door": 3, "interior_partition": 4, "kitchen_bench": 5,
	"patient_bed": 6, "seat": 7, "shelf": 8,
}

## `RecipeDefinition.station`'s domain: all ELEVEN service keys BAL-CAT-011 authors
## (gameplay_balance.md:60), published under R-BUILD-DOM-002 (decision 0074).
##
## THIS IS NOT `BuildingDefinition`. BAL-CAT-011 says in terms that `station` "indexes a
## **service domain**, not the BuildingDefinition index", and eight of these keys are spelled
## identically to building keys while carrying different ids: `kitchen` is service 3 and
## building 14, `well` is service 8 and building 27, `workshop` is service 10 and building 29.
## A range check cannot catch a wrong-domain integer here, because every station id is also a
## valid building id; only importing by the field's named domain can. `building_definitions.gd`
## holds the explicit building -> station provider mapping, so the two are joined in one place.
##
## `kitchen_bench` is a FurnitureDefinition, not a twelfth station key: BAL-CAT-011 gives the
## kitchen service two providers -- "one exterior kitchen's 2 cooking slots or each valid
## interior kitchen_bench's 1 slot" -- and both satisfy service id 3 through different refs.
##
## Ordering is the ASCII rule's own output over these keys, proven by verify_compiled_enum().
const STATION: Dictionary = {
	"brewery": 0, "composter": 1, "dryer": 2,
	"kitchen": 3, "mill": 4, "nursery": 5,
	"preserver": 6, "saltpan": 7, "well": 8,
	"workbench": 9, "workshop": 10,
}

const COMPILED_ENUM_DOMAINS: Array[String] = [
	BUILDING_DEFINITION_DOMAIN, COMMAND_KIND_DOMAIN, CROP_FAMILY_DOMAIN,
	EVENT_DEFINITION_DOMAIN, FURNITURE_DEFINITION_DOMAIN, HABITAT_TYPE_DOMAIN,
	STATION_DOMAIN,
]

# --- SET-MOVE-ECON-001 catalog work this module does NOT carry, and exactly why ------------------
#
# BLOCKER EH-01-A: the `excavated_earth` ItemDefinition row. ECON-002 authors it completely --
# category MATERIAL, mass 1000 g/U, nutrition 0, shelf_hours 0, raw_edible false, seed false,
# effect NONE, effect_value 0 -- and forbids aliasing `stone` or `compost` onto it. It is NOT
# added here because the ItemDefinition catalog has exactly one authored source:
# docs/gameplay_balance.md §3.1, mechanically extracted by tools/extract_item_definitions.py
# (whose EXPECTED_ROW_COUNT is 60) into res://data/item_definitions.json. Adding the key to the
# JSON or to this module without the §3.1 row would be the hand-copied second catalog that
# pipeline exists to prevent, and the suite runs the real extractor against the real document, so
# it would fail honestly. Both files are outside this change's ownership; the §3.1 row and the
# row-count bump are reported to the owner rather than invented here.
#
# BLOCKER EH-01-B: the InventoryLot provenance domain. GDD §4.2 types `InventoryLot.provenance`
# as `enum` and §4.3 does NOT number it, so under §4.2's closing paragraph it is compiled from
# its own sorted ASCII keys -- exactly as inventory.gd's own note says ("Provenance ... [is an]
# OPAQUE int32 catalog enum value ... compiled by catalog.gd from sorted ASCII keys"). ECON-002
# supplies three members (EXCAVATION, BACKFILL_RECLAIM, SPOIL_RECLAIM); §5.1 names STARTER for
# the initial loose lots and §5.7 a coastal-brine kind the salt recipe filters on. But NO
# specification declares the domain's NAME or its
# complete key set. A domain name is the artifact's own object key, and a partial key set
# renumbers every member the moment the next one lands -- the failure BUILDING_DEFINITION was
# published complete to avoid. Publishing three of an unknown number of keys under an invented
# name would bake a wrong, save-carried numbering into the digest. It is therefore refused here,
# not guessed, on the same grounds catalog_ids.gd refuses to name the entity-kind and RNG-stream
# domains. Unblocking it needs one ruling: the domain name plus the complete member list.

# --- legacy ordinal conversion (ruling §2: translate or refuse, never reinterpret) ---------------

## Old provisional module-local ordinal -> compiled id, indexed by the OLD ordinal.
## fishing.gd's §5.4 table order was RIVER=0, LAKE=1, COAST=2.
const HABITAT_TYPE_LEGACY_IDS: Array[int] = [2, 1, 0]
## weather.gd's §5.10 printed order was ideal_spell=0, heavy_rain=1, drought=2, blight=3,
## early_frost=4, hard_freeze=5, calm_days=6.
const EVENT_DEFINITION_LEGACY_IDS: Array[int] = [6, 5, 2, 0, 3, 4, 1]
## farming.gd's §5.6 printed order was CEREAL=0, ROOT=1, LEGUME=2, LEAF=3, FIBER=4.
const CROP_FAMILY_LEGACY_IDS: Array[int] = [0, 4, 3, 2, 1]


class DomainResult:
	"""Outcome of compiling one catalog domain: success flag, key->int32 id map, refusal reason."""
	var ok: bool
	var ids: Dictionary
	var error: String

	func _init(p_ok: bool, p_ids: Dictionary, p_error: String) -> void:
		"""Store the outcome fields for this domain compilation attempt."""
		ok = p_ok
		ids = p_ids
		error = p_error


class CompileReport:
	"""Outcome of compiling a whole batch of domains together, all-or-nothing.

	When ok is false, `domains` is empty: no partial result is ever produced, so a caller can
	never mutate its world state from a half-compiled catalog.
	"""
	var ok: bool
	var domains: Dictionary
	var error: String

	func _init(p_ok: bool, p_domains: Dictionary, p_error: String) -> void:
		"""Store the outcome fields for this batch compilation attempt."""
		ok = p_ok
		domains = p_domains
		error = p_error


class EnumLookup:
	"""Outcome of one compiled-enum lookup: success flag, resolved key, resolved id, refusal.

	`.ok` MUST be inspected first. A refusal carries no usable key or id -- there is no sentinel
	to mistake for an answer -- and `error` names what was rejected.
	"""
	var ok: bool
	var key: StringName
	var id: int
	var error: String

	func _init(p_ok: bool, p_key: StringName, p_id: int, p_error: String) -> void:
		"""Store the outcome fields for this lookup attempt."""
		ok = p_ok
		key = p_key
		id = p_id
		error = p_error


static func fixed_enum(domain_name: String) -> Dictionary:
	"""Return the explicitly numbered GDD §4.3 enum table for a protected domain name.

	Returns an empty Dictionary for any name that is not one of the protected enums.
	"""
	if not FIXED_ENUM_TABLES.has(domain_name):
		return {}
	return FIXED_ENUM_TABLES[domain_name]


static func compiled_enum(domain_name: String) -> Dictionary:
	"""Return the ASCII-generated id table for one compiled enum domain.

	Returns an empty Dictionary for any name that is not a compiled domain, matching
	fixed_enum()'s treatment of a name it does not own.
	"""
	match domain_name:
		BUILDING_DEFINITION_DOMAIN:
			return BUILDING_DEFINITION
		COMMAND_KIND_DOMAIN:
			return COMMAND_KIND
		CROP_FAMILY_DOMAIN:
			return CROP_FAMILY
		EVENT_DEFINITION_DOMAIN:
			return EVENT_DEFINITION
		FURNITURE_DEFINITION_DOMAIN:
			return FURNITURE_DEFINITION
		HABITAT_TYPE_DOMAIN:
			return HABITAT_TYPE
		STATION_DOMAIN:
			return STATION
		_:
			return {}


static func compiled_enum_keys(domain_name: String) -> Array[StringName]:
	"""One compiled domain's keys in the form compile_domain() takes. Empty when unknown."""
	var table: Dictionary = compiled_enum(domain_name)
	var keys: Array[StringName] = []
	for key: String in table.keys():
		keys.append(StringName(key))
	return keys


static func verify_compiled_enum(domain_name: String) -> DomainResult:
	"""Prove a compiled domain's table IS what the ASCII compiler produces from its own keys.

	This is what makes those tables a transcription of a generated result rather than a second
	set of hand-chosen ordinals: every owning module calls it from `_init()`, so an edited number
	fails loudly instead of silently repointing persisted state at a different key.
	"""
	var table: Dictionary = compiled_enum(domain_name)
	if table.is_empty():
		return DomainResult.new(false, {}, "'%s' is not a compiled enum domain" % domain_name)
	var compiled: DomainResult = compile_domain(domain_name, compiled_enum_keys(domain_name))
	if not compiled.ok:
		return compiled
	for key: String in table.keys():
		var expected: int = int(compiled.ids[StringName(key)])
		if int(table[key]) != expected:
			var message: String = "'%s' key '%s' is %d but ascending ASCII order generates %d"
			return DomainResult.new(false, {},
				message % [domain_name, key, int(table[key]), expected])
	return DomainResult.new(true, compiled.ids, "")


static func compiled_id_of(domain_name: String, key: StringName) -> EnumLookup:
	"""The compiled id one key carries. Refuses an unknown domain and an unknown key."""
	var table: Dictionary = compiled_enum(domain_name)
	if table.is_empty():
		return EnumLookup.new(false, &"", 0, "'%s' is not a compiled enum domain" % domain_name)
	var name: String = String(key)
	if not table.has(name):
		return EnumLookup.new(false, &"", 0, "'%s' has no key '%s'" % [domain_name, name])
	return EnumLookup.new(true, key, int(table[name]), "")


static func compiled_key_of(domain_name: String, id: int) -> EnumLookup:
	"""The key one compiled id names. Refuses an unknown domain and an id no key carries."""
	var table: Dictionary = compiled_enum(domain_name)
	if table.is_empty():
		return EnumLookup.new(false, &"", 0, "'%s' is not a compiled enum domain" % domain_name)
	for name: String in table.keys():
		if int(table[name]) == id:
			return EnumLookup.new(true, StringName(name), id, "")
	return EnumLookup.new(false, &"", 0, "'%s' has no id %d" % [domain_name, id])


static func legacy_ids_of(domain_name: String) -> Array[int]:
	"""One compiled domain's old-ordinal -> compiled-id map. Empty when the name is unknown."""
	match domain_name:
		CROP_FAMILY_DOMAIN:
			return CROP_FAMILY_LEGACY_IDS
		EVENT_DEFINITION_DOMAIN:
			return EVENT_DEFINITION_LEGACY_IDS
		HABITAT_TYPE_DOMAIN:
			return HABITAT_TYPE_LEGACY_IDS
		_:
			return [] as Array[int]


static func convert_legacy_id(domain_name: String, legacy_id: int) -> EnumLookup:
	"""Translate one pre-ruling module-local ordinal into its compiled id, or refuse.

	The old provisional numbers are not interchangeable with these, so a retained development
	snapshot or replay fixture is translated here or rejected with an unsupported-schema message;
	it is never reinterpreted. §4.2's empty catalog id -1 means absence in both schemas and
	converts to itself, carrying no key because absence names none.

	A compiled domain that never HAD other ordinals -- CommandKind was compiled from ARCH-CMD-003
	on the day it was implemented -- refuses every legacy ordinal with its own message, so
	"nothing to convert" cannot be misread as "no such domain".
	"""
	if compiled_enum(domain_name).is_empty():
		return EnumLookup.new(false, &"", 0, "'%s' is not a compiled enum domain" % domain_name)
	var map: Array[int] = legacy_ids_of(domain_name)
	if map.is_empty():
		var no_legacy: String = "'%s' was never numbered any other way; no legacy ordinal converts"
		return EnumLookup.new(false, &"", 0, no_legacy % domain_name)
	if legacy_id == EMPTY_CATALOG_ID:
		return EnumLookup.new(true, &"", EMPTY_CATALOG_ID, "")
	if legacy_id < 0 or legacy_id >= map.size():
		var message: String = "unsupported schema/catalog: '%s' has no legacy ordinal %d"
		return EnumLookup.new(false, &"", 0, message % [domain_name, legacy_id])
	return compiled_key_of(domain_name, map[legacy_id])


static func compile_domain(domain_name: String, keys: Array[StringName]) -> DomainResult:
	"""Compile one domain's keys into ascending-ASCII-ordered, insertion-order-independent IDs.

	Refuses without producing any IDs when: the domain name is a protected fixed enum, a key
	repeats, or the domain is ItemDefinition with more than 256 keys.
	"""
	var validation: DomainResult = _validate_domain(domain_name, keys)
	if not validation.ok:
		return validation
	return DomainResult.new(true, _assign_ascending_ids(keys), "")


static func compile_catalog(domains: Dictionary) -> CompileReport:
	"""Compile every domain in `domains` (domain name -> an Array of per-domain keys).

	Each domain's keys may be a plain untyped Array, as a data-driven loader (e.g. one reading
	item ids out of JSON) naturally produces, not only an `Array[StringName]` literal. Every
	element must be a StringName or a String (converted to StringName here); anything else, or a
	non-Array value, refuses the whole batch with a CompileReport instead of throwing.

	All-or-nothing: the first domain that fails aborts the whole batch and no domain's IDs are
	returned, per GDD §4.2's abort-before-mutate rule. Domain names are visited in their own
	ascending order purely for deterministic error reporting; each domain's IDs depend only on
	that domain's own key set.
	"""
	var domain_names: Array = domains.keys()
	domain_names.sort()
	var result_domains: Dictionary = {}
	for domain_name: String in domain_names:
		var raw_keys: Variant = domains[domain_name]
		if not (raw_keys is Array):
			return CompileReport.new(false, {}, "domain '%s' keys must be an Array" % domain_name)
		var coerced: Dictionary = _coerce_keys(domain_name, raw_keys)
		if not bool(coerced["ok"]):
			return CompileReport.new(false, {}, String(coerced["error"]))
		var keys: Array[StringName] = coerced["keys"]
		var result: DomainResult = compile_domain(domain_name, keys)
		if not result.ok:
			return CompileReport.new(false, {}, "domain '%s' failed: %s" % [domain_name, result.error])
		result_domains[domain_name] = result.ids
	return CompileReport.new(true, result_domains, "")


static func _coerce_keys(domain_name: String, raw_keys: Array) -> Dictionary:
	"""Convert an untyped Array of per-domain keys into a strict Array[StringName].

	Assigning a plain untyped Array straight into an `Array[StringName]` variable throws a
	SCRIPT ERROR in Godot even when every element is already a StringName, so each element is
	appended individually instead. A String element converts to StringName; any other element
	type refuses. Returns `{"ok": bool, "keys": Array[StringName], "error": String}`.
	"""
	var keys: Array[StringName] = []
	for index: int in raw_keys.size():
		var element: Variant = raw_keys[index]
		if element is StringName:
			keys.append(element)
		elif element is String:
			keys.append(StringName(element))
		else:
			var message: String = "domain '%s' key at index %d is not a String or StringName (got %s)"
			return {"ok": false, "keys": [] as Array[StringName], "error": message % [domain_name, index, type_string(typeof(element))]}
	return {"ok": true, "keys": keys, "error": ""}


static func _validate_domain(domain_name: String, keys: Array[StringName]) -> DomainResult:
	"""Reject a protected enum name, a duplicate key, or an oversized ItemDefinition catalog."""
	if PROTECTED_ENUM_DOMAINS.has(domain_name):
		return DomainResult.new(false, {}, "'%s' is a fixed enum and cannot be recompiled" % domain_name)
	var seen: Dictionary = {}
	for key: StringName in keys:
		if seen.has(key):
			return DomainResult.new(false, {}, "duplicate key '%s' in domain '%s'" % [key, domain_name])
		seen[key] = true
	if domain_name == ITEM_DEFINITION_DOMAIN and keys.size() > ITEM_DEFINITION_MAX_KEYS:
		var message: String = "ItemDefinition catalog exceeds %d keys (%d given)"
		return DomainResult.new(false, {}, message % [ITEM_DEFINITION_MAX_KEYS, keys.size()])
	return DomainResult.new(true, {}, "")


static func _assign_ascending_ids(keys: Array[StringName]) -> Dictionary:
	"""Map each key to its index in ascending ASCII order, independent of input order.

	StringName's own default comparator does not sort by string content (it may order by an
	internal interning detail instead), so keys are compared as String explicitly.
	"""
	var string_keys: Array[String] = []
	for key: StringName in keys:
		string_keys.append(String(key))
	string_keys.sort()
	var ids: Dictionary = {}
	for index: int in string_keys.size():
		ids[StringName(string_keys[index])] = index
	return ids
