extends RefCounted
## Deterministic catalog compiler and validator, per BAL-CAT-001 and GDD §4.2's closing paragraph.
##
## Every domain (SpeciesDefinition, ItemDefinition, RecipeDefinition, BuildingDefinition,
## CropDefinition, EventDefinition, ...) is compiled independently: its own StringName keys are
## sorted into ascending ASCII order and assigned int32 IDs 0..n-1 in that order, so the same key
## set always compiles to the same IDs regardless of the order the keys were declared or
## discovered in. Dictionary insertion order never leaks into an ID.
##
## The handful of gameplay enums that GDD §4.3 gives explicit numeric values (Speed, Activity,
## JobKind, JobState, ZoneType, Season, Soil, CropState, OrderMode, Quality, Severity) are fixed
## data here, never run through the compiler: they must never be renumbered, including the
## intentionally reserved gaps (JobKind.RESERVED_3, ZoneType.RESERVED_1).
##
## Decision 0018 fixes the rule: every enum §4.3 numbers explicitly lives in
## PROTECTED_ENUM_DOMAINS, because the protected table is the thing that REFUSES a recompile. A
## module needing one of these numbers reads it from here (`const X: int = Catalog.ACTIVITY[...]`
## is a valid GDScript constant expression) rather than mirroring it locally, so there is exactly
## one copy of every specified value and no drift is possible.
##
## A compile_catalog() batch is all-or-nothing: if any domain in the batch fails validation, no
## domain's IDs are produced, matching GDD §4.2's "a registry validation failure aborts loading
## before mutating the current world."
##
## Persistence note (blocker U1): `catalog_ids.json` emission and its load-time hash check are
## unspecified (document shape, canonical serialization, and hash relationship to save-header
## offset 72 are not defined anywhere in the architecture doc) and are therefore NOT implemented
## here. This module compiles and validates in memory only; a future task adds the file once U1
## is resolved.

const ITEM_DEFINITION_DOMAIN: String = "ItemDefinition"
const ITEM_DEFINITION_MAX_KEYS: int = 256

## GDD §4.3 explicit enums: fixed data, never regenerated by the compiler below.
const SPEED: Dictionary = {"PAUSED": 0, "NORMAL": 1, "DOUBLE": 2, "QUADRUPLE": 4}
## §4.3: "Activity | SLEEP=0, ANYTHING=1, WORK=2, SOCIAL=3". Four values, no reserved gap.
const ACTIVITY: Dictionary = {"SLEEP": 0, "ANYTHING": 1, "WORK": 2, "SOCIAL": 3}
const JOB_KIND: Dictionary = {
	"HAUL": 0, "BUILD": 1, "FISH": 2, "RESERVED_3": 3, "FORAGE": 4, "FARM": 5,
	"COOK": 6, "PRESERVE": 7, "CRAFT": 8, "TEND": 9, "KEEP": 10, "HEAL": 11,
}
## §4.3: "JobState | QUEUED=0, RESERVED=1, TRAVEL=2, WORK=3, HAUL_OUTPUT=4, COMPLETE=5,
## BLOCKED=6, CANCELLED=7". WORK=3 here is a JobState, unrelated to Activity.WORK=2.
const JOB_STATE: Dictionary = {
	"QUEUED": 0, "RESERVED": 1, "TRAVEL": 2, "WORK": 3,
	"HAUL_OUTPUT": 4, "COMPLETE": 5, "BLOCKED": 6, "CANCELLED": 7,
}
const ZONE_TYPE: Dictionary = {
	"FISH": 0, "RESERVED_1": 1, "FORAGE": 2, "FARM": 3, "ORCHARD": 4,
	"FORESTRY": 5, "QUARRY": 6, "STOCKPILE": 7, "CONSERVATION": 8,
}
const SEASON: Dictionary = {"SPRING": 0, "SUMMER": 1, "AUTUMN": 2, "WINTER": 3}
## §4.3: "Soil | LOAM=0, CLAY=1, SAND=2". GDD §5.6 and BAL-CROP-001 build `allowed_soils` as
## `1<<Soil` from exactly these ordinals, so renumbering them silently repoints every crop's
## soil mask at a different soil.
const SOIL: Dictionary = {"LOAM": 0, "CLAY": 1, "SAND": 2}
## §4.3: "CropState | EMPTY=0, SOWN=1, GROWING=2, RIPE=3, WITHERED=4". `FarmPlot.state` is
## persisted state, so these five are save-carried.
const CROP_STATE: Dictionary = {
	"EMPTY": 0, "SOWN": 1, "GROWING": 2, "RIPE": 3, "WITHERED": 4,
}
## §4.3: "OrderMode | ONCE=0, REPEAT=1, MAINTAIN_STOCK=2". `ProductionOrder.mode` in §4.2.
const ORDER_MODE: Dictionary = {"ONCE": 0, "REPEAT": 1, "MAINTAIN_STOCK": 2}
const QUALITY: Dictionary = {"POOR": 0, "PLAIN": 1, "GOOD": 2, "EXCELLENT": 3}
const SEVERITY: Dictionary = {"INFO": 0, "ADVISORY": 1, "WARNING": 2, "CRITICAL": 3}

const PROTECTED_ENUM_DOMAINS: Array[String] = [
	"Speed", "Activity", "JobKind", "JobState", "ZoneType", "Season", "Soil", "CropState",
	"OrderMode", "Quality", "Severity",
]


class DomainResult:
	"""Outcome of compiling one catalog domain: success flag, key->int32 id map, refusal reason."""
	var ok: bool
	var ids: Dictionary
	var error: String

	func _init(p_ok: bool, p_ids: Dictionary, p_error: String) -> void:
		"""Store the outcome fields for this domain compilation attempt."""
		ok = p_ok
		ids = p_ids
		error = p_error


class CompileReport:
	"""Outcome of compiling a whole batch of domains together, all-or-nothing.

	When ok is false, `domains` is empty: no partial result is ever produced, so a caller can
	never mutate its world state from a half-compiled catalog.
	"""
	var ok: bool
	var domains: Dictionary
	var error: String

	func _init(p_ok: bool, p_domains: Dictionary, p_error: String) -> void:
		"""Store the outcome fields for this batch compilation attempt."""
		ok = p_ok
		domains = p_domains
		error = p_error


static func fixed_enum(domain_name: String) -> Dictionary:
	"""Return the explicitly numbered GDD §4.3 enum table for a protected domain name.

	Returns an empty Dictionary for any name that is not one of the protected enums.
	"""
	match domain_name:
		"Speed":
			return SPEED
		"Activity":
			return ACTIVITY
		"JobKind":
			return JOB_KIND
		"JobState":
			return JOB_STATE
		"ZoneType":
			return ZONE_TYPE
		"Season":
			return SEASON
		"Soil":
			return SOIL
		"CropState":
			return CROP_STATE
		"OrderMode":
			return ORDER_MODE
		"Quality":
			return QUALITY
		"Severity":
			return SEVERITY
		_:
			return {}


static func compile_domain(domain_name: String, keys: Array[StringName]) -> DomainResult:
	"""Compile one domain's keys into ascending-ASCII-ordered, insertion-order-independent IDs.

	Refuses without producing any IDs when: the domain name is a protected fixed enum, a key
	repeats, or the domain is ItemDefinition with more than 256 keys.
	"""
	var validation: DomainResult = _validate_domain(domain_name, keys)
	if not validation.ok:
		return validation
	return DomainResult.new(true, _assign_ascending_ids(keys), "")


static func compile_catalog(domains: Dictionary) -> CompileReport:
	"""Compile every domain in `domains` (domain name -> an Array of per-domain keys).

	Each domain's keys may be a plain untyped Array, as a data-driven loader (e.g. one reading
	item ids out of JSON) naturally produces, not only an `Array[StringName]` literal. Every
	element must be a StringName or a String (converted to StringName here); anything else, or a
	non-Array value, refuses the whole batch with a CompileReport instead of throwing.

	All-or-nothing: the first domain that fails aborts the whole batch and no domain's IDs are
	returned, per GDD §4.2's abort-before-mutate rule. Domain names are visited in their own
	ascending order purely for deterministic error reporting; each domain's IDs depend only on
	that domain's own key set.
	"""
	var domain_names: Array = domains.keys()
	domain_names.sort()
	var result_domains: Dictionary = {}
	for domain_name: String in domain_names:
		var raw_keys: Variant = domains[domain_name]
		if not (raw_keys is Array):
			return CompileReport.new(false, {}, "domain '%s' keys must be an Array" % domain_name)
		var coerced: Dictionary = _coerce_keys(domain_name, raw_keys)
		if not bool(coerced["ok"]):
			return CompileReport.new(false, {}, String(coerced["error"]))
		var keys: Array[StringName] = coerced["keys"]
		var result: DomainResult = compile_domain(domain_name, keys)
		if not result.ok:
			return CompileReport.new(false, {}, "domain '%s' failed: %s" % [domain_name, result.error])
		result_domains[domain_name] = result.ids
	return CompileReport.new(true, result_domains, "")


static func _coerce_keys(domain_name: String, raw_keys: Array) -> Dictionary:
	"""Convert an untyped Array of per-domain keys into a strict Array[StringName].

	Assigning a plain untyped Array straight into an `Array[StringName]` variable throws a
	SCRIPT ERROR in Godot even when every element is already a StringName, so each element is
	appended individually instead. A String element converts to StringName; any other element
	type refuses. Returns `{"ok": bool, "keys": Array[StringName], "error": String}`.
	"""
	var keys: Array[StringName] = []
	for index: int in raw_keys.size():
		var element: Variant = raw_keys[index]
		if element is StringName:
			keys.append(element)
		elif element is String:
			keys.append(StringName(element))
		else:
			var message: String = "domain '%s' key at index %d is not a String or StringName (got %s)"
			return {"ok": false, "keys": [] as Array[StringName], "error": message % [domain_name, index, type_string(typeof(element))]}
	return {"ok": true, "keys": keys, "error": ""}


static func _validate_domain(domain_name: String, keys: Array[StringName]) -> DomainResult:
	"""Reject a protected enum name, a duplicate key, or an oversized ItemDefinition catalog."""
	if PROTECTED_ENUM_DOMAINS.has(domain_name):
		return DomainResult.new(false, {}, "'%s' is a fixed enum and cannot be recompiled" % domain_name)
	var seen: Dictionary = {}
	for key: StringName in keys:
		if seen.has(key):
			return DomainResult.new(false, {}, "duplicate key '%s' in domain '%s'" % [key, domain_name])
		seen[key] = true
	if domain_name == ITEM_DEFINITION_DOMAIN and keys.size() > ITEM_DEFINITION_MAX_KEYS:
		var message: String = "ItemDefinition catalog exceeds %d keys (%d given)"
		return DomainResult.new(false, {}, message % [ITEM_DEFINITION_MAX_KEYS, keys.size()])
	return DomainResult.new(true, {}, "")


static func _assign_ascending_ids(keys: Array[StringName]) -> Dictionary:
	"""Map each key to its index in ascending ASCII order, independent of input order.

	StringName's own default comparator does not sort by string content (it may order by an
	internal interning detail instead), so keys are compared as String explicitly.
	"""
	var string_keys: Array[String] = []
	for key: StringName in keys:
		string_keys.append(String(key))
	string_keys.sort()
	var ids: Dictionary = {}
	for index: int in string_keys.size():
		ids[StringName(string_keys[index])] = index
	return ids
