extends RefCounted
## Loads the authoritative ItemDefinition catalog and registers it into an inventory.gd instance.
##
## Task 2.6 (docs/tasks/02_settlement_foundation.md). The single source of truth is
## docs/gameplay_balance.md §3.1; nobody hand-copies that table. `tools/extract_item_definitions.py`
## mechanically extracts it into `res://data/item_definitions.json`, and this module loads that
## JSON, validates it, and wires it into the runtime catalog:
##
##   * IDs are compiled through catalog.gd's `compile_domain("ItemDefinition", keys)`, so they
##     are ascending-ASCII and insertion-order independent (BAL-CAT-001, ARCH-STATE-004's
##     256-key ItemDefinition cap is enforced there).
##   * `category` and `effect` are their own domains, compiled the same deterministic way
##     (BAL-CAT-002: "Category, effect, ... domains use the keys printed in these tables and
##     numeric IDs generated by BAL-CAT-001"), rather than hand-assigned integers.
##   * Each item's `mass_g`/category are registered into an `inventory.gd` instance via its
##     existing `register_item(item_id, mass_g, category)`.
##   * The remaining GDD §4.3 fields (`nutrition_per_u`, `shelf_hours`, `raw_edible`, `seed`,
##     `effect`, `effect_value`) are exposed as typed lookups by compiled id, held in packed
##     columns (ARCH-MEM-001) rather than one Dictionary/object per item.
##
## ALL-OR-NOTHING (GDD §4.2 closing paragraph: "A registry validation failure aborts loading
## before mutating the current world"). A single invalid record -- a missing field, a
## non-integer numeric column, a retired key -- refuses the *entire* load: nothing is compiled,
## nothing is written to this instance's own columns, and nothing is registered into the target
## inventory. `inventory.gd`'s `register_item()` has no batch/transactional form of its own, so
## this module replicates its guard conditions in `_precheck_registration()` for every item
## *before* calling `register_item()` on any of them -- only when every item is independently
## known to succeed does registration actually begin, which is what makes the guarantee hold
## even though registration itself happens one call at a time.
##
## REQ-ADM-003 (docs/setting_rules_amendment.md, SET-AMEND-001 §3): a reference to one of the
## nine retired item keys is rejected outright, never substituted and never allowed to spawn a
## free resource. This module refuses the whole load rather than silently dropping the row.
##
## Resolved ambiguity: GDD §4.3 lists `category` and `effect` as enum-typed fields but neither
## the GDD nor the architecture document enumerates their members the way it does for Speed,
## JobKind, ZoneType, etc. BAL-CAT-002 settles this: both are ordinary compiled catalog domains,
## not fixed enums, so they go through the same `catalog.compile_domain()` path as item IDs.

const CatalogScript := preload("res://scripts/core/catalog.gd")
const InventoryScript := preload("res://scripts/core/inventory.gd")

const DEFAULT_JSON_PATH: String = "res://data/item_definitions.json"
const CATEGORY_DOMAIN: String = "ItemCategory"
const EFFECT_DOMAIN: String = "ItemEffect"

const REQUIRED_FIELDS: Array[String] = [
	"id", "category", "mass_g", "nutrition_per_u", "shelf_hours",
	"raw_edible", "seed", "effect", "effect_value",
]
const STRING_FIELDS: Array[String] = ["id", "category", "effect"]
const INT_FIELDS: Array[String] = ["mass_g", "nutrition_per_u", "shelf_hours", "effect_value"]
const BOOL01_FIELDS: Array[String] = ["raw_edible", "seed"]

## SET-AMEND-001 §3: retired item keys. REQ-ADM-003 requires these be rejected before world
## mutation, never substituted and never allowed to spawn free resources.
const RETIRED_KEYS: Dictionary = {
	&"bow": true, &"carcass_boar": true, &"carcass_deer": true, &"carcass_grouse": true,
	&"hide": true, &"hunting_tool": true, &"meal_game_roast": true, &"raw_game": true,
	&"smoked_game": true,
}


class LoadResult:
	"""Outcome of one load_from_file() attempt: success flag, refusal reason, item count."""
	var ok: bool
	var error: String
	var item_count: int

	func _init(p_ok: bool, p_error: String, p_item_count: int) -> void:
		"""Store the outcome fields for this load attempt."""
		ok = p_ok
		error = p_error
		item_count = p_item_count


class _ValidatedItem:
	"""One fully type-checked, not-yet-compiled ItemDefinition row."""
	var id: StringName
	var category: String
	var mass_g: int
	var nutrition_per_u: int
	var shelf_hours: int
	var raw_edible: int
	var seed: int
	var effect: String
	var effect_value: int


class _ParseResult:
	"""Outcome of reading and JSON-decoding the catalog file."""
	var ok: bool
	var error: String
	var raw_items: Array

	func _init(p_ok: bool, p_error: String, p_raw_items: Array) -> void:
		"""Store the outcome fields for this parse attempt."""
		ok = p_ok
		error = p_error
		raw_items = p_raw_items


class _ValidationResult:
	"""Outcome of type-checking every raw record into a list of _ValidatedItem."""
	var ok: bool
	var error: String
	var items: Array[_ValidatedItem]

	func _init(p_ok: bool, p_error: String, p_items: Array[_ValidatedItem]) -> void:
		"""Store the outcome fields for this validation pass."""
		ok = p_ok
		error = p_error
		items = p_items


class _RecordResult:
	"""Outcome of validating a single raw JSON record."""
	var ok: bool
	var error: String
	var item: _ValidatedItem

	func _init(p_ok: bool, p_error: String, p_item: _ValidatedItem) -> void:
		"""Store the outcome fields for this single-record validation."""
		ok = p_ok
		error = p_error
		item = p_item


class _CompileResult:
	"""Outcome of compiling the ItemDefinition, ItemCategory, and ItemEffect domains together."""
	var ok: bool
	var error: String
	var item_ids: Dictionary
	var category_ids: Dictionary
	var effect_ids: Dictionary

	func _init(p_ok: bool, p_error: String, p_item_ids: Dictionary, p_category_ids: Dictionary, p_effect_ids: Dictionary) -> void:
		"""Store the outcome fields for this domain-compilation attempt."""
		ok = p_ok
		error = p_error
		item_ids = p_item_ids
		category_ids = p_category_ids
		effect_ids = p_effect_ids


# Compiled state (ARCH-MEM-001 packed columns), populated only by a fully successful load.
var _item_ids: Dictionary = {}
var _category_ids: Dictionary = {}
var _effect_ids: Dictionary = {}
var _item_count: int = 0
var _nutrition_per_u: PackedInt32Array = PackedInt32Array()
var _shelf_hours: PackedInt32Array = PackedInt32Array()
var _raw_edible: PackedByteArray = PackedByteArray()
var _seed: PackedByteArray = PackedByteArray()
var _effect_id: PackedInt32Array = PackedInt32Array()
var _effect_value: PackedInt32Array = PackedInt32Array()
var _loaded: bool = false


func load_default(inventory: InventoryScript) -> LoadResult:
	"""Load the catalog from its standard project path (`res://data/item_definitions.json`)."""
	return load_from_file(DEFAULT_JSON_PATH, inventory)


func load_from_file(path: String, inventory: InventoryScript) -> LoadResult:
	"""Load, validate, compile, and register the ItemDefinition catalog from `path`.

	All-or-nothing (GDD §4.2): either the whole catalog is registered into `inventory` and this
	instance becomes loaded, or nothing changes anywhere and a refusal reason is returned.
	"""
	var parse_result: _ParseResult = _parse_json_file(path)
	if not parse_result.ok:
		return LoadResult.new(false, parse_result.error, 0)
	var validation: _ValidationResult = _validate_records(parse_result.raw_items)
	if not validation.ok:
		return LoadResult.new(false, validation.error, 0)
	var id_error: String = _check_ids(validation.items)
	if id_error != "":
		return LoadResult.new(false, id_error, 0)
	var compiled: _CompileResult = _compile_domains(validation.items)
	if not compiled.ok:
		return LoadResult.new(false, compiled.error, 0)
	var precheck_error: String = _precheck_registration(validation.items, compiled.item_ids, compiled.category_ids, inventory)
	if precheck_error != "":
		return LoadResult.new(false, precheck_error, 0)
	_commit(validation.items, compiled.item_ids, compiled.category_ids, compiled.effect_ids, inventory)
	return LoadResult.new(true, "", validation.items.size())


func _parse_json_file(path: String) -> _ParseResult:
	"""Read `path` and decode it, expecting a top-level JSON object with an "items" array."""
	if not FileAccess.file_exists(path):
		return _ParseResult.new(false, "item definitions file not found: %s" % path, [])
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		return _ParseResult.new(false, "could not open item definitions file: %s" % path, [])
	var text: String = file.get_as_text()
	file.close()
	var parsed: Variant = JSON.parse_string(text)
	if typeof(parsed) != TYPE_DICTIONARY:
		return _ParseResult.new(false, "item definitions file is not a JSON object: %s" % path, [])
	var dict: Dictionary = parsed
	if not dict.has("items") or typeof(dict["items"]) != TYPE_ARRAY:
		return _ParseResult.new(false, "item definitions file has no \"items\" array: %s" % path, [])
	return _ParseResult.new(true, "", dict["items"])


func _validate_records(raw_items: Array) -> _ValidationResult:
	"""Validate every raw JSON entry; the whole batch fails on the first invalid record."""
	var items: Array[_ValidatedItem] = []
	for index: int in raw_items.size():
		var result: _RecordResult = _validate_record(raw_items[index], index)
		if not result.ok:
			return _ValidationResult.new(false, result.error, [])
		items.append(result.item)
	return _ValidationResult.new(true, "", items)


func _validate_record(raw: Variant, index: int) -> _RecordResult:
	"""Type-check one raw JSON item entry into a fully validated, still-uncompiled record."""
	if typeof(raw) != TYPE_DICTIONARY:
		return _RecordResult.new(false, "record %d is not a JSON object" % index, null)
	var dict: Dictionary = raw
	var missing: String = _missing_field(dict, index)
	if missing != "":
		return _RecordResult.new(false, missing, null)
	var values: Dictionary = {}
	var field_error: String = _validate_all_fields(dict, index, values)
	if field_error != "":
		return _RecordResult.new(false, field_error, null)
	return _RecordResult.new(true, "", _build_item(values))


func _missing_field(dict: Dictionary, index: int) -> String:
	"""Return an error naming the first required field absent from `dict`, or "" if none."""
	for field: String in REQUIRED_FIELDS:
		if not dict.has(field):
			return "record %d missing field '%s'" % [index, field]
	return ""


func _validate_all_fields(dict: Dictionary, index: int, values: Dictionary) -> String:
	"""Validate every column of one record into `values` (mutated in place). "" on success."""
	for field: String in STRING_FIELDS:
		var result: Dictionary = _validate_string_field(dict, field, index)
		if not result["ok"]:
			return result["error"]
		values[field] = result["value"]
	for field: String in INT_FIELDS:
		var result_i: Dictionary = _validate_int_field(dict, field, index)
		if not result_i["ok"]:
			return result_i["error"]
		values[field] = result_i["value"]
	for field: String in BOOL01_FIELDS:
		var result_b: Dictionary = _validate_bool01_field(dict, field, index)
		if not result_b["ok"]:
			return result_b["error"]
		values[field] = result_b["value"]
	return ""


func _validate_string_field(dict: Dictionary, field: String, index: int) -> Dictionary:
	"""Validate `dict[field]` is a non-empty JSON string."""
	var raw_value: Variant = dict[field]
	if typeof(raw_value) != TYPE_STRING or String(raw_value).is_empty():
		var message: String = "record %d field '%s' is not a non-empty string" % [index, field]
		return {"ok": false, "error": message, "value": ""}
	return {"ok": true, "error": "", "value": String(raw_value)}


func _validate_int_field(dict: Dictionary, field: String, index: int) -> Dictionary:
	"""Validate `dict[field]` is a JSON number with no fractional part; returns it as int.

	Godot's JSON decoder returns every bare number as float (there is no int/float distinction
	in JSON text itself), so integrality is checked explicitly rather than trusted from typeof().
	"""
	var raw_value: Variant = dict[field]
	if typeof(raw_value) != TYPE_FLOAT and typeof(raw_value) != TYPE_INT:
		return {"ok": false, "error": "record %d field '%s' is not numeric" % [index, field], "value": 0}
	var as_float: float = float(raw_value)
	if as_float != floor(as_float):
		var message: String = "record %d field '%s' is not an integer: %s" % [index, field, str(as_float)]
		return {"ok": false, "error": message, "value": 0}
	return {"ok": true, "error": "", "value": int(as_float)}


func _validate_bool01_field(dict: Dictionary, field: String, index: int) -> Dictionary:
	"""Validate `dict[field]` is the integer 0 or 1."""
	var int_result: Dictionary = _validate_int_field(dict, field, index)
	if not int_result["ok"]:
		return int_result
	var value: int = int_result["value"]
	if value != 0 and value != 1:
		var message: String = "record %d field '%s' must be 0 or 1, got %d" % [index, field, value]
		return {"ok": false, "error": message, "value": 0}
	return int_result


func _build_item(values: Dictionary) -> _ValidatedItem:
	"""Assemble a _ValidatedItem from a fully validated field dictionary."""
	var item: _ValidatedItem = _ValidatedItem.new()
	item.id = StringName(values["id"])
	item.category = values["category"]
	item.mass_g = values["mass_g"]
	item.nutrition_per_u = values["nutrition_per_u"]
	item.shelf_hours = values["shelf_hours"]
	item.raw_edible = values["raw_edible"]
	item.seed = values["seed"]
	item.effect = values["effect"]
	item.effect_value = values["effect_value"]
	return item


func _check_ids(items: Array[_ValidatedItem]) -> String:
	"""Return an error naming the first retired or duplicated id, or "" if all are clean."""
	var seen: Dictionary = {}
	for item: _ValidatedItem in items:
		if RETIRED_KEYS.has(item.id):
			var message: String = "item '%s' is a retired key (SET-AMEND-001 Sec.3); " \
				+ "rejected per REQ-ADM-003, never substituted"
			return message % item.id
		if seen.has(item.id):
			return "duplicate item id '%s'" % item.id
		seen[item.id] = true
	return ""


func _compile_domains(items: Array[_ValidatedItem]) -> _CompileResult:
	"""Compile the ItemDefinition, ItemCategory, and ItemEffect domains via catalog.gd."""
	var item_keys: Array[StringName] = []
	var category_keys: Array[StringName] = []
	var effect_keys: Array[StringName] = []
	var seen_categories: Dictionary = {}
	var seen_effects: Dictionary = {}
	for item: _ValidatedItem in items:
		item_keys.append(item.id)
		_add_unique(category_keys, seen_categories, StringName(item.category))
		_add_unique(effect_keys, seen_effects, StringName(item.effect))
	return _compile_three_domains(item_keys, category_keys, effect_keys)


func _add_unique(keys: Array[StringName], seen: Dictionary, key: StringName) -> void:
	"""Append `key` to `keys` the first time it is seen, tracked via `seen`."""
	if seen.has(key):
		return
	seen[key] = true
	keys.append(key)


func _compile_three_domains(item_keys: Array[StringName], category_keys: Array[StringName], effect_keys: Array[StringName]) -> _CompileResult:
	"""Run catalog.compile_domain() for all three domains, aborting on the first failure."""
	var item_result: CatalogScript.DomainResult = CatalogScript.compile_domain(CatalogScript.ITEM_DEFINITION_DOMAIN, item_keys)
	if not item_result.ok:
		return _CompileResult.new(false, "ItemDefinition domain: %s" % item_result.error, {}, {}, {})
	var category_result: CatalogScript.DomainResult = CatalogScript.compile_domain(CATEGORY_DOMAIN, category_keys)
	if not category_result.ok:
		return _CompileResult.new(false, "%s domain: %s" % [CATEGORY_DOMAIN, category_result.error], {}, {}, {})
	var effect_result: CatalogScript.DomainResult = CatalogScript.compile_domain(EFFECT_DOMAIN, effect_keys)
	if not effect_result.ok:
		return _CompileResult.new(false, "%s domain: %s" % [EFFECT_DOMAIN, effect_result.error], {}, {}, {})
	return _CompileResult.new(true, "", item_result.ids, category_result.ids, effect_result.ids)


func _precheck_registration(items: Array[_ValidatedItem], item_ids: Dictionary, category_ids: Dictionary, inventory: InventoryScript) -> String:
	"""Verify every item can be registered before any registration is attempted.

	inventory.register_item() has no batch form, so this replicates its own guard conditions
	up front: only when every item independently passes does load_from_file() proceed to call
	register_item(), which is what guarantees the all-or-nothing contract GDD §4.2 requires.
	"""
	if inventory.is_transaction_open():
		return "inventory has an open transaction; catalog load refused"
	for item: _ValidatedItem in items:
		var error: String = _precheck_one(item, item_ids, category_ids, inventory)
		if error != "":
			return error
	return ""


func _precheck_one(item: _ValidatedItem, item_ids: Dictionary, category_ids: Dictionary, inventory: InventoryScript) -> String:
	"""Verify one item's compiled id, category id, and mass are registerable right now."""
	var compiled_item_id: int = item_ids[item.id]
	if compiled_item_id < 0 or compiled_item_id >= InventoryScript.ITEM_CAPACITY:
		return "item '%s' compiled id %d is out of inventory range" % [item.id, compiled_item_id]
	if inventory.is_item_registered(compiled_item_id):
		return "item '%s' (compiled id %d) is already registered in this inventory" % [item.id, compiled_item_id]
	var category_id: int = category_ids[item.category]
	if category_id < 0 or category_id >= InventoryScript.CATEGORY_COUNT:
		return "item '%s' category id %d is out of inventory range" % [item.id, category_id]
	if item.mass_g <= 0:
		return "item '%s' mass_g must be positive" % item.id
	return ""


func _commit(items: Array[_ValidatedItem], item_ids: Dictionary, category_ids: Dictionary, effect_ids: Dictionary, inventory: InventoryScript) -> void:
	"""Register every item into `inventory` and populate this instance's packed columns.

	Only called after every precondition has been independently verified in
	_precheck_registration(), so every register_item() call here is guaranteed to succeed.
	"""
	var count: int = items.size()
	_nutrition_per_u.resize(count)
	_shelf_hours.resize(count)
	_raw_edible.resize(count)
	_seed.resize(count)
	_effect_id.resize(count)
	_effect_value.resize(count)
	for item: _ValidatedItem in items:
		_commit_one(item, item_ids, category_ids, effect_ids, inventory)
	_item_ids = item_ids
	_category_ids = category_ids
	_effect_ids = effect_ids
	_item_count = count
	_loaded = true


func _commit_one(item: _ValidatedItem, item_ids: Dictionary, category_ids: Dictionary, effect_ids: Dictionary, inventory: InventoryScript) -> void:
	"""Register one item into `inventory` and fill its packed-column row."""
	var compiled_item_id: int = item_ids[item.id]
	var category_id: int = category_ids[item.category]
	inventory.register_item(compiled_item_id, item.mass_g, category_id)
	_nutrition_per_u[compiled_item_id] = item.nutrition_per_u
	_shelf_hours[compiled_item_id] = item.shelf_hours
	_raw_edible[compiled_item_id] = item.raw_edible
	_seed[compiled_item_id] = item.seed
	_effect_id[compiled_item_id] = effect_ids[StringName(item.effect)]
	_effect_value[compiled_item_id] = item.effect_value


func is_loaded() -> bool:
	"""True once load_from_file()/load_default() has fully succeeded on this instance."""
	return _loaded


func item_count() -> int:
	"""Number of items loaded, or 0 before a successful load."""
	return _item_count


func compiled_id(item_id: StringName) -> int:
	"""Compiled ItemDefinition id for `item_id`, or -1 if unknown or not yet loaded."""
	if not _item_ids.has(item_id):
		return -1
	return _item_ids[item_id]


func category_compiled_id(category_name: StringName) -> int:
	"""Compiled ItemCategory id for `category_name`, or -1 if unknown or not yet loaded."""
	if not _category_ids.has(category_name):
		return -1
	return _category_ids[category_name]


func effect_compiled_id(effect_name: StringName) -> int:
	"""Compiled ItemEffect id for `effect_name`, or -1 if unknown or not yet loaded."""
	if not _effect_ids.has(effect_name):
		return -1
	return _effect_ids[effect_name]


func nutrition_per_u(compiled_item_id: int) -> int:
	"""Nutrition per catalog unit for a compiled item id, or 0 if out of range."""
	if compiled_item_id < 0 or compiled_item_id >= _item_count:
		return 0
	return _nutrition_per_u[compiled_item_id]


func shelf_hours(compiled_item_id: int) -> int:
	"""Shelf life in hours for a compiled item id (0 means unlimited), or 0 if out of range."""
	if compiled_item_id < 0 or compiled_item_id >= _item_count:
		return 0
	return _shelf_hours[compiled_item_id]


func is_raw_edible(compiled_item_id: int) -> bool:
	"""True when a compiled item id is directly edible without a recipe."""
	if compiled_item_id < 0 or compiled_item_id >= _item_count:
		return false
	return _raw_edible[compiled_item_id] == 1


func is_seed(compiled_item_id: int) -> bool:
	"""True when a compiled item id is plantable seed stock."""
	if compiled_item_id < 0 or compiled_item_id >= _item_count:
		return false
	return _seed[compiled_item_id] == 1


func effect_id(compiled_item_id: int) -> int:
	"""Compiled ItemEffect id for a compiled item id, or -1 if out of range."""
	if compiled_item_id < 0 or compiled_item_id >= _item_count:
		return -1
	return _effect_id[compiled_item_id]


func effect_value(compiled_item_id: int) -> int:
	"""Effect magnitude for a compiled item id (BAL-CAT-003), or 0 if out of range."""
	if compiled_item_id < 0 or compiled_item_id >= _item_count:
		return 0
	return _effect_value[compiled_item_id]
