from pathlib import Path
import json,tempfile,shutil,subprocess,re,hashlib,time
r=Path('/Users/brendan/Developer/redwall-rts-loop-2026-09-19');e=r/'docs/validation/evidence/construction-component-validation-2026-09-20';out=e/'allocation-a1';out.mkdir(exist_ok=True);bridge='godot/scripts/core/save_owner_construction.gd';original=(r/bridge).read_text();needle='Construction.Columns.new(false)';assert original.count(needle)>=1;pattern='var image: Construction.Columns = Construction.Columns.new(false)';
if original.count(pattern)!=1:
 candidates=[x for x in original.splitlines() if re.match(r'^\s*var \w+:.* = Construction\.Columns\.new\(false\)$',x)];assert len(candidates)==1;pattern=candidates[0]
assert original.count(pattern)==1;mutated=original.replace(pattern,pattern.replace('new(false)','new()'));results=[]
with tempfile.TemporaryDirectory(prefix='redwall-construction-allocation-') as tmp:
 c=Path(tmp);shutil.copytree(r/'godot',c/'godot');(c/'docs').symlink_to(r/'docs');(c/'assets').symlink_to(r/'assets');project=c/'godot/project.godot';s,n=re.subn(r'(?ms)^\[autoload\]\n.*?(?=^\[|\Z)','',project.read_text());assert n==1;project.write_text(s);shutil.copy2(e/'allocation-probe.gd',c/'godot/test/construction_allocation_probe.gd')
 for label,source in [('baseline-before',original),('actual-default-constructor',mutated),('baseline-after',original)]:
  (c/bridge).write_text(source);t=time.monotonic();p=subprocess.run(['godot','--headless','--path','godot','--script','test/construction_allocation_probe.gd'],cwd=c,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,timeout=60);(out/(label+'.log')).write_text(p.stdout);matches=re.findall(r'^CONSTRUCTION_ALLOCATION (.*)$',p.stdout,re.M);data=json.loads(matches[0]) if len(matches)==1 else {};valid=bool(data and not re.search(r'SCRIPT ERROR:|Parse Error:|ERROR:',p.stdout));expected='FAIL' if label=='actual-default-constructor' else 'PASS';passed=valid and data.get('status')==expected and p.returncode==(1 if expected=='FAIL' else 0);record=dict(case=label,valid=valid,expected_outcome=passed,exit_code=p.returncode,seconds=round(time.monotonic()-t,3),observation=data);results.append(record);print(json.dumps(record),flush=True)
record=dict(scope='Actual bridge default-image allocation discriminator; not total native-memory qualification',bridge_sha256=hashlib.sha256(original.encode()).hexdigest(),probe_sha256=hashlib.sha256((e/'allocation-probe.gd').read_bytes()).hexdigest(),mutated_exact_line=pattern,results=results,source_unchanged=(r/bridge).read_text()==original);(out/'result.json').write_text(json.dumps(record,indent=2)+'\n');shutil.copy2(__file__,out/'executed-harness.py')
