extends SceneTree
const Suite := preload("res://test/test_work.gd")
const Work := preload("res://scripts/core/work.gd")
const Jobs := preload("res://scripts/core/jobs.gd")

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var f: Suite = Suite.new()
	f.before_each()
	f._use_gear()
	var row: int = f._fractional_rate_worker()
	var first: int = f._worked_job(row,1000000)
	var lot: Vector2i = f._claimed_tool(row)
	var tick: Work.TickResult = f._work.tick_solo(first)
	f.assert_true(tick.ok,"real fractional work succeeds")
	f.assert_equal(tick.accepted_mwu,40,"80*510/1000 releases40")
	f.assert_equal(f._work.potential_remainder_of(row).value,800,"work carry800")
	f.assert_equal(f._work.xp_remainder_of(row,Jobs.JOB_KIND_KEEP).value,40,"XP carry40")
	f.assert_equal(f._work.wear_remainder_of(row).value,40,"wear carry40")
	f.assert_true(f._work.set_memory_total(511,-2147483648).ok,"inactive physical-tail minimum memory")
	f.assert_true(f._work.set_memory_total(510,2147483647).ok,"inactive maximum memory")
	var image: PackedByteArray = f._work.state_bytes()
	f.assert_equal(image.size(),39424,"actual Work diagnostic bytes")
	f.assert_equal(image.decode_s32(2048+511*4),-2147483648,"diagnostic memory is second")
	f.assert_equal(image.decode_s32(4096+(row*12+Jobs.JOB_KIND_KEEP)*4),40,"diagnostic XP is third")
	f.assert_true(f._work.release_tool_claim(row).ok,"release claim")
	f.assert_equal(f._work.tool_lot_of(row),Vector2i(-1,0),"released lot null")
	f.assert_equal(f._work.tool_job_of(row),Vector2i(-1,0),"released job null")
	f.assert_equal(f._work.wear_remainder_of(row).value,40,"unbound wear retained")
	f.assert_equal(f._work.potential_remainder_of(row).value,800,"unbound work retained")
	f.assert_equal(f._work.xp_remainder_of(row,Jobs.JOB_KIND_KEEP).value,40,"unbound XP retained")
	f.assert_true(f._work.claim_tool_for_work(row,lot).ok,"reclaim tool")
	var retained: Vector2i = f._work.tool_job_of(row)
	f.assert_true(f._jobs.release_worker(row).ok,"change current job without release")
	var next: int = f._worked_job(row,1000000)
	var before: PackedByteArray = f._work.state_bytes()
	tick = f._work.tick_solo(next)
	f.assert_false(tick.ok,"stale current-job relation refuses productive tick")
	f.assert_equal(tick.error,Work.REFUSE_TOOL_CLAIM_STALE,"exact stale refusal")
	f.assert_equal(f._work.tool_job_of(row),retained,"binding history retained")
	f.assert_equal(f._work.state_bytes(),before,"refusal preserves all Work bytes")
	f.after_each()
	f.before_each()
	f.test_a_broken_tool_stops_the_contributor_rather_than_working_for_free()
	f.assert_true(f._work.tool_is_broken(0),"actual retained broken binding")
	f.assert_true(f._work.tool_lot_of(0) != Vector2i(-1,0),"broken binding is not cleared")
	f.after_each()
	for failure: String in f.failures: printerr(failure)
	print("WORK_PUBLIC_HISTORY_PROBE assertions=%d failures=%d" % [f.assertions,f.failures.size()])
	quit(0 if f.failures.is_empty() else 1)
