extends SceneTree
const Work := preload("res://scripts/core/work.gd")
const Schema := preload("res://scripts/core/save_component_columns_schema.gd")
const Section := preload("res://scripts/core/save_section_component_columns.gd")
const Case := preload("res://test/framework/test_case.gd")
func _initialize() -> void:
	call_deferred("_run")
func _run() -> void:
	var f: Case = Case.new()
	f.assert_equal(Schema.owner_key(16),"work","owner key")
	f.assert_equal(Schema.owner_version(16),2,"actual owner version TWO")
	f.assert_equal(Schema.primary_count(16),512,"primary")
	f.assert_equal(Schema.field_count(16),9,"fields")
	f.assert_equal(Work.RESIDENT_CAPACITY,512,"resident extent")
	f.assert_equal(Work.SKILL_COUNT,12,"skills")
	f.assert_equal(Work.SKILL_RESERVED_INDEX,3,"reserved skill")
	f.assert_equal(Work.WORK_FACTOR_DENOMINATOR,1000,"potential denominator")
	f.assert_equal(Work.MILLI_WU_PER_WU,1000,"XP denominator")
	f.assert_equal(Work.WEAR_MWU_PER_DURABILITY_POINT,10000,"wear denominator")
	f.assert_equal(Work.GearScript.LOT_CAPACITY,16384,"gear lot address extent")
	f.assert_equal(Work.GearScript.JOB_CAPACITY,8192,"gear Job address extent")
	f.assert_equal(Work.InventoryScript.LOT_CAPACITY,16384,"actual Inventory extent")
	f.assert_equal(Work.JobsScript.JOB_CAPACITY,8192,"actual Jobs extent")
	f.assert_equal(Work.NULL_SLOT,-1,"null slot")
	f.assert_equal(Work.EntityDirectory.NULL_GENERATION,0,"null generation")
	var record: Section.FramedOwner = Section.FramedOwner.new(16)
	var bytes: PackedByteArray = PackedByteArray()
	bytes.resize(512)
	bytes.fill(1)
	f.assert_true(record.set_u8(8,bytes),"actual u8 setter")
	f.assert_equal(record.u8_column(8),bytes,"actual u8 accessor")
	f.assert_true(Section.owner_shape_refusal(record).is_ok(),"u8 valid shape")
	record.u8_columns[0].resize(511)
	f.assert_equal(Section.owner_shape_refusal(record).code,&"SAVE_COMPONENT_SHAPE","u8 bad extent rejected")
	for failure: String in f.failures: printerr(failure)
	print("WORK_SOURCE_PIN_PROBE assertions=%d failures=%d" % [f.assertions,f.failures.size()])
	quit(0 if f.failures.is_empty() else 1)
