extends RefCounted
## Generated by publish_claw_stair_motion.py (ADR 1229). Do not edit.

const WIRE_PATH: String = "res://data/underground/mole-worker/qualified-claw-stair-motion-v1/stair-motion.ugstair"
const WIRE_SHA: String = "e7840c7babc9bbe21c8f8c36a3d3a313172bc4a3adff9f13dcd6f4a99c25a58b"
const WIRE_BYTES: int = 9620
const CONTENT_REVISION: int = 10
const PROGRAM_COUNT: int = 5
const KEY_COUNT: int = 457
const DECK_COUNT: int = 7
