extends RefCounted
## Generated by publish_stone_runtime.py (ADR 1206). Do not edit.

const WIRE_SHA: String = "30c3dc1f5e9162f5530f410c437ed6f85d28dc6879f88dec81cb193ea87b0df5"
const HANDLING_SOURCE_SHA: String = "b94d676e999c87dd399a4dc110674620a4fbc66f0ca07e494b8bedadac683b66"
const HAUL_SOURCE_SHA: String = "cc8542712705248f944d7430cbba0b7a365860f0073473c2fc0cb9106cf97a85"
const STONE_SOURCE_SHA: String = "49ff3018d363c7dbad05df0af91368e8fec11e30525c2f8231e6a959f80a7b95"
const ACTOR_SHA: String = "adc617642313ac004c050d4877ef0b9f4024bb9c88e3ea92ce9a924471bd5ab9"
const BASIS_SHA: String = "de8c3b04fde4bec30b0b85bf2bf82e01604e9c17cfcb3fdf4029af0f4d43ebf9"
const BASIS_PRODUCER: String = "e68ec74b02bb227a065d9881ca2c12fe3b1ef122f032e7bb1324213d3031813f"
const CONSUMER_COMMIT: String = "912de685b423c5eedd36ee68bc78f18670276cb7"
const PATHS: PackedStringArray = [
	"res://scripts/core/underground_profiles.gd",
	"res://scripts/core/underground_work_face.gd",
	"res://scripts/core/underground_connector_contacts.gd",
	"res://scripts/core/underground_routes.gd",
	"res://scripts/core/underground_world_routes.gd",
	"res://demo/cast/underground_actor.gd",
	"res://demo/cast/underground_actor_content.gd",
	"res://data/underground/mole-worker/mole_profile_driver.gd",
	"res://data/underground/mole-worker/work-approach-v1/source_program.gd",
	"res://data/underground/mole-worker/work-step-v1/source_program.gd",
]
const DIGESTS: PackedStringArray = [
	"64325eed6772207817a043220fe4db371fe5aa68a89fec60a287099ea589dfaf",
	"2e68481744124bc9aa56667112de2d223796069fd1966090f69fad37d63b9b26",
	"c7345c1b937187eaadc8cbb59bb638468c0385179eb21f6b36724b4a45bc682a",
	"3983826ff5e0c177bc831ea41e4dd96c5ba1764f92e2f2488467a6e1fdffdad8",
	"36e7ddc5dd1a1486d1e0ee4d60bd3cd98f2eb6777f3b62a17081575ddd378974",
	"b0ef7640d2b5626eb95c162d19318d9b3985a51479d19dfdf9a38e0176a06e91",
	"388374964d20879b6b896021ebde7927e472634ea8a32b6834ec7b1b5042157f",
	"db7c2051d5d4d4b642a5c1442be4241de3dd4802780bcace6d91d44e5f643064",
	"bc79fbe61bfd23641d6602070d132df724f9975ac36c1555cef701b14d6ab2c4",
	"7134c58f0a48c8eb1184484f1caf41089696cc90083c5cd7038fafeb3fce7879",
]
