extends SceneTree
const Farming := preload("res://scripts/core/farming.gd")
const Forage := preload("res://scripts/core/forage.gd")
const Policy := preload("res://scripts/core/field_policy.gd")
const Case := preload("res://test/framework/test_case.gd")
func _initialize() -> void:
	call_deferred("_run")
func _run() -> void:
	var f: Case = Case.new()
	var farm: Farming = Farming.new()
	var forage: Forage = Forage.new(farm.directory())
	var policy: Policy = Policy.new(farm,forage)
	var zone_result: Forage.OpResult = forage.create_zone(3,0,0,false,true)
	f.assert_true(zone_result.ok,"real FARM zone")
	var zone: Vector2i = zone_result.ref
	var created: Policy.OpResult = policy.create_policy(zone)
	f.assert_true(created.ok,"real policy")
	var row: int = created.value
	var plot_result: Farming.OpResult = farm.create_plot_at_tile(0,0,1)
	f.assert_true(plot_result.ok,"real live plot")
	var plot: int = plot_result.value
	f.assert_equal(policy.cycle_ordinal_of(row).value,0,"initial ordinal")
	f.assert_false(policy.is_auto_rotation(row),"auto default false")
	f.assert_true(policy.is_seed_reserve(row),"seed reserve default true")
	f.assert_true(policy.open_cycle(zone).ok,"first open")
	f.assert_true(policy.enrol_plot(zone,plot).ok,"first enrollment")
	f.assert_true(policy.withdraw_plot(zone,plot,0).ok,"last participant withdrawn")
	f.assert_equal(policy.close_reason_of(row).value,3,"abandoned closure")
	f.assert_equal(policy.participant_count_of(row).value,0,"abandoned participants")
	f.assert_equal(policy.resolved_count_of(row).value,0,"abandoned resolved")
	f.assert_equal(policy.withdrawn_count_of(row).value,1,"abandoned withdrawal retained")
	f.assert_equal(policy.completed_cycle_count_of(row).value,0,"no fabricated completion")
	f.assert_equal(policy.plot_outcome_of(plot).value,3,"withdrawn ledger outcome retained")
	f.assert_false(policy.is_plot_enrolled(plot),"closed ledger no longer active")
	f.assert_true(policy.open_cycle(zone).ok,"second open")
	f.assert_equal(policy.withdrawn_count_of(row).value,0,"new cycle resets withdrawn")
	f.assert_true(policy.enrol_plot(zone,plot).ok,"closed enrollment can be reused")
	f.assert_true(policy.set_auto_rotation(zone,true).ok,"enable auto")
	f.assert_true(policy.record_plot_resolved(zone,plot,1,0).ok,"complete by explicit work result")
	f.assert_equal(policy.close_reason_of(row).value,1,"completed closure")
	f.assert_equal(policy.completed_cycle_count_of(row).value,1,"one completion")
	f.assert_equal(policy.rotation_cursor_of(row).value,1,"exactly one advance")
	var request: int = policy.request_state_of(row).value
	f.assert_true(request != 0,"standing next crop request")
	f.assert_equal(policy.requested_crop_of(row).value,0,"beans at cursor1")
	f.assert_true(policy.set_auto_rotation(zone,false).ok,"turn auto off after closure")
	f.assert_equal(policy.request_state_of(row).value,request,"existing request survives auto off")
	f.assert_equal(policy.requested_crop_of(row).value,0,"requested crop preserved")
	f.assert_true(policy.set_rotation(zone,-1,-1,-1,0).ok,"edit outstanding request to empty entry")
	f.assert_equal(policy.request_state_of(row).value,4,"unconfigured request state")
	f.assert_equal(policy.requested_crop_of(row).value,-1,"unconfigured requested crop")
	f.assert_equal(policy.rotation_cursor_of(row).value,1,"edit does not advance")
	f.assert_true(policy.open_cycle(zone).ok,"third open consumes outstanding request")
	f.assert_equal(policy.request_state_of(row).value,0,"request consumed")
	f.assert_true(policy.cancel_cycle(zone).ok,"empty open cycle can be cancelled")
	f.assert_equal(policy.close_reason_of(row).value,2,"cancellation reason")
	f.assert_equal(policy.cancelled_cycle_count_of(row).value,1,"one cancellation")
	f.assert_equal(policy.participant_count_of(row).value,0,"empty cancellation")
	f.assert_true(policy.destroy_policy(zone).ok,"retire policy")
	f.assert_false(policy.cycle_ordinal_of(row).ok,"inactive ordinal public reader refuses")
	f.assert_equal(policy.plot_outcome_of(plot).value,1,"old plot outcome remains publicly readable")
	f.assert_true(policy.create_policy(zone).ok,"same-zone policy recreated")
	f.assert_equal(policy.cycle_ordinal_of(row).value,3,"ordinal survives recreation")
	f.assert_equal(policy.completed_cycle_count_of(row).value,0,"completed count reset on recreation")
	f.assert_equal(policy.cancelled_cycle_count_of(row).value,0,"cancelled count reset on recreation")
	f.assert_equal(policy.close_reason_of(row).value,0,"new policy close reason reset")
	f.assert_equal(policy.cycle_state_of(row).value,0,"positive-ordinal idle is legal")
	f.assert_equal(policy.plot_outcome_of(plot).value,1,"recreation does not walk plot history")
	f.assert_false(policy.is_plot_enrolled(plot),"stale old enrollment is not active")
	f.assert_true(policy.open_cycle(zone).ok,"fourth cycle")
	f.assert_equal(policy.cycle_ordinal_of(row).value,4,"monotonic cycle ordinal")
	f.assert_true(policy.enrol_plot(zone,plot).ok,"old plot can join new ordinal")
	f.assert_equal(policy.plot_outcome_of(plot).value,0,"new enrollment resets outcome")
	f.assert_true(policy.record_plot_resolved(zone,plot,1,0).ok,"fourth completes")
	var other_zone_result: Forage.OpResult = forage.create_zone(3,0,0,false,true)
	f.assert_true(other_zone_result.ok,"second zone")
	var other: Policy.OpResult = policy.create_policy(other_zone_result.ref)
	f.assert_true(other.ok,"second policy")
	f.assert_true(policy.open_cycle(other_zone_result.ref).ok,"second field opens")
	f.assert_true(policy.enrol_plot(other_zone_result.ref,plot).ok,"closed first field releases enrollment identity")
	f.assert_equal(policy.plot_field_slot_of(plot).value,other.value,"plot ledger now names second field")
	f.assert_equal(policy.participant_count_of(row).value,1,"first closed participant history retained")
	f.assert_equal(policy.resolved_count_of(row).value,1,"first closed resolution history retained")
	f.assert_true(policy.cancel_cycle(other_zone_result.ref).ok,"second field cancellation with unresolved plot")
	f.assert_equal(policy.plot_outcome_of(plot).value,0,"cancelled unresolved ledger remains legal")
	f.assert_true(forage.destroy_zone(zone).ok,"zone disappears without policy destruction")
	f.assert_true(policy.is_present(row),"stale policy row remains present")
	f.assert_false(policy.zone_is_live(row),"stale zone liveness fails")
	var replacement: Forage.OpResult = forage.create_zone(3,0,0,false,true)
	f.assert_true(replacement.ok,"zone row reused")
	var reclaimed: Policy.OpResult = policy.create_policy(replacement.ref)
	f.assert_true(reclaimed.ok,"stale policy reclaimed for new zone generation")
	f.assert_equal(reclaimed.value,row,"same typed policy row")
	f.assert_equal(policy.cycle_ordinal_of(row).value,4,"ordinal retained through stale-zone reclaim")
	f.assert_equal(policy.completed_cycle_count_of(row).value,0,"new policy counts reset")
	f.assert_true(policy.open_cycle(replacement.ref).ok,"reclaimed policy opens next ordinal")
	f.assert_equal(policy.cycle_ordinal_of(row).value,5,"new ordinal cannot collide with old stamp")
	f.assert_false(Policy.can_open_cycle(2147483647),"explicit public boundary predicate refuses MAX")
	f.assert_true(Policy.can_open_cycle(2147483646),"one final ordinal increment allowed")
	for failure: String in f.failures: printerr(failure)
	print("FIELD_POLICY_PUBLIC_HISTORY_PROBE assertions=%d failures=%d" % [f.assertions,f.failures.size()])
	quit(0 if f.failures.is_empty() else 1)
