extends RefCounted
## Generated by publish_claw_runtime.py (ADR 1217). Do not edit.

const WIRE_SHA: String = "8b79294f390fb8b16899ca83be70d01baa0eaf800f071d9042e2e1250cff2355"
const HANDLING_SOURCE_SHA: String = "b94d676e999c87dd399a4dc110674620a4fbc66f0ca07e494b8bedadac683b66"
const HAUL_SOURCE_SHA: String = "fa8dc668f7ae881d5fcc88a9dd1b6796b7f37466d0cca5e1994647e04a54dc71"
const STONE_SOURCE_SHA: String = "1756932c3839c3dbf2d66a715f65f5dfea7861ddafdf7f5921687b821040e6e6"
const CLAW_SOURCE_SHA: String = "6be24202d75c31011423de4fe8dd62358d66497412f733c087c3b130561caae6"
const ACTOR_SHA: String = "adc617642313ac004c050d4877ef0b9f4024bb9c88e3ea92ce9a924471bd5ab9"
const BASIS_SHA: String = "de8c3b04fde4bec30b0b85bf2bf82e01604e9c17cfcb3fdf4029af0f4d43ebf9"
const BASIS_PRODUCER: String = "e68ec74b02bb227a065d9881ca2c12fe3b1ef122f032e7bb1324213d3031813f"
const CONSUMER_COMMIT: String = "912de685b423c5eedd36ee68bc78f18670276cb7"
const PATHS: PackedStringArray = [
	"res://scripts/core/underground_profiles.gd",
	"res://scripts/core/underground_work_face.gd",
	"res://scripts/core/underground_connector_contacts.gd",
	"res://scripts/core/underground_routes.gd",
	"res://scripts/core/underground_world_routes.gd",
	"res://demo/cast/underground_actor.gd",
	"res://demo/cast/underground_actor_content.gd",
	"res://data/underground/mole-worker/mole_profile_driver.gd",
	"res://data/underground/mole-worker/work-approach-v1/source_program.gd",
	"res://data/underground/mole-worker/work-step-v1/source_program.gd",
]
const DIGESTS: PackedStringArray = [
	"64325eed6772207817a043220fe4db371fe5aa68a89fec60a287099ea589dfaf",
	"2e68481744124bc9aa56667112de2d223796069fd1966090f69fad37d63b9b26",
	"2e78aa88633e02ddceb66499e65460a9fff8e96c56a0edc42fe9ef22335022f2",
	"7cca094843626e3a6b730041ca809d4b798b3bd72ced7da9ba425acb1e35e659",
	"71a1bbc47b49eeedb71ffd6ce2d9e9c10ed5084381f87282353f9b4e8332d53e",
	"b0ef7640d2b5626eb95c162d19318d9b3985a51479d19dfdf9a38e0176a06e91",
	"388374964d20879b6b896021ebde7927e472634ea8a32b6834ec7b1b5042157f",
	"db7c2051d5d4d4b642a5c1442be4241de3dd4802780bcace6d91d44e5f643064",
	"bc79fbe61bfd23641d6602070d132df724f9975ac36c1555cef701b14d6ab2c4",
	"7134c58f0a48c8eb1184484f1caf41089696cc90083c5cd7038fafeb3fce7879",
]
