extends RefCounted
## Generated by publish_qualified_install.py (ADR 1202). Do not edit.

const CATALOG_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-install-v3/structure.ugconn"
const CATALOG_SHA: String = "82dff49dc3da23383b9e22b05ee82b267378dcc801ca42931806946db8392aa3"
const CATALOG_REVISION: int = 1
const GROUPING_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-install-v3/assemblies.ugasmb"
const GROUPING_SHA: String = "9cf6d8bbd7748f3756f766592215eb2ac836afd3fbf4b68e5bb3c1677306b7de"
const GROUPING_REVISION: int = 1
const RECIPE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-install-v3/recipes.ugrecp"
const RECIPE_SHA: String = "d18ac338c76a9b3d03d5aa864d1cb36ffbef815fa98b47d44f8e6219eeac27fc"
const RECIPE_REVISION: int = 1
const FRONTIER_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-install-v3/frontier.ugfront"
const FRONTIER_SHA: String = "609605ea40d14529cbc8eed4f61bf4ed3dd569c2184e35481c22517de67b9382"
const FRONTIER_REVISION: int = 3
const WORKPIECES_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-install-v3/workpieces.ugwipc"
const WORKPIECES_SHA: String = "3999e4c0064c8336a5268171c6f74ed14abd257a04c54f910c7ffdcab2f43421"
const WORKPIECES_REVISION: int = 1
const GROUND_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-install-v3/ground-pace.ugconn"
const GROUND_SHA: String = "1ae7ffc421f2a93deac4ccde12a843652da1fd46c91f58c28c559979015422f0"
const PROFILE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-install-v3/mole-worker.ugprof"
const PROFILE_SHA: String = "dc4969e4dc562e39b941a7fefa4be4b72851490f59492f0b04b3f26954bc5d8e"
const CONTENT_REVISION: int = 5
const ACTOR_SHA: String = "adc617642313ac004c050d4877ef0b9f4024bb9c88e3ea92ce9a924471bd5ab9"
const INSTALL_COUNT: int = 2
const STATION_COUNT: int = 8
const CUT_COUNT: int = 2
const BEARING_COUNT: int = 10
const ENDPOINT_COUNT: int = 12
const EPISODE_COUNT: int = 6
const CATALOG_DIGEST_0: int = 4045317424012386178
const CATALOG_DIGEST_1: int = 2750547490819448379
const CATALOG_DIGEST_2: int = -7835478292657571725
const CATALOG_DIGEST_3: int = -6689470832230267368
const GROUND_DIGEST_0: int = 4443348734230652698
const GROUND_DIGEST_1: int = 7296860620271174890
const GROUND_DIGEST_2: int = -4442766083061079763
const GROUND_DIGEST_3: int = -1143258990086892148
