extends RefCounted
## Generated by publish_qualified_stairs.py (ADR 1229). Do not edit.

const CATALOG_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v7/structure.ugconn"
const CATALOG_SHA: String = "531de0371e339c6f8a6abe8034e3e2fea68c8dd95e1e14b348d40258561ae9eb"
const CATALOG_REVISION: int = 1
const GROUPING_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v7/assemblies.ugasmb"
const GROUPING_SHA: String = "f4b465d56897519d360d43d70eb85e73b3e74fce865c5faf8a0c14bd4a6333c7"
const GROUPING_REVISION: int = 1
const RECIPE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v7/recipes.ugrecp"
const RECIPE_SHA: String = "efb08fa53b13fa3b2902369a2a7ca5257b146330bf9405d98bb3b4fd865009c2"
const RECIPE_REVISION: int = 1
const FRONTIER_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v7/frontier.ugfront"
const FRONTIER_SHA: String = "8dacfa92bd7855f64f69189cbf69f0a0e4ea94453e65f7ffff1a9bb9857e78da"
const FRONTIER_REVISION: int = 6
const WORKPIECES_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v7/workpieces.ugwipc"
const WORKPIECES_SHA: String = "6bf953e405d4322955be13a31b352e9b384a33bc689bc25ecbc92f6f633c9e67"
const WORKPIECES_REVISION: int = 1
const GROUND_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v7/ground-pace.ugconn"
const GROUND_SHA: String = "dfadb2efbbd3ebb234e5f0fe3c128038eafb67572e2be1103470b7b432da67f3"
const PROFILE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v7/mole-worker.ugprof"
const PROFILE_SHA: String = "9791eb59b778cf9fe0b4c66dfd7181c58706abd6ed1a8e6a90a73daafa7f3317"
const CONTENT_REVISION: int = 10
const ACTOR_SHA: String = "b85f91952992fecfc4b0b89affb0b605b3d7c8e15b9c3e8f66ab03969efd6675"
const INSTALL_COUNT: int = 8
const STATION_COUNT: int = 22
const CUT_COUNT: int = 5
const BEARING_COUNT: int = 38
const ENDPOINT_COUNT: int = 44
const EPISODE_COUNT: int = 14
const CATALOG_DIGEST_0: int = 8042359239456333139
const CATALOG_DIGEST_1: int = -80252028701480310
const CATALOG_DIGEST_2: int = -5542771848660546394
const CATALOG_DIGEST_3: int = -1447596847076813752
const GROUND_DIGEST_0: int = -5554112911297565217
const GROUND_DIGEST_1: int = 4071274116327466292
const GROUND_DIGEST_2: int = 1216300852401667050
const GROUND_DIGEST_3: int = -907516888576724940
