#!/usr/bin/env python3
"""Create-only content-4 runtime mole profile publication `qualified-handling-v5/` (ADR 1194).

Content 4 is content 3 plus the stationary assembly-handling row 29 and its second source digest
(rows 0-28 and boxes 0-270 are byte-identical; checked here). This copies the content-4 wire and
ground pace from the published first-entry bundle (ADR 1190), emits an accessor with the same shape
as qualified-step-v4's (same actor/basis pins, renewed consumer digests, new wire), and rebinds the
unchanged source-only motion bank to the new wire. Refuses to overwrite.

    python3 godot/data/underground/mole-worker/publish_handling_runtime.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re
import struct
import sys

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
OLD = HERE / "qualified-step-v4"
BUNDLE = ROOT / "godot/data/underground/first-entry-prefix-v1/qualified-handling-v1"
OUTPUT = HERE / "qualified-handling-v5"
OLD_WIRE_SHA = "830ee531a432f9cef8a24a85f1c017be21253301bc46bf55e0a6b97807a4ec4e"
NEW_WIRE_SHA = "17d9c229fdfe8ad1923f004db136653ab9834994ba946061be38ec7a2c862ff9"
NEW_GROUND_SHA = "877be0982eb6945c4c4f014e9de428b3ab278d1fddc630080e9c6bfe341a1ea8"
OLD_MOTION_SHA = "69fd9011da9b9c1d85e206401ef287943381a24d19322946287234b2dc66850c"
I64_AT = 32 + 12 + 17421 * 4 + 12
BYTE_AT = I64_AT + 67 * 8 + 12


def require(value: bool, code: str) -> None:
    """Every refusal names the exact failed publication fact."""
    if not value:
        raise ValueError("HANDLING_RUNTIME_" + code)


def sha(raw: bytes) -> str:
    """Lower-case hex SHA256."""
    return hashlib.sha256(raw).hexdigest()


def check_superset(old: bytes, new: bytes) -> str:
    """Content 4 must keep every content-3 row and box byte-exact; return the added source digest."""
    require(old[:8] == new[:8] == b"UGPROF01", "WIRE_MAGIC")
    o_rev, o_rows, o_boxes, o_src = struct.unpack_from("<qIII", old, 12)
    n_rev, n_rows, n_boxes, n_src = struct.unpack_from("<qIII", new, 12)
    require((o_rev, o_rows, o_boxes, o_src) == (3, 29, 271, 1), "OLD_HEADER")
    require((n_rev, n_rows, n_boxes, n_src) == (4, 30, 281, 2), "NEW_HEADER")
    require(old[32:64] == new[32:64], "ACTOR_SOURCE")
    old_rows, new_rows = 32 + 32, 32 + 64
    require(old[old_rows:old_rows + 29 * 98] == new[new_rows:new_rows + 29 * 98], "ROWS_0_28")
    old_boxes, new_boxes = old_rows + 29 * 98, new_rows + 30 * 98
    require(old[old_boxes:old_boxes + 271 * 28] == new[new_boxes:new_boxes + 271 * 28], "BOXES_0_270")
    return new[64:96].hex()


def accessor(old_text: str, handling_source: str) -> str:
    """Same constants as v4 with the new wire, the handling source, and current consumer digests."""
    text = old_text.replace(OLD_WIRE_SHA, NEW_WIRE_SHA)
    text = text.replace("## Generated exact source pins; use publish_short_step_profiles.py.",
                        "## Generated by publish_handling_runtime.py (ADR 1194). Do not edit.")
    text = text.replace("const ACTOR_SHA:", f'const HANDLING_SOURCE_SHA: String = "{handling_source}"\nconst ACTOR_SHA:', 1)
    paths = re.findall(r'"(res://[^"]+\.gd)"', text)
    old_digests = re.search(r"const DIGESTS: PackedStringArray = \[\n(.*?)\n\]", text, re.S)
    current = [sha((ROOT / ("godot/" + p.removeprefix("res://"))).read_bytes()) for p in paths]
    block = "\n".join(f'\t"{d}",' for d in current)
    return text[:old_digests.start(1)] + block + text[old_digests.end(1):]


def rebind_motion(motion: bytes, numerical: str) -> bytes:
    """Change only the profile revisions, embedded wire digest and input manifest digest."""
    require(sha(motion) == OLD_MOTION_SHA and len(motion) == 70936, "MOTION_ORIGINAL")
    require(struct.unpack_from("<q", motion, 16) == (3,) and struct.unpack_from("<3q", motion, I64_AT) == (1, 3, 3)
            and motion[BYTE_AT + 160:BYTE_AT + 192].hex() == OLD_WIRE_SHA, "MOTION_LAYOUT")
    out = bytearray(motion)
    struct.pack_into("<q", out, 16, 4)
    struct.pack_into("<2q", out, I64_AT + 8, 4, 4)
    out[BYTE_AT + 160:BYTE_AT + 192] = bytes.fromhex(NEW_WIRE_SHA)
    out[BYTE_AT + 384:BYTE_AT + 416] = bytes.fromhex(numerical)
    ranges = [(16, 24), (I64_AT + 8, I64_AT + 24), (BYTE_AT + 160, BYTE_AT + 192), (BYTE_AT + 384, BYTE_AT + 416)]
    require(all(a == b or any(lo <= i < hi for lo, hi in ranges) for i, (a, b) in enumerate(zip(motion, out))),
            "MOTION_FOREIGN_DELTA")
    return bytes(out)


def main() -> int:
    """Create the publication exactly once."""
    require(not OUTPUT.exists(), "OUTPUT_EXISTS")
    old_wire = (OLD / "mole-worker.ugprof").read_bytes()
    require(sha(old_wire) == OLD_WIRE_SHA, "OLD_WIRE")
    new_wire = (BUNDLE / "mole-worker.ugprof").read_bytes()
    require(sha(new_wire) == NEW_WIRE_SHA, "NEW_WIRE")
    ground = (BUNDLE / "ground-pace.ugconn").read_bytes()
    require(sha(ground) == NEW_GROUND_SHA, "GROUND")
    handling_source = check_superset(old_wire, new_wire)
    pins = {"godot/data/underground/mole-worker/qualified-step-v4/motion.ugmotion": OLD_MOTION_SHA,
            str((BUNDLE / "mole-worker.ugprof").relative_to(ROOT)): NEW_WIRE_SHA,
            str(Path(__file__).relative_to(ROOT)): sha(Path(__file__).read_bytes())}
    numerical = sha(json.dumps(pins, sort_keys=True, separators=(",", ":")).encode())
    motion = rebind_motion((OLD / "motion.ugmotion").read_bytes(), numerical)
    constants = accessor((OLD / "catalog_source.gd").read_text(), handling_source)
    OUTPUT.mkdir()
    (OUTPUT / "mole-worker.ugprof").write_bytes(new_wire)
    (OUTPUT / "ground-pace.ugconn").write_bytes(ground)
    (OUTPUT / "motion.ugmotion").write_bytes(motion)
    (OUTPUT / "catalog_source.gd").write_text(constants)
    consumers = {"godot/" + p.removeprefix("res://"): d for p, d in
                 zip(re.findall(r'"(res://[^"]+\.gd)"', constants), re.findall(r'"([0-9a-f]{64})",', constants))}
    manifest = {"schema": 1, "decision": "1194", "content_revision": 4, "profile_count": 30, "box_count": 281,
                "source_count": 2, "wire_sha256": NEW_WIRE_SHA, "wire_bytes": len(new_wire),
                "paired_bank_bytes": 21808, "handling_source_sha256": handling_source,
                "superset_of": {"wire_sha256": OLD_WIRE_SHA, "rows": "0-28", "boxes": "0-270"},
                "ground_sha256": NEW_GROUND_SHA, "motion_sha256": sha(motion), "motion_inputs": pins,
                "motion_numerical_input_sha256": numerical, "consumers": consumers,
                "presentation": "Row 29 has no actor-source presentation; rows 0-28 unchanged."}
    (OUTPUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print("published", OUTPUT.relative_to(ROOT), "motion", sha(motion)[:12])
    return 0


if __name__ == "__main__":
    sys.exit(main())
