extends SceneTree
const Residents := preload("res://scripts/core/residents.gd")
const Case := preload("res://test/framework/test_case.gd")
const MAX_I64: int = 9223372036854775807
const MIN_I64: int = -9223372036854775807 - 1
func _initialize() -> void:
	call_deferred("_run")
func _run() -> void:
	var f: Case = Case.new()
	var store: Residents = Residents.new()
	f.assert_equal(store.catalog_error(),"","real catalogs compile")
	var spawned: Residents.OpResult = store.spawn_with_stage(&"otter",Residents.LIFE_STAGE_ELDER)
	f.assert_true(spawned.ok,"public elder spawn")
	var row: int = spawned.value
	var columns: Residents.Columns = Residents.Columns.new()
	f.assert_true(store.copy_columns_into(columns),"public capture")
	f.assert_true(store.restore_columns(columns),"existing valid self restore")
	for tick: int in [-1,MIN_I64]:
		f.assert_true(store.set_arrival_tick(row,tick).ok,"original setter accepts negative tick")
		f.assert_true(store.copy_columns_into(columns),"negative history capture")
		f.assert_equal(columns.arrival_tick[row],tick,"exact signed arrival retained")
		var before: PackedByteArray = store.state_bytes()
		f.assert_false(store.restore_columns(columns),"original live restore rejects producer history")
		f.assert_equal(store.last_column_refusal(),&"COLUMN_ARRIVAL_TICK","exact producer mismatch")
		f.assert_equal(store.state_bytes(),before,"refusal keeps original state")
	f.assert_true(store.set_arrival_tick(row,MAX_I64).ok,"full positive arrival endpoint")
	f.assert_true(store.set_skill_xp(row,Residents.SKILL_KEEP,MAX_I64).ok,"full skill XP endpoint")
	var large_ref: Vector2i = Vector2i(2147483647,2147483647)
	f.assert_true(store.set_home(row,large_ref).ok,"shape-only home accepts large slot")
	f.assert_true(store.set_bed(row,large_ref).ok,"shape-only bed accepts large slot")
	f.assert_true(store.set_satchel(row,large_ref).ok,"shape-only satchel accepts large slot")
	f.assert_true(store.set_equipped_tool(row,2147483647,2147483647).ok,"uncapped local item/durability domain")
	f.assert_true(store.copy_columns_into(columns),"public endpoint capture")
	f.assert_true(store.restore_columns(columns),"existing restore agrees on lawful endpoints")
	f.assert_equal(columns.skill_level[row*12+Residents.SKILL_KEEP],10,"MAX XP uses bounded level curve")
	f.assert_true(store.set_arrival_tick(row,MIN_I64).ok,"original negative history before release")
	f.assert_true(store.despawn(store.ref_of(row)).ok,"public departure")
	f.assert_true(store.copy_columns_into(columns),"free-row capture")
	f.assert_equal(columns.present[row],0,"row released")
	f.assert_equal(columns.arrival_tick[row],MIN_I64,"inactive negative arrival retained")
	f.assert_equal(columns.home_slot[row],2147483647,"inactive home retained")
	f.assert_equal(columns.bed_slot[row],2147483647,"inactive bed retained")
	f.assert_equal(columns.skill_xp[row*12+Residents.SKILL_KEEP],MAX_I64,"inactive XP retained")
	f.assert_equal(columns.life_stage[row],Residents.LIFE_STAGE_ADULT,"free stage reset")
	f.assert_equal(columns.equip_satchel_slot[row],-1,"free satchel cleared")
	f.assert_equal(columns.equip_tool_item_id[row],Residents.NO_TOOL_ITEM,"free tool cleared")
	var retained: Residents.Columns = Residents.Columns.new()
	f.assert_true(store.restore_columns(columns),"existing restore accepts retained inactive negative tick")
	f.assert_true(store.copy_columns_into(retained),"capture restored inactive history")
	f.assert_true(columns.equals(retained),"all nineteen fields preserve exact inactive history")
	for failure: String in f.failures: printerr(failure)
	print("RESIDENTS_PUBLIC_HISTORY_PROBE assertions=%d failures=%d" % [f.assertions,f.failures.size()])
	quit(0 if f.failures.is_empty() else 1)
