extends SceneTree
const Transforms := preload("res://scripts/core/transforms.gd")
const Directory := preload("res://scripts/core/entity_directory.gd")
func _initialize() -> void:
	"""Observe extrema, retained predecessor data and presentation nonmutation via public APIs."""
	var directory: Directory = Directory.new()
	var owner: Transforms = Transforms.new(directory)
	var first: Vector2i = directory.create(Directory.KIND_RESIDENT)
	assert(directory.is_valid(first))
	var first_id: int = directory.get_persistent_id(first)
	var row: int = directory.get_typed_row(first)
	assert(owner.place(first,-2147483648,2147483647,-7,-2147483648))
	assert(owner.advance(first,2147483647,-2147483648,9))
	assert(owner.set_yaw(first,2147483647))
	var pose: Transforms.Pose = Transforms.Pose.new()
	assert(owner.read_into(first,pose))
	assert(pose.x == 2147483647 and pose.prev_x == -2147483648)
	assert(pose.y == -2147483648 and pose.prev_y == 2147483647)
	assert(pose.yaw == 2147483647 and pose.prev_yaw == -2147483648)
	var before: PackedByteArray = owner.state_bytes()
	var presentation: Transforms.PresentationPose = Transforms.PresentationPose.new()
	assert(owner.presentation_interpolate_into(first,1,2,presentation))
	assert(owner.state_bytes() == before)
	assert(directory.destroy(first))
	assert(owner.state_bytes() == before and owner.bound_count() == 1)
	var second: Vector2i = directory.create(Directory.KIND_RESIDENT)
	assert(directory.get_typed_row(second) == row)
	assert(directory.get_persistent_id(second) != first_id)
	assert(not owner.is_bound(second) and not owner.read_into(second,pose))
	assert(owner.state_bytes() == before and owner.bound_count() == 1)
	assert(owner.place(second,0,0,0,0))
	assert(owner.bound_count() == 1 and owner.is_bound(second))
	assert(owner.unbind(second))
	var empty: PackedByteArray = owner.state_bytes()
	assert(owner.bound_count() == 0 and empty.size() == 3151872 and empty.count(0) == 3151872)
	print("TRANSFORM_HISTORY_PROBE "+JSON.stringify({"signed_pose_extrema":true,"signed_yaw_extrema":true,"retained_stale_stamp_and_pose":true,"successor_unplaced":true,"replacement_keeps_count":true,"presentation_preserves_history":true,"unbind_zeroes_all_columns":true}))
	quit(0)
