extends RefCounted
## Generated by publish_qualified_stairs.py (ADR 1229). Do not edit.

const CATALOG_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v9/structure.ugconn"
const CATALOG_SHA: String = "7f6758911458de66f751d6d5d4bbb525f980227cc4d79c9d03a2f538e60fd673"
const CATALOG_REVISION: int = 1
const GROUPING_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v9/assemblies.ugasmb"
const GROUPING_SHA: String = "30dcccd1e312cb27e575e27e95f5467408a0964a34362e92e3115ce89f870b4a"
const GROUPING_REVISION: int = 1
const RECIPE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v9/recipes.ugrecp"
const RECIPE_SHA: String = "44776bf27c4456803417d16504b41cfa83bc580e2da4a09e3849d5dbe7c9467a"
const RECIPE_REVISION: int = 1
const FRONTIER_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v9/frontier.ugfront"
const FRONTIER_SHA: String = "182b304c2a0d9ff7b337dac2566f98a2587171d97c18c9bb89c9b3afe1d5e49f"
const FRONTIER_REVISION: int = 8
const WORKPIECES_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v9/workpieces.ugwipc"
const WORKPIECES_SHA: String = "41afd0ecc52d197d44f074824f1f546beecd7aad87a5073f4710ff78314234d4"
const WORKPIECES_REVISION: int = 1
const GROUND_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v9/ground-pace.ugconn"
const GROUND_SHA: String = "dfadb2efbbd3ebb234e5f0fe3c128038eafb67572e2be1103470b7b432da67f3"
const PROFILE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stairs-v9/mole-worker.ugprof"
const PROFILE_SHA: String = "9791eb59b778cf9fe0b4c66dfd7181c58706abd6ed1a8e6a90a73daafa7f3317"
const CONTENT_REVISION: int = 10
const ACTOR_SHA: String = "b85f91952992fecfc4b0b89affb0b605b3d7c8e15b9c3e8f66ab03969efd6675"
const INSTALL_COUNT: int = 8
const STATION_COUNT: int = 22
const CUT_COUNT: int = 6
const BEARING_COUNT: int = 38
const ENDPOINT_COUNT: int = 44
const EPISODE_COUNT: int = 14
const CATALOG_DIGEST_0: int = 7412458882059495295
const CATALOG_DIGEST_1: int = 2717284472983015927
const CATALOG_DIGEST_2: int = -7089554474491805447
const CATALOG_DIGEST_3: int = 8346876440850309635
const GROUND_DIGEST_0: int = -5554112911297565217
const GROUND_DIGEST_1: int = 4071274116327466292
const GROUND_DIGEST_2: int = 1216300852401667050
const GROUND_DIGEST_3: int = -907516888576724940
