extends "res://test/framework/test_case.gd"
## INIT-C live apply through the real settlement (DEMO-CONTAIN-R01 D3, decision 0533).
##
## A separate suite from `test_settlement_system.gd`, which D4 owns. Every test drives a
## `SettlementSystem` built outside the scene tree, generated by its own production transaction,
## and checks the colony, the World row and the ground-pile composer it binds, the store binding
## EconomySystem is opened on, the M4 placement refusal, the save owners that carry the colony,
## and seed determinism. Expected tiles are restated from GDD §5.9, not read from the plan.

const SettlementSystemScript := preload("res://scripts/systems/settlement_system.gd")
const EconomySystemScript := preload("res://scripts/systems/economy_system.gd")
const EntityDirectory := preload("res://scripts/core/entity_directory.gd")
const Buildings := preload("res://scripts/core/buildings.gd")
const BuildingsOwner := preload("res://scripts/core/save_owner_buildings.gd")
const Catalog := preload("res://scripts/core/catalog.gd")
const GroundPiles := preload("res://scripts/core/ground_piles.gd")
const Inventory := preload("res://scripts/core/inventory.gd")
const ItemDefinitions := preload("res://scripts/core/item_definitions.gd")
const StarterColony := preload("res://scripts/core/starter_colony.gd")
const Section7 := preload("res://scripts/core/save_section_inventories.gd")
const SaveHeader := preload("res://scripts/core/save_header.gd")
const IntMath := preload("res://scripts/core/int_math.gd")

const TUTORIAL_SEED: int = 20260905
const OTHER_SEED: int = 20260910
const START_MASK: int = 1
## GDD §5.9 origins, `z*128+x`.
const HALL_TILE: int = 59 * 128 + 58
const STOCKPILE_TILES: Array[int] = [60 * 128 + 50, 65 * 128 + 50, 60 * 128 + 70, 65 * 128 + 70]
## Footprint areas: the 12x10 hall, four 4x4 stockpiles, the 2x2 well and the 3x3 workbench.
const BUILDING_TILES: int = 120 + 4 * 16 + 4 + 9
## The hall's 80 interior tiles all belong to a room; floor furniture covers 31 pieces of which
## the kitchen bench and the hearth are 2x1, so 33 tiles.
const ROOM_TILES: int = 80
const FURNITURE_TILES: int = 33
## West of the hall, on §5.1's cleared one-tile apron: walkable and on no footprint.
const PILE_X: int = 57
const PILE_Z: int = 60

var _settlement: SettlementSystemScript = null


class LateRefusingAuthority extends RefCounted:
	"""A placement authority that passes the preflight's asks and refuses during the apply."""
	var asks: int = 0
	var refuse_after: int = 0

	func building_tile_refusal(_tile_index: int) -> StringName:
		"""Pass the first `refuse_after` tiles, then refuse every one after."""
		asks += 1
		return &"PROBE_REFUSED" if asks > refuse_after else &""


func before_each() -> void:
	"""A fresh settlement outside the tree, so `_ready()` binds no autoload clock."""
	_settlement = SettlementSystemScript.new()


func after_each() -> void:
	"""Free the settlement this test built."""
	if _settlement != null:
		_settlement.free()
		_settlement = null


func _generate(settlement: SettlementSystemScript, seed_value: int = TUTORIAL_SEED) -> bool:
	"""Run the production generation transaction with the shipped catalog."""
	var items: ItemDefinitions = ItemDefinitions.new()
	assert_true(items.load_default(Inventory.new()).ok, "the item catalog loads")
	return settlement.create_generated_settlement(items, seed_value)


func _tile(x: int, z: int) -> int:
	"""GDD §5.1's `z*128+x`."""
	return z * 128 + x


# --- the colony, the World row and the composer --------------------------------------------------

func test_generation_materialises_the_colony_at_its_planned_tiles() -> void:
	"""Seven ACTIVE structures, four rooms, thirty-one furniture, every one where §5.9 puts it."""
	assert_true(_generate(_settlement), "the settlement generates: %s" % _settlement.last_refusal())
	var buildings: Buildings = _settlement.buildings()
	assert_equal(buildings.live_building_count(), 7, "seven structures")
	assert_equal(buildings.live_room_count(), 4, "four rooms")
	assert_equal(buildings.live_furniture_count(), 31, "thirty-one floor furniture")
	var hall: Vector2i = buildings.building_at_tile(HALL_TILE)
	assert_equal(buildings.type_id_of_building(hall).value, int(Catalog.BUILDING_DEFINITION["hall"]),
		"the hall stands at (58,59)")
	assert_equal(buildings.state_of_building(hall).value, int(Catalog.BUILDING_STATE["ACTIVE"]),
		"ACTIVE")
	for tile: int in STOCKPILE_TILES:
		assert_equal(buildings.type_id_of_building(buildings.building_at_tile(tile)).value,
			int(Catalog.BUILDING_DEFINITION["open_stockpile"]), "a stockpile at tile %d" % tile)
	assert_equal(buildings.type_id_of_building(buildings.building_at_tile(_tile(64, 54))).value,
		int(Catalog.BUILDING_DEFINITION["well"]), "the well at (64,54)")
	assert_equal(buildings.type_id_of_building(buildings.building_at_tile(_tile(58, 54))).value,
		int(Catalog.BUILDING_DEFINITION["workbench"]), "the workbench at (58,54)")
	assert_equal(buildings.rooms_of_building(hall).size(), 4, "all four rooms are the hall's")
	assert_equal(buildings.live_furniture_of_kind(int(Catalog.FURNITURE_DEFINITION["bed"])), 12,
		"twelve beds")
	assert_equal(buildings.section_1_cross_check_refusal(), Buildings.COLUMN_REFUSE_NONE,
		"and every footprint, room run and furniture floor agrees with the tile maps")


func test_generation_creates_the_world_row_and_binds_the_composer_to_it() -> void:
	"""Decision 0532's obligation: one live World row, the composer bound to it, piles succeed."""
	assert_equal(_settlement.world_ref(), EntityDirectory.NULL_REF, "no World row before generation")
	assert_true(_generate(_settlement), "the settlement generates")
	var world: Vector2i = _settlement.world_ref()
	assert_true(_settlement.directory().is_valid_of_kind(world, EntityDirectory.KIND_WORLD),
		"a live World row exists")
	assert_equal(_settlement.directory().live_count(EntityDirectory.KIND_WORLD), 1, "exactly one")
	var piles: GroundPiles = _settlement.ground_piles()
	assert_equal(piles.ground_pile_owner_ref(), world, "the composer owns piles through it")
	assert_true(_settlement.inventory().has_ground_pile_authority(),
		"and is Inventory's live site authority")
	assert_true(_settlement.buildings().has_placement_authority(),
		"and Buildings' live placement authority")
	assert_true(_place_pile(PILE_X, PILE_Z), "so a pile request succeeds")
	var pile: Vector2i = _settlement.inventory().ground_pile_at_tile(_tile(PILE_X, PILE_Z))
	assert_true(_settlement.inventory().is_ground_pile(pile), "a pile stands on the apron")
	assert_equal(_settlement.inventory().container_owner(pile), world, "owned by the World")


func _place_pile(x: int, z: int) -> bool:
	"""Place 10 stone U into a pile on (x, z) through the settlement's composer."""
	var out: GroundPiles.PlaceResult = GroundPiles.PlaceResult.new()
	var stone: int = _settlement.item_definitions().compiled_id(&"stone")
	var placed: bool = _settlement.ground_piles().place_lots_into_piles(_tile(x, z),
		PackedByteArray(), PackedInt64Array([stone, 10000, 0, 0, 0, 0, 0]), out)
	assert_true(placed, "the pile placement: %s" % out.error)
	return placed


func test_a_building_over_a_live_pile_is_refused_by_name() -> void:
	"""Decision 0532 M4: a footprint covering a live ground pile refuses, writing nothing."""
	assert_true(_generate(_settlement), "the settlement generates")
	assert_true(_place_pile(PILE_X, PILE_Z), "a pile stands west of the hall")
	var buildings: Buildings = _settlement.buildings()
	var well: int = int(Catalog.BUILDING_DEFINITION["well"])
	var directory_before: PackedByteArray = _settlement.directory().state_bytes()
	var placed: Buildings.OpResult = buildings.place_building(well, _tile(56, 59), 0, START_MASK)
	assert_false(placed.ok, "a well over the pile is refused")
	assert_equal(placed.error, GroundPiles.REFUSE_BUILDING_OVER_PILE, "by name")
	assert_equal(buildings.placement_refusal(well, _tile(56, 59), 0, START_MASK),
		GroundPiles.REFUSE_BUILDING_OVER_PILE, "and the preview says the same")
	assert_equal(buildings.live_building_count(), 7, "no building was added")
	assert_true(_settlement.directory().state_bytes() == directory_before, "no directory row taken")
	assert_true(buildings.place_building(well, _tile(56, 50), 0, START_MASK).ok,
		"a well clear of every pile still places")


func test_a_reset_unbinds_the_world_and_piles_refuse_until_the_next_colony() -> void:
	"""After a reset no World row lives, so the composer owns nothing and refuses every pile."""
	assert_true(_generate(_settlement), "the settlement generates")
	_settlement.reset()
	assert_equal(_settlement.world_ref(), EntityDirectory.NULL_REF, "the World row is gone")
	assert_equal(_settlement.buildings().live_building_count(), 0, "and so is the colony")
	assert_equal(_settlement.ground_piles().ground_pile_tile_refusal(_tile(PILE_X, PILE_Z)),
		GroundPiles.REFUSE_NO_WORLD, "a pile tile is refused for want of a World")
	assert_true(_settlement.buildings().has_placement_authority(),
		"the placement authority is wiring and survives the reset")
	assert_true(_settlement.materialize_starter_colony(), "the colony materialises again")
	assert_equal(_settlement.ground_piles().ground_pile_owner_ref(), _settlement.world_ref(),
		"and the composer is rebound to the new World row")


func test_a_second_materialisation_is_refused_and_changes_nothing() -> void:
	"""The colony is materialised once; a repeat refuses STARTER_COLONY_ALREADY_PRESENT."""
	assert_true(_generate(_settlement), "the settlement generates")
	var before: PackedByteArray = _settlement.directory().state_bytes()
	assert_false(_settlement.materialize_starter_colony(), "a second colony is refused")
	assert_equal(_settlement.last_refusal(), SettlementSystemScript.REFUSE_STARTER_COLONY_PRESENT,
		"by name")
	assert_true(_settlement.directory().state_bytes() == before, "the directory is untouched")
	assert_equal(_settlement.population(), 12, "and the settlement was not reset")


func test_a_site_with_a_stray_building_is_refused_before_any_write() -> void:
	"""Any live building means the site is not the empty one the colony is planned for."""
	var well: int = int(Catalog.BUILDING_DEFINITION["well"])
	assert_true(_settlement.buildings().place_building(well, _tile(66, 66), 0, START_MASK).ok,
		"a stray well stands inside the hall's footprint")
	var before: PackedByteArray = _settlement.directory().state_bytes()
	assert_false(_settlement.materialize_starter_colony(), "the colony refuses")
	assert_equal(_settlement.last_refusal(), SettlementSystemScript.REFUSE_STARTER_COLONY_PRESENT,
		"by name")
	assert_equal(_settlement.directory().live_count(EntityDirectory.KIND_WORLD), 0, "no World row")
	assert_true(_settlement.directory().state_bytes() == before, "and nothing was written")
	assert_equal(_settlement.buildings().live_building_count(), 1, "only the stray well stands")


func test_a_live_world_row_alone_also_means_the_colony_is_present() -> void:
	"""A World row with no building still refuses by name: the World row is created only here."""
	assert_true(_settlement.directory().create(EntityDirectory.KIND_WORLD) != EntityDirectory.NULL_REF,
		"a World row exists before any colony")
	var before: PackedByteArray = _settlement.directory().state_bytes()
	assert_false(_settlement.materialize_starter_colony(), "the colony refuses")
	assert_equal(_settlement.last_refusal(), SettlementSystemScript.REFUSE_STARTER_COLONY_PRESENT,
		"as already present, not as a directory capacity refusal")
	assert_true(_settlement.directory().state_bytes() == before, "and nothing was written")


func test_an_ungenerated_settlement_can_materialise_the_colony_alone() -> void:
	"""Create's path: the apply needs an empty site, not this node's own world generator."""
	assert_true(_settlement.materialize_starter_colony(), "the colony materialises: %s"
		% _settlement.last_refusal())
	assert_equal(_settlement.buildings().live_furniture_count(), 31, "with all its furniture")
	assert_equal(_settlement.directory().get_persistent_id(_settlement.world_ref()), 1,
		"the World row is the first id an empty directory issues, ahead of the structures")


# --- the store binding EconomySystem opens on ------------------------------------------------------

func test_the_store_binding_opens_the_economy_on_the_colonys_buildings() -> void:
	"""#7 and #3a end to end: hall-owned pantry, stockpile-owned stores, §5.9's fill order."""
	assert_true(_generate(_settlement), "the settlement generates")
	var binding: StarterColony.StoreBinding = StarterColony.StoreBinding.new()
	assert_true(_settlement.starter_store_binding_into(binding), "the binding reads back")
	var economy: EconomySystemScript = EconomySystemScript.new()
	assert_true(economy.open_starter_stores(binding), "the stores open: %s" % economy.last_refusal())
	assert_true(economy.seed_initial_inventory(), "and take §5.1's inventory")
	var buildings: Buildings = _settlement.buildings()
	assert_equal(economy.inventory().container_owner(economy.pantry()),
		buildings.building_at_tile(HALL_TILE), "the hall owns the pantry")
	assert_equal(economy.inventory().container_anchor_tile(economy.pantry()), HALL_TILE,
		"anchored at its origin")
	var grams: Array[int] = [400000, 400000, 400000, 312000]
	for index: int in STOCKPILE_TILES.size():
		var store: Vector2i = economy.stockpile(index)
		assert_equal(economy.inventory().container_owner(store),
			buildings.building_at_tile(STOCKPILE_TILES[index]), "stockpile %d owns its store" % index)
		assert_equal(economy.inventory().container_anchor_tile(store), STOCKPILE_TILES[index],
			"anchored at its origin")
		assert_equal(economy.store_used_mass_g(store), grams[index], "holding %d g" % grams[index])
	economy.free()


func test_no_binding_is_published_without_a_colony() -> void:
	"""An empty settlement has no hall to own a pantry; the binding refuses and stays cleared."""
	var binding: StarterColony.StoreBinding = StarterColony.StoreBinding.new()
	assert_false(_settlement.starter_store_binding_into(binding), "no colony, no binding")
	assert_equal(_settlement.last_refusal(), StarterColony.REFUSE_NOT_PLACED, "by name")
	assert_false(binding.is_complete(), "and the output is cleared")


# --- save: the colony persists through the existing owners ------------------------------------------

func test_the_directory_round_trip_keeps_the_world_row_and_every_structure_ref() -> void:
	"""Section 3's six columns and §1's cursor restore the World row and the 42 structure rows."""
	assert_true(_generate(_settlement), "the settlement generates")
	var source: EntityDirectory = _settlement.directory()
	var columns: Array = _directory_columns(source)
	var restored: EntityDirectory = EntityDirectory.new()
	assert_true(restored.restore_columns_and_cursor(columns[0], columns[1], columns[2], columns[3],
		columns[4], columns[5], source.next_persistent_id()), "the directory restores")
	assert_true(restored.state_bytes() == source.state_bytes(), "byte-identical")
	assert_true(restored.is_valid_of_kind(_settlement.world_ref(), EntityDirectory.KIND_WORLD),
		"the World row is live in the restored directory")
	var hall: Vector2i = _settlement.buildings().building_at_tile(HALL_TILE)
	assert_true(restored.is_valid_of_kind(hall, EntityDirectory.KIND_BUILDING), "and so is the hall")
	assert_equal(restored.get_persistent_id(hall), source.get_persistent_id(hall),
		"under the same persistent id")
	assert_equal(restored.live_count(EntityDirectory.KIND_FURNITURE), 31, "with every furniture row")


func _directory_columns(source: EntityDirectory) -> Array:
	"""The six persisted directory columns, captured into capacity-sized buffers."""
	var active: PackedByteArray = PackedByteArray()
	var generation: PackedInt32Array = PackedInt32Array()
	var retired: PackedByteArray = PackedByteArray()
	var persistent_id: PackedInt32Array = PackedInt32Array()
	var kind: PackedInt32Array = PackedInt32Array()
	var typed_row: PackedInt32Array = PackedInt32Array()
	active.resize(EntityDirectory.DIRECTORY_CAPACITY)
	generation.resize(EntityDirectory.DIRECTORY_CAPACITY)
	retired.resize(EntityDirectory.DIRECTORY_CAPACITY)
	persistent_id.resize(EntityDirectory.DIRECTORY_CAPACITY)
	kind.resize(EntityDirectory.DIRECTORY_CAPACITY)
	typed_row.resize(EntityDirectory.DIRECTORY_CAPACITY)
	assert_true(source.copy_columns_into(active, generation, retired, persistent_id, kind,
		typed_row), "the directory columns copy")
	return [active, generation, retired, persistent_id, kind, typed_row]


func test_section_1_carries_every_footprint_room_and_furniture_tile() -> void:
	"""The three §1 tile maps hold the colony's 197/80/33 tiles and restore without a refusal."""
	assert_true(_generate(_settlement), "the settlement generates")
	var buildings: Buildings = _settlement.buildings()
	var maps: Array[PackedInt32Array] = [PackedInt32Array(), PackedInt32Array(), PackedInt32Array()]
	for index: int in 3:
		maps[index].resize(Buildings.TILE_COUNT)
	assert_true(buildings.copy_section_1_columns_into(maps[0], maps[1], maps[2]), "the maps copy")
	assert_equal(_occupied(maps[0]), BUILDING_TILES, "every building footprint tile")
	assert_equal(_occupied(maps[1]), ROOM_TILES, "every room tile")
	assert_equal(_occupied(maps[2]), FURNITURE_TILES, "every furniture floor tile")
	assert_equal(buildings.section_1_local_refusal(maps[0], maps[1], maps[2]),
		Buildings.COLUMN_REFUSE_NONE, "the copy is in its local domain")
	assert_true(buildings.restore_section_1_columns(maps[0], maps[1], maps[2]), "it restores")
	assert_equal(buildings.section_1_cross_check_refusal(), Buildings.COLUMN_REFUSE_NONE,
		"and cross-checks against the live rows")


func _occupied(column: PackedInt32Array) -> int:
	"""Tiles of a §1 map that name a row."""
	var count: int = 0
	for value: int in column:
		if value != Buildings.NO_LINK:
			count += 1
	return count


func test_section_4_accepts_the_colonys_building_room_and_furniture_columns() -> void:
	"""The 29 saved columns of the live colony pass owner 0's ordered column predicate.

	Buildings has no bulk capture yet (BUILDINGS-SAVED-BINDINGS), so the image is assembled from
	the store's own columns in the bridge's declared order; what is proved is that the colony is a
	state section 4 accepts, not that a capture call exists.
	"""
	assert_true(_generate(_settlement), "the settlement generates")
	var buildings: Buildings = _settlement.buildings()
	var image: Buildings.Columns = Buildings.Columns.new(false)
	for key: StringName in BuildingsOwner.FIELD_KEYS:
		image.set(String(key).substr(1), buildings.get(key))
	assert_equal(Buildings.columns_refusal(image), Buildings.REFUSE_NONE,
		"section 4's predicate accepts the colony")
	var live_rooms: int = 0
	for row: int in Buildings.ROOM_CAPACITY:
		live_rooms += image.r_present[row]
	assert_equal(live_rooms, 4, "and the image carries the four rooms")


func test_section_7_round_trips_the_owned_anchored_stores() -> void:
	"""The economy's five stores keep owner, anchor and capacity across encode, decode and apply."""
	assert_true(_generate(_settlement), "the settlement generates")
	var binding: StarterColony.StoreBinding = StarterColony.StoreBinding.new()
	assert_true(_settlement.starter_store_binding_into(binding), "the binding reads back")
	var economy: EconomySystemScript = EconomySystemScript.new()
	assert_true(economy.open_starter_stores(binding), "the stores open")
	assert_true(economy.seed_initial_inventory(), "and are seeded")
	var bytes: PackedByteArray = _encoded(economy.inventory())
	var parsed: Section7.Record = Section7.Record.new()
	var decoded: SaveHeader.Refusal = Section7.decode_into_versioned(bytes, 0, bytes.size(),
		Section7.SECTION_SCHEMA_VERSION, parsed)
	assert_equal(decoded.code, Section7.REFUSE_NONE, "decodes: %s" % decoded.detail)
	var restored: Inventory = Inventory.new()
	assert_true(ItemDefinitions.new().load_default(restored).ok, "the catalog registers")
	var applied: SaveHeader.Refusal = Section7.apply_inventory(parsed, restored,
		Section7.inventory_columns_for(parsed))
	assert_equal(applied.code, Section7.REFUSE_NONE, "publishes: %s" % applied.detail)
	assert_equal(restored.container_owner(economy.pantry()), binding.pantry_owner, "pantry owner")
	assert_equal(restored.container_anchor_tile(economy.pantry()), HALL_TILE, "pantry anchor")
	for index: int in STOCKPILE_TILES.size():
		var store: Vector2i = economy.stockpile(index)
		assert_equal(restored.container_owner(store), binding.stockpile_owner(index),
			"stockpile store %d owner" % index)
		assert_equal(restored.container_anchor_tile(store), STOCKPILE_TILES[index], "and anchor")
		assert_equal(restored.container_used_mass_g(store),
			economy.inventory().container_used_mass_g(store), "and contents")
	assert_equal(_encoded(restored), bytes, "save -> load -> save is byte-identical")
	economy.free()


func _encoded(store: Inventory) -> PackedByteArray:
	"""Capture and encode one inventory's section 7 with the runtime owners shrunk to 8 rows."""
	var record: Section7.Record = Section7.Record.new()
	record.owners[Section7.OWNER_GEAR] = Section7.OwnerRecord.new(
		Section7.OWNER_GEAR, 8, PackedInt64Array())
	record.owners[Section7.OWNER_RESERVATIONS] = Section7.OwnerRecord.new(
		Section7.OWNER_RESERVATIONS, 8, PackedInt64Array())
	var caps: Vector2i = store.canonical_capacities()
	record.owners[Section7.OWNER_INVENTORY] = Section7.OwnerRecord.new(
		Section7.OWNER_INVENTORY, caps.x, PackedInt64Array([caps.y]))
	Section7.fill_empty(record)
	var columns: Inventory.CanonicalColumns = Section7.inventory_columns_for(record)
	var captured: SaveHeader.Refusal = Section7.capture_inventory_into(record, store, columns)
	assert_true(captured.is_ok(), "capture: %s %s" % [captured.code, captured.detail])
	var result: Section7.EncodeResult = Section7.EncodeResult.new()
	assert_true(Section7.encode_record(record, result), "encode: %s" % result.detail)
	return result.bytes


# --- determinism ------------------------------------------------------------------------------------

func test_the_same_seed_builds_the_same_colony_rows_and_ids() -> void:
	"""Two fresh settlements on one seed: byte-identical directories and tile maps."""
	assert_true(_generate(_settlement), "the first settlement generates")
	var twin: SettlementSystemScript = SettlementSystemScript.new()
	assert_true(_generate(twin), "the second settlement generates")
	assert_true(twin.directory().state_bytes() == _settlement.directory().state_bytes(),
		"every directory row, generation and persistent id agrees")
	assert_equal(_maps_of(twin), _maps_of(_settlement), "and the building tile maps agree")
	twin.free()


func test_the_colony_is_authored_not_seeded() -> void:
	"""Another seed changes the world, never the colony: same tiles, same row kinds."""
	assert_true(_generate(_settlement), "the tutorial seed generates")
	var other: SettlementSystemScript = SettlementSystemScript.new()
	assert_true(_generate(other, OTHER_SEED), "another seed generates")
	assert_equal(_maps_of(other)[0], _maps_of(_settlement)[0],
		"the building footprints are §5.9's on any seed")
	assert_equal(other.buildings().live_furniture_count(), 31, "with the same furniture")
	other.free()


func _maps_of(settlement: SettlementSystemScript) -> Array[PackedInt32Array]:
	"""The three §1 building tile maps of `settlement`."""
	var maps: Array[PackedInt32Array] = [PackedInt32Array(), PackedInt32Array(), PackedInt32Array()]
	for index: int in 3:
		maps[index].resize(Buildings.TILE_COUNT)
	settlement.buildings().copy_section_1_columns_into(maps[0], maps[1], maps[2])
	return maps


# --- a refusal after the first write, and the order of the ids ---------------------------------------

func test_a_refusal_after_the_first_write_resets_the_settlement_to_empty() -> void:
	"""A colony that fails half-built is not left standing: the settlement is reset, code kept.

	The probe passes the preflight's 197 footprint tiles and the hall's 120 at apply, then refuses
	inside the first stockpile, so the World row and the hall are already written when it fails.
	"""
	var probe: LateRefusingAuthority = LateRefusingAuthority.new()
	probe.refuse_after = BUILDING_TILES + 120
	assert_true(_settlement.buildings().set_placement_authority(probe).ok, "the probe binds")
	assert_false(_settlement.materialize_starter_colony(), "the colony refuses half-built")
	assert_equal(_settlement.last_refusal(), &"PROBE_REFUSED", "with the probe's own code")
	assert_true(probe.asks > BUILDING_TILES + 120, "after the hall had been placed")
	assert_equal(_settlement.buildings().live_building_count(), 0, "no building is left")
	assert_equal(_settlement.directory().live_count(EntityDirectory.KIND_WORLD), 0, "no World row")
	assert_equal(_settlement.directory().total_live_count(), 0, "no row of any kind")


func test_the_world_row_and_the_colony_take_the_ids_after_every_world_entity() -> void:
	"""R-INIT-ID-001: residents 1-12, the world from 13, then the World row, then the colony."""
	assert_true(_generate(_settlement), "the settlement generates")
	var directory: EntityDirectory = _settlement.directory()
	var highest_world: int = 0
	var lowest_colony: int = 0
	for slot: int in EntityDirectory.DIRECTORY_CAPACITY:
		var ref: Vector2i = directory.ref_of_slot(slot)
		if ref == EntityDirectory.NULL_REF:
			continue
		var kind: int = directory.get_kind(ref)
		var id: int = directory.get_persistent_id(ref)
		if kind == EntityDirectory.KIND_BUILDING or kind == EntityDirectory.KIND_ROOM \
				or kind == EntityDirectory.KIND_FURNITURE:
			lowest_colony = id if lowest_colony == 0 else mini(lowest_colony, id)
		elif kind != EntityDirectory.KIND_WORLD:
			highest_world = maxi(highest_world, id)
	var world_id: int = directory.get_persistent_id(_settlement.world_ref())
	assert_true(highest_world > 12, "the world was published")
	assert_true(world_id > highest_world, "the World row follows every world entity")
	assert_equal(lowest_colony, world_id + 1, "and the colony follows the World row")


# --- the demolition gate over the real colony (D4, decision 0534) ------------------------------

func _open_economy_on_settlement() -> EconomySystemScript:
	"""An EconomySystem that adopts the settlement's inventory, then opens and seeds the stores."""
	var binding: StarterColony.StoreBinding = StarterColony.StoreBinding.new()
	assert_true(_settlement.starter_store_binding_into(binding), "the binding reads back")
	var economy: EconomySystemScript = EconomySystemScript.new()
	assert_true(economy.bind_inventory(_settlement.inventory()), "the economy adopts the store")
	assert_true(economy.open_and_seed_starter_stores(binding),
		"the stores open and seed: %s" % economy.last_refusal())
	return economy


func test_the_starter_stores_block_the_hall_and_the_stockpiles() -> void:
	"""Changed on purpose by D4: the gate now SEES the starter stores, so their goods block.

	D3 pinned every starter building at stage 5's MISSING_CONTAINMENT_CONTRACT, because the
	stores lived in EconomySystem's own inventory. EconomySystem now adopts the settlement's, so
	the hall's pantry and every stockpile's store are found by both scans and refuse by goods.
	"""
	assert_true(_generate(_settlement), "the settlement generates")
	var economy: EconomySystemScript = _open_economy_on_settlement()
	var buildings: Buildings = _settlement.buildings()
	for tile: int in [HALL_TILE, STOCKPILE_TILES[0], STOCKPILE_TILES[3]]:
		var before: int = _settlement.construction().live_project_count()
		var report: SettlementSystemScript.DemolitionReport = _settlement.request_demolition(
			buildings.building_at_tile(tile))
		assert_equal(report.error, SettlementSystemScript.REFUSE_DEMOLITION_STORED_GOODS,
			"the building at tile %d holds goods and refuses" % tile)
		assert_true(report.stranded_lot_count > 0, "naming its lots")
		assert_equal(_settlement.construction().live_project_count(), before, "publishing nothing")
	economy.free()


func test_the_well_is_admitted_into_the_last_stockpiles_headroom() -> void:
	"""A storeless starter building passes, and its return is reserved in a surviving store.

	The well returns wood 5 U and stone 10 U, 75000 g. Stockpiles 1-3 are full (400000 g) and the
	fourth holds 312000 g, so the fourth is the lowest store with room.
	"""
	assert_true(_generate(_settlement), "the settlement generates")
	var economy: EconomySystemScript = _open_economy_on_settlement()
	var well: Vector2i = _settlement.buildings().building_at_tile(_tile(64, 54))
	var report: SettlementSystemScript.DemolitionReport = _settlement.request_demolition(well)
	assert_true(report.ok, "the well is admitted (%s)" % report.error)
	assert_equal(report.output_container, economy.stockpile(3), "into the fourth stockpile")
	assert_equal(report.output_reserved_g, 75000, "reserving the whole return")
	assert_equal(_settlement.inventory().container_reserved_mass_g(economy.stockpile(3)), 75000,
		"which EconomySystem's own store now carries")
	assert_equal(_settlement.buildings().state_of_building(well).value,
		Catalog.BUILDING_STATE["DEMOLISHING"], "the well is DEMOLISHING")
	economy.free()


func test_the_workbench_then_falls_back_to_ground_piles() -> void:
	"""With 13000 g left nowhere holds the workbench's 40000 g, so #9's piles take it."""
	assert_true(_generate(_settlement), "the settlement generates")
	var economy: EconomySystemScript = _open_economy_on_settlement()
	var buildings: Buildings = _settlement.buildings()
	assert_true(_settlement.request_demolition(buildings.building_at_tile(_tile(64, 54))).ok,
		"the well is admitted first")
	var report: SettlementSystemScript.DemolitionReport = _settlement.request_demolition(
		buildings.building_at_tile(_tile(58, 54)))
	assert_true(report.ok, "the workbench is admitted (%s)" % report.error)
	assert_true(report.output_to_ground_piles, "its return goes to ground piles at D5")
	assert_equal(report.output_reserved_g, 0, "with nothing reserved")
	economy.free()


# --- the composed completion over the real colony (D5, decision 0535) ---------------------------

func _finish_demolition_work(project: Vector2i) -> void:
	"""Begin and complete an admitted demolition's work, leaving it commit-pending."""
	var remaining: IntMath.IntResult = IntMath.IntResult.new()
	assert_true(_settlement.construction().begin_work(project).ok, "work begins")
	assert_true(_settlement.construction().remaining_mwu_into(project, remaining), "remainder")
	assert_true(_settlement.construction().add_work_mwu(project, remaining.value).ok, "work done")


func test_the_starter_well_completes_into_the_fourth_stockpile() -> void:
	"""#6 over the real colony: the well goes and its 75000 g lands in the reserved stockpile."""
	assert_true(_generate(_settlement), "the settlement generates")
	var economy: EconomySystemScript = _open_economy_on_settlement()
	var well: Vector2i = _settlement.buildings().building_at_tile(_tile(64, 54))
	var stockpile: Vector2i = economy.stockpile(3)
	var used: int = _settlement.inventory().container_used_mass_g(stockpile)
	var admitted: SettlementSystemScript.DemolitionReport = _settlement.request_demolition(well)
	assert_true(admitted.ok, "admitted (%s)" % admitted.error)
	_finish_demolition_work(admitted.project_ref)
	var report: SettlementSystemScript.DemolitionReport = _settlement.complete_demolition(well)
	assert_true(report.ok, "the well completes (%s)" % report.error)
	assert_false(_settlement.buildings().is_live_building(well), "the well is gone")
	assert_equal(_settlement.inventory().container_used_mass_g(stockpile), used + 75000,
		"the fourth stockpile holds the return")
	assert_equal(_settlement.inventory().container_reserved_mass_g(stockpile), 0, "claim released")
	assert_equal(economy.stock_milli(&"wood"), 180000 + 5000, "the HUD's wood rose by 5 U")
	assert_true(_settlement.inventory().audit().ok, "audits")
	economy.free()


func test_the_starter_workbench_completes_onto_ground_piles() -> void:
	"""With no store left, the workbench's return is placed on piles from its front ring."""
	assert_true(_generate(_settlement), "the settlement generates")
	var economy: EconomySystemScript = _open_economy_on_settlement()
	var buildings: Buildings = _settlement.buildings()
	assert_true(_settlement.request_demolition(buildings.building_at_tile(_tile(64, 54))).ok,
		"the well takes the last headroom")
	var bench: Vector2i = buildings.building_at_tile(_tile(58, 54))
	var admitted: SettlementSystemScript.DemolitionReport = _settlement.request_demolition(bench)
	assert_true(admitted.output_to_ground_piles, "admitted onto piles (%s)" % admitted.error)
	_finish_demolition_work(admitted.project_ref)
	var report: SettlementSystemScript.DemolitionReport = _settlement.complete_demolition(bench)
	assert_true(report.ok, "the workbench completes (%s)" % report.error)
	assert_true(report.returned_lot_count >= 2, "its wood and stone are on the ground")
	var wood: int = _settlement.item_definitions().compiled_id(&"wood")
	assert_equal(_settlement.inventory().total_live_milli(wood), 180000 + 6000,
		"half the workbench's 12 U of wood joins the colony's 180 U")
	assert_true(_settlement.inventory().audit().ok, "audits")
	economy.free()


func test_the_emptied_starter_hall_still_refuses_for_its_31_pieces() -> void:
	"""The furniture rule over the real colony: with the pantry emptied, the 31 pieces refuse."""
	assert_true(_generate(_settlement), "the settlement generates")
	var economy: EconomySystemScript = _open_economy_on_settlement()
	var hall: Vector2i = _settlement.buildings().building_at_tile(HALL_TILE)
	var report: SettlementSystemScript.DemolitionReport = _settlement.request_demolition(hall)
	assert_equal(report.error, SettlementSystemScript.REFUSE_DEMOLITION_STORED_GOODS, "goods first")
	for index: int in report.stranded_lot_count:
		var lot: Vector2i = report.stranded_lot_at(index)
		assert_true(_settlement.inventory().sink_lot_quantity(lot,
			_settlement.inventory().lot_quantity_milli(lot)).ok, "the pantry is emptied")
	report = _settlement.request_demolition(hall)
	assert_equal(report.error, SettlementSystemScript.REFUSE_DEMOLITION_FURNITURE_UNPAID,
		"then every piece refuses")
	assert_equal(report.unpaid_furniture_count, 31, "all 31 of them")
	assert_true(_settlement.buildings().is_live_furniture(report.blocking_furniture), "one named")
	assert_equal(_settlement.construction().live_project_count(), 0, "nothing was admitted")
	economy.free()


func test_without_the_adoption_the_hall_would_read_as_empty() -> void:
	"""Why decision 0534 adopts the inventory: stores in a second inventory are invisible.

	An economy left on its PRIVATE store opens the same five owned, anchored stores, and the gate
	scanning the settlement's inventory finds none of them: the hall's goods scan reads empty.
	"""
	assert_true(_generate(_settlement), "the settlement generates")
	var binding: StarterColony.StoreBinding = StarterColony.StoreBinding.new()
	assert_true(_settlement.starter_store_binding_into(binding), "the binding reads back")
	var detached: EconomySystemScript = EconomySystemScript.new()
	assert_true(detached.open_and_seed_starter_stores(binding), "the private stores open")
	var hall: Vector2i = _settlement.buildings().building_at_tile(HALL_TILE)
	var report: SettlementSystemScript.DemolitionReport = _settlement.preview_demolition(hall)
	assert_equal(report.stranded_lot_count, 0, "the gate cannot see a pantry in another inventory")
	assert_equal(report.error, SettlementSystemScript.REFUSE_DEMOLITION_FURNITURE_UNPAID,
		"so it gets as far as the furniture rule (decision 0535) instead of refusing on goods")
	detached.free()


