extends SceneTree
const Injury := preload("res://scripts/core/injury.gd")
const Needs := preload("res://scripts/core/needs.gd")
const Directory := preload("res://scripts/core/entity_directory.gd")
const Case := preload("res://test/framework/test_case.gd")
const MAX_I64: int = 9223372036854775807
func _initialize() -> void:
	call_deferred("_run")
func _run() -> void:
	var f: Case = Case.new()
	var injury: Injury = Injury.new()
	var needs: Needs = Needs.new()
	var directory: Directory = Directory.new()
	f.assert_true(needs.spawn(511,Needs.SIZE_SMALL).ok,"physical tail patient needs")
	f.assert_true(injury.spawn(511).ok,"physical tail patient injury row")
	var rescuer: Vector2i = directory.create(Directory.KIND_RESIDENT)
	f.assert_true(rescuer.x >= 0,"target resident ref")
	f.assert_true(injury.set_rescuer(511,rescuer,directory,needs).ok,"healthy present patient may bind rescuer")
	f.assert_false(injury.is_injured(511),"still no injury")
	f.assert_true(injury.has_rescuer(511),"healthy binding retained")
	f.assert_true(injury.rescuer_is_live(511,directory),"live binding initially")
	f.assert_true(directory.destroy(rescuer),"rescuer directory leaves")
	f.assert_true(injury.has_rescuer(511),"stale reference deliberately retained")
	f.assert_false(injury.rescuer_is_live(511,directory),"stale ref refused by liveness reader")
	f.assert_true(injury.clear_rescuer(511).ok,"explicit relationship release")
	f.assert_true(injury.begin_airless_episode(511,1,needs).ok,"airless incident")
	f.assert_true(injury.apply_exhaustion_incident(511,2,needs).ok,"exhaustion episode")
	f.assert_equal(injury.kind_of(511).value,4,"worse exposure aggregate retained")
	f.assert_equal(injury.severity_of(511).value,2,"serious severity retained")
	f.assert_true(injury.airless_episode_active(511),"airless latch")
	f.assert_true(injury.exhaustion_latched(511),"exhaustion latch")
	f.assert_true(injury.add_care_work(511,MAX_I64,needs).ok,"care may exceed recipe work up to i64 max")
	f.assert_equal(injury.care_progress_mwu_of(511).value,MAX_I64,"care exact max")
	var before: PackedByteArray = injury.state_bytes()
	var extra: Needs.OpResult = injury.add_care_work(511,1,needs)
	f.assert_false(extra.ok,"care overflow refuses")
	f.assert_equal(extra.error,&"OVERFLOW","care overflow code")
	f.assert_equal(injury.state_bytes(),before,"care overflow does not mutate")
	f.assert_true(injury.tick_all(needs).ok,"one untreated tick")
	f.assert_equal(injury.untreated_ticks_of(511).value,1,"untreated tick")
	f.assert_true(injury.complete_treatment(511,60000,needs).ok,"treatment clears aggregate")
	f.assert_equal(injury.kind_of(511).value,0,"no injury kind")
	f.assert_equal(injury.severity_of(511).value,0,"no severity")
	f.assert_equal(injury.untreated_ticks_of(511).value,0,"clock reset on treatment")
	f.assert_equal(injury.care_progress_mwu_of(511).value,0,"care reset on treatment")
	f.assert_equal(injury.last_incident_ordinal_of(511).value,2,"ordinal retained")
	f.assert_true(injury.airless_episode_active(511),"airless retained after treatment")
	f.assert_true(injury.exhaustion_latched(511),"exhaustion retained after treatment")
	f.assert_true(injury.set_care_context_blocked(511,true).ok,"healthy context flag permitted")
	f.assert_true(injury.care_context_blocked(511),"healthy blocked context")
	f.assert_true(injury.apply_incident(511,1,1,0,MAX_I64,needs).ok,"full positive i64 ordinal")
	f.assert_equal(injury.last_incident_ordinal_of(511).value,MAX_I64,"ordinal exact max")
	var image: Variant = bytes_to_var(injury.state_bytes())
	f.assert_true(image is PackedInt64Array,"diagnostic format packed i64 variant")
	f.assert_equal(image.size(),12,"count plus eleven present fields")
	f.assert_equal(image[0],1,"one present row")
	f.assert_equal(image[1],511,"physical row identity")
	f.assert_equal(image[6],MAX_I64,"ordinal diagnostic position")
	f.assert_true(needs.apply_health_event(511,-100).ok,"death event")
	before = injury.state_bytes()
	f.assert_true(injury.tick_all(needs).ok,"dead injury row skipped")
	f.assert_equal(injury.state_bytes(),before,"dead history unchanged")
	f.assert_true(injury.despawn(511).ok,"row release")
	f.assert_equal(injury.present_count(),0,"derived count cleared")
	f.assert_equal(injury.injured_count(),0,"derived injury count cleared")
	for failure: String in f.failures: printerr(failure)
	print("INJURY_PUBLIC_HISTORY_PROBE assertions=%d failures=%d" % [f.assertions,f.failures.size()])
	quit(0 if f.failures.is_empty() else 1)
