extends RefCounted
## Generated by publish_claw_stairs_runtime.py (ADR 1229). Do not edit.

const WIRE_SHA: String = "9791eb59b778cf9fe0b4c66dfd7181c58706abd6ed1a8e6a90a73daafa7f3317"
const HANDLING_SOURCE_SHA: String = "b94d676e999c87dd399a4dc110674620a4fbc66f0ca07e494b8bedadac683b66"
const HAUL_SOURCE_SHA: String = "fa8dc668f7ae881d5fcc88a9dd1b6796b7f37466d0cca5e1994647e04a54dc71"
const STONE_SOURCE_SHA: String = "1756932c3839c3dbf2d66a715f65f5dfea7861ddafdf7f5921687b821040e6e6"
const CLAW_SOURCE_SHA: String = "b85f91952992fecfc4b0b89affb0b605b3d7c8e15b9c3e8f66ab03969efd6675"
const PAW_SOURCE_SHA: String = "9cdafc55914ba2ca25858d54ff1692df324c4e7eed019b04066b55de560bae3d"
const CLAW_WALK_ROW: int = 42
const CLAW_APPROACH_ROWS: PackedInt32Array = [43, 44, 45, 46]
const CLAW_RETREAT_ROWS: PackedInt32Array = [47, 48, 49, 50]
const CLAW_DIG_ROWS: PackedInt32Array = [56, 58, 60, 62]
const CLAW_TAP_ROWS: PackedInt32Array = [57, 59, 61, 63]
const PAW_HANDLING_ROW: int = 65
const CLAW_READY_KEY: int = 8
const CLAW_WALK_KEYS: int = 45
## Brendan, ADR 1217 step 4d: the READY fade never starts from these walk keys (inclusive).
const CLAW_FADE_BLOCKED_FIRST: int = 28
const CLAW_FADE_BLOCKED_LAST: int = 37
const CLAW_FADE_RESUME_KEY: int = 38
## ADR 1229 (content 10): the tread and stair rows.
const CLAW_STEP_BACK_ROW: int = 51
const CLAW_STEP_FORWARD_ROW: int = 52
const CLAW_DESCENT_ROW: int = 53
const CLAW_ASCENT_ROW: int = 54
const CLAW_TURN_ROW: int = 55
const CLAW_TREAD_TAP_ROW: int = 64
const PAW_TREAD_HANDLING_ROW: int = 66
const ACTOR_SHA: String = "adc617642313ac004c050d4877ef0b9f4024bb9c88e3ea92ce9a924471bd5ab9"
const BASIS_SHA: String = "de8c3b04fde4bec30b0b85bf2bf82e01604e9c17cfcb3fdf4029af0f4d43ebf9"
const BASIS_PRODUCER: String = "e68ec74b02bb227a065d9881ca2c12fe3b1ef122f032e7bb1324213d3031813f"
const CONSUMER_COMMIT: String = "912de685b423c5eedd36ee68bc78f18670276cb7"
const PATHS: PackedStringArray = [
	"res://scripts/core/underground_profiles.gd",
	"res://scripts/core/underground_work_face.gd",
	"res://scripts/core/underground_connector_contacts.gd",
	"res://scripts/core/underground_routes.gd",
	"res://scripts/core/underground_world_routes.gd",
	"res://demo/cast/underground_actor.gd",
	"res://demo/cast/underground_actor_content.gd",
	"res://data/underground/mole-worker/mole_profile_driver.gd",
	"res://data/underground/mole-worker/work-approach-v1/source_program.gd",
	"res://data/underground/mole-worker/work-step-v1/source_program.gd",
]
const DIGESTS: PackedStringArray = [
	"4adcdc2be52254d7c9ca73f7790b64cdd58e62f35d512dbd6f47a9f573d17d28",
	"2e68481744124bc9aa56667112de2d223796069fd1966090f69fad37d63b9b26",
	"4d1aff362f9eb60c5e9c10788fce98e65a2226c64d41c17b72de4cc38a3a035e",
	"97d2f4bf4e083cc5e00fabd7abd8b54195663fc7cebd1c3b0f28dbed50949d9a",
	"602f20d30812f4da61d624d3d42ade7eb1fe44729b751942b9d64dee1b4ee531",
	"b0ef7640d2b5626eb95c162d19318d9b3985a51479d19dfdf9a38e0176a06e91",
	"388374964d20879b6b896021ebde7927e472634ea8a32b6834ec7b1b5042157f",
	"db7c2051d5d4d4b642a5c1442be4241de3dd4802780bcace6d91d44e5f643064",
	"bc79fbe61bfd23641d6602070d132df724f9975ac36c1555cef701b14d6ab2c4",
	"7134c58f0a48c8eb1184484f1caf41089696cc90083c5cd7038fafeb3fce7879",
]
