#!/usr/bin/env python3
"""Create-only ADR 1190 publication of the fixed first-entry handling source bundle.

Copies the exact source bytes the passing real paid-L0 suite executes, verifies every
pinned digest and the Frontier's linked header digests and table census, and emits the
typed accessor `catalog_source.gd` plus `manifest.json`. Refuses to overwrite.

    python3 godot/data/underground/first-entry-prefix-v1/publish_qualified_handling.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parents[4]
OUTPUT = ROOT / "godot/data/underground/first-entry-prefix-v1/qualified-handling-v1"
RES = "res://data/underground/first-entry-prefix-v1/qualified-handling-v1/"
CONTENT = "docs/validation/evidence/underground-paid-assembly-handling-2026-10-05/diagnostic-content-1/"
INPUTS = {
    "CATALOG": (CONTENT + "structure.ugconn", "eda41ce78d4a798e2160250e2d6760ec7507f0c651c1e7b9b8ad462ff65ab520", 1),
    "GROUPING": (CONTENT + "assemblies.ugasmb", "3bb788bf250f4628cc4ab6a0c1a5748478d7909753cb5d1a8056d5eb7a8f4a54", 1),
    "RECIPE": (CONTENT + "recipes.ugrecp", "3019f92d56713317550c417e732b057d238fe0b70adadca8b56289a1362391a8", 1),
    "FRONTIER": ("docs/validation/evidence/underground-entry-work-area-2026-10-05/source-1/frontier.ugfront",
                 "1068db6b1217e6542f6489cd56add7af52db663c756e572c86c1128e8227a058", 2),
    "WORKPIECES": ("docs/validation/evidence/underground-paid-assembly-handling-2026-10-05/diagnostic-workpieces-1/workpieces.ugwipc",
                   "e68a7d9340675c495d875d97f5c51b063ba2a20b17041dc881b25a3e8b0f79ee", 1),
    "GROUND": (CONTENT + "ground-pace.ugconn", "877be0982eb6945c4c4f014e9de428b3ab278d1fddc630080e9c6bfe341a1ea8", 0),
    "PROFILE": (CONTENT + "mole-worker.ugprof", "17d9c229fdfe8ad1923f004db136653ab9834994ba946061be38ec7a2c862ff9", 4),
}
# The Frontier's fourth linked digest is the published mole actor (qualified-step-v4 ACTOR_SHA).
ACTOR_SHA = "adc617642313ac004c050d4877ef0b9f4024bb9c88e3ea92ce9a924471bd5ab9"
TABLES = ("INSTALL", "STATION", "CUT", "BEARING", "ENDPOINT", "EPISODE")


def require(value: bool, code: str) -> None:
    """Every refusal names its exact failed publication fact."""
    if not value:
        raise ValueError("QUALIFIED_HANDLING_" + code)


def load_inputs() -> dict:
    """Read each pinned input once."""
    data = {}
    for name, (path, digest, _) in INPUTS.items():
        raw = (ROOT / path).read_bytes()
        require(hashlib.sha256(raw).hexdigest() == digest, name + "_DIGEST")
        data[name] = raw
    return data


def frontier_census(frontier: bytes, data: dict) -> dict:
    """Decode the accepted header: revision, six positive table counts, and its catalog/group/recipe/actor links."""
    require(frontier[:8] == b"UGFRNT01" and struct.unpack_from("<I", frontier, 8)[0] == 1, "FRONTIER_FORMAT")
    require(struct.unpack_from("<q", frontier, 12)[0] == INPUTS["FRONTIER"][2], "FRONTIER_REVISION")
    counts = dict(zip(TABLES, struct.unpack_from("<6I", frontier, 68)))
    require(all(count >= 1 for count in counts.values()), "FRONTIER_CENSUS")
    for slot, name in enumerate(("CATALOG", "GROUPING", "RECIPE")):
        require(frontier[92 + 32 * slot:124 + 32 * slot] == hashlib.sha256(data[name]).digest(), "FRONTIER_LINK_" + name)
    require(frontier[188:220].hex() == ACTOR_SHA, "FRONTIER_LINK_ACTOR")
    return counts


def digest_words(raw: bytes) -> list[int]:
    """Signed little-endian I64 words of one SHA256, for allocation-free repeated comparison."""
    return list(struct.unpack("<4q", hashlib.sha256(raw).digest()))


def accessor(data: dict, counts: dict) -> str:
    """Emit typed constants only from the accepted bytes; nothing is caller-supplied."""
    lines = ["extends RefCounted", "## Generated by publish_qualified_handling.py (ADR 1190). Do not edit.", ""]
    for name, (path, _, revision) in INPUTS.items():
        ext = Path(path).name
        lines.append(f'const {name}_PATH: String = "{RES}{ext}"')
        lines.append(f'const {name}_SHA: String = "{hashlib.sha256(data[name]).hexdigest()}"')
        if name not in ("GROUND", "PROFILE"):
            lines.append(f"const {name}_REVISION: int = {revision}")
    lines.append(f"const CONTENT_REVISION: int = {INPUTS['PROFILE'][2]}")
    lines.append(f'const ACTOR_SHA: String = "{ACTOR_SHA}"')
    for table, count in counts.items():
        lines.append(f"const {table}_COUNT: int = {count}")
    for name in ("CATALOG", "GROUND"):
        for index, word in enumerate(digest_words(data[name])):
            lines.append(f"const {name}_DIGEST_{index}: int = {word}")
    return "\n".join(lines) + "\n"


def main() -> int:
    """Create the bundle exactly once; an existing output directory is never overwritten."""
    require(not OUTPUT.exists(), "OUTPUT_EXISTS")
    data = load_inputs()
    counts = frontier_census(data["FRONTIER"], data)
    OUTPUT.mkdir(parents=True)
    manifest = {"schema": 1, "decision": "1190", "content_revision": INPUTS["PROFILE"][2], "census": counts, "files": {}}
    for name, (path, _, _) in INPUTS.items():
        target = OUTPUT / Path(path).name
        target.write_bytes(data[name])
        manifest["files"][Path(path).name] = {"role": name, "sha256": hashlib.sha256(data[name]).hexdigest(), "source": path}
    (OUTPUT / "catalog_source.gd").write_text(accessor(data, counts))
    (OUTPUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print("published", OUTPUT.relative_to(ROOT), counts)
    return 0


if __name__ == "__main__":
    sys.exit(main())
