extends SceneTree
const Nodes := preload("res://scripts/core/resource_nodes.gd")
const Case := preload("res://test/framework/test_case.gd")
const I64_MAX: int = 9223372036854775807
const WIDE: int = 9007199254740993
func _initialize() -> void:
	call_deferred("_run")
func _run() -> void:
	var f: Case = Case.new()
	var nodes: Nodes = Nodes.new()
	# Generic API reachability, deliberately NOT a valid published catalog-ID fixture.
	var first: Nodes.OpResult = nodes.create_at_tile(0,2147483647,I64_MAX,2147483647,2147483647)
	f.assert_true(first.ok,"generic API accepts independent numeric extrema")
	f.assert_equal(nodes.capacity_milli_of(first.value).value,I64_MAX,"full i64 capacity exact")
	f.assert_equal(nodes.quantity_milli_of(first.value).value,I64_MAX,"initial quantity exact")
	f.assert_true(nodes.harvest(first.value,1,2147483647).ok,"partial harvest")
	f.assert_equal(nodes.quantity_milli_of(first.value).value,I64_MAX-1,"subtract exactly one")
	f.assert_true(nodes.harvest_all(first.value,2147483647).ok,"exhaust remaining stock")
	f.assert_true(nodes.is_exhausted(first.value),"exhausted zero-quantity row remains present")
	var ready: Variant = nodes.regrow_ready_day_of(first.value)
	f.assert_false(ready.ok,"independently valid day and period may overflow sum")
	f.assert_equal(String(ready.error),"OVERFLOW","explicit runtime refusal")
	f.assert_true(nodes.destroy(first.ref).ok,"destroy clears live address")
	f.assert_false(nodes.is_present(first.value),"row inactive")
	f.assert_equal(nodes.ref_of(first.value),Vector2i(-1,0),"inactive public null ref")
	f.assert_false(nodes.capacity_milli_of(first.value).ok,"reader cannot expose retained inactive capacity")
	var second: Nodes.OpResult = nodes.create_at_tile(1,0,WIDE,48,1)
	f.assert_true(second.ok,"wide integer fixture creates")
	f.assert_true(nodes.harvest(second.value,1,2).ok,"wide partial debit")
	f.assert_equal(nodes.quantity_milli_of(second.value).value,WIDE-1,"no float rounding")
	f.assert_true(nodes.harvest_all(second.value,3).ok,"wide exhaustion")
	f.assert_equal(nodes.planted_day_of(second.value).value,3,"stump date is harvest date")
	f.assert_true(nodes.regrow(second.value,51).ok,"regrow exactly due")
	f.assert_equal(nodes.quantity_milli_of(second.value).value,WIDE,"wide capacity restored exactly")
	f.assert_equal(nodes.planted_day_of(second.value).value,3,"regrow retains stump history")
	f.assert_false(nodes.is_exhausted(second.value),"grown row no longer exhausted")
	f.assert_equal(nodes.section_1_cross_check_refusal(),&"","actual live inverse/Directory passes")
	f.assert_true(nodes.destroy(second.ref).ok,"fixture cleanup")
	for failure: String in f.failures: printerr(failure)
	print("RESOURCE_NODES_PUBLIC_HISTORY_PROBE assertions=%d failures=%d" % [f.assertions,f.failures.size()])
	quit(0 if f.failures.is_empty() else 1)
