#!/usr/bin/env python3
"""Render the Astra inbox, and refuse a stale one.

Astra is the planner. This file is the single stable path it polls: one page,
always current, listing every question the executor may not answer for itself
and naming exactly what each one is holding up.

The index is GENERATED from open_items.json rather than hand-written, and
--check refuses a rendering that has drifted. A hand-maintained index goes stale
in about a week and then quietly stops being read, which is how four separate
lanes came to report four separate blockers that turned out to be one missing
artifact nobody had written down in one place.

    python3 tools/astra_inbox.py           # rewrite OPEN.md
    python3 tools/astra_inbox.py --check   # CI: refuse if OPEN.md is stale
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/rulings/requests/open_items.json"
INDEX = ROOT / "docs/rulings/requests/OPEN.md"
QUEUE = ROOT / "docs/planning/work_queue.json"

HEADER = """# Open questions for Astra

<!-- GENERATED by tools/astra_inbox.py from open_items.json. Do not hand-edit:
     CI refuses a stale rendering. Add or close items in the JSON. -->

This is the executor's inbox to the planner. Everything here is a decision the
executor **may not make for itself**, with the work it is holding named beside
it. Nothing here is a request for review; each item is a question whose answer
sets a contract.

An answer becomes binding by landing as a ruling in `docs/rulings/`. When it
does, the item is removed here and `astra_answered` is set on the tasks it was
blocking in `docs/planning/work_queue.json`, which is what releases them to the
dispatcher.

"""

FOOTER = """
## What is NOT here

Anything the executor can settle from the code, the GDD, an existing ruling or
arithmetic is settled without asking. Questions reach this page only when both
readings are internally consistent with the governing contracts, which is the
case where guessing sets a format that later has to be broken.

Review requests are a different thing and live in
[`docs/planning/review_packet.md`](../../planning/review_packet.md).
"""


def render() -> str:
	"""Build the index from the item source and the work queue."""
	items = json.loads(SOURCE.read_text(encoding="utf-8"))["items"]
	tasks = {t["id"]: t for t in json.loads(QUEUE.read_text(encoding="utf-8"))["tasks"]}

	blocking = [i for i in items if i.get("blocks")]
	advisory = [i for i in items if not i.get("blocks")]

	out = [HEADER]
	out.append(f"**{len(blocking)} blocking, {len(advisory)} advisory.** "
		f"Oldest asked {min(i['asked'] for i in items)}.\n")
	out.append("| Question | Asked | Holding up |")
	out.append("|---|---|---|")
	for item in items:
		held = ", ".join(f"`{b}`" for b in item.get("blocks", ())) or "nothing yet"
		out.append(f"| [{item['title']}](#{item['anchor']}) | {item['asked']} | {held} |")
	out.append("")

	for item in blocking + advisory:
		out.append(f"## {item['title']}")
		out.append("")
		out.append(f"*Asked {item['asked']}.*")
		out.append("")
		out.append(f"**Question.** {item['question']}")
		out.append("")
		out.append(f"**Why the executor cannot decide it.** {item['why_we_cannot_decide']}")
		out.append("")
		out.append(f"**Impact.** {item['impact']}")
		if item.get("blocks"):
			out.append("")
			for task_id in item["blocks"]:
				task = tasks.get(task_id)
				title = task["title"] if task else "unknown task"
				out.append(f"- Blocks `{task_id}` — {title}")
		out.append("")
	out.append(FOOTER.rstrip())
	return "\n".join(out) + "\n"


def main() -> int:
	"""Write or verify the index."""
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--check", action="store_true", help="refuse a stale OPEN.md")
	args = parser.parse_args()

	wanted = render()
	if args.check:
		current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
		if current != wanted:
			print("astra_inbox: REFUSE -- OPEN.md is stale. Run tools/astra_inbox.py.")
			return 1
		print("astra_inbox: PASS -- OPEN.md matches open_items.json")
		return 0

	INDEX.write_text(wanted, encoding="utf-8")
	print(f"astra_inbox: wrote {INDEX.relative_to(ROOT)}")
	return 0


if __name__ == "__main__":
	sys.exit(main())
