#!/usr/bin/env python3
"""Build the periodic packet Astra reviews, refusals first.

Astra is the planner and head of the project. Its job is not to approve merges
-- the gate does that -- but to catch what a green suite cannot: work that
drifted from the vision, an instruction that was quietly dropped, a plan detail
that got skipped because it was inconvenient, art that passes every check and
still looks wrong.

ORDERING IS THE DESIGN. This packet leads with refusals and deviations, because
those are the only entries where the executor and the plan actually disagreed,
and they are exactly what a summary written in good faith buries. Merged work
comes after. "Everything is fine" is the least informative thing this file can
say, so it is written last if it is written at all.

    python3 tools/review_packet.py --since 2026-09-05

Writes docs/planning/review_packet.md. Regenerating it is cheap and it is meant
to be regenerated, not edited.
"""

from __future__ import annotations

import argparse
import datetime
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
QUEUE = ROOT / "docs/planning/work_queue.json"
APPROVALS = ROOT / "docs/planning/art_approvals.json"
ITEMS = ROOT / "docs/rulings/requests/open_items.json"
OUT = ROOT / "docs/planning/review_packet.md"

BLOCKS = ("DEVIATIONS", "SURVIVED_MUTANTS", "BLOCKED")


def _git(*args: str) -> str:
	"""Run git in the repository root."""
	return subprocess.run(["git", "-C", str(ROOT), *args],
		capture_output=True, text=True).stdout


def merged_since(since: str) -> list[tuple[str, str]]:
	"""(sha, subject) for every commit merged since a date."""
	log = _git("log", f"--since={since}", "--merges", "--pretty=%h%x00%s")
	rows: list[tuple[str, str]] = []
	for line in log.strip().split("\n"):
		if "\x00" in line:
			sha, subject = line.split("\x00", 1)
			rows.append((sha, subject))
	return rows


def declarations_since(since: str) -> list[tuple[str, str, str]]:
	"""(sha, block, text) for every non-empty declaration in a merged commit body.

	These are the entries a human already agreed to let through. Astra reads
	them again because "a human looked at it once, at the moment they wanted it
	merged" is a weaker check than it sounds.
	"""
	log = _git("log", f"--since={since}", "--pretty=%h%x00%B%x01")
	found: list[tuple[str, str, str]] = []
	for entry in log.split("\x01"):
		if "\x00" not in entry:
			continue
		sha, body = entry.split("\x00", 1)
		for block in BLOCKS:
			for match in re.finditer(rf"^\s*\**{block}:\**\s*(.*)$", body, re.M):
				text = match.group(1).strip().strip("*")
				if text and text.lower() not in ("none", "none."):
					found.append((sha.strip(), block, text))
	return found


def main() -> int:
	"""Assemble the packet."""
	parser = argparse.ArgumentParser(description=__doc__)
	default_since = (datetime.date.today() - datetime.timedelta(days=7)).isoformat()
	parser.add_argument("--since", default=default_since, help="ISO date, default 7 days ago")
	args = parser.parse_args()

	queue = json.loads(QUEUE.read_text(encoding="utf-8"))
	approvals = json.loads(APPROVALS.read_text(encoding="utf-8"))
	items = json.loads(ITEMS.read_text(encoding="utf-8"))["items"]
	tasks = queue["tasks"]

	declarations = declarations_since(args.since)
	merges = merged_since(args.since)

	out: list[str] = []
	out.append("# Astra review packet")
	out.append("")
	out.append(f"<!-- GENERATED by tools/review_packet.py. Regenerate, do not edit. -->")
	out.append("")
	out.append(f"Covering {args.since} to {datetime.date.today().isoformat()}. "
		"Refusals and deviations lead, because they are the only entries where the "
		"executor and the plan disagreed, and they are what a good-faith summary "
		"buries.")
	out.append("")

	out.append("## 1. Declared exceptions in merged work")
	out.append("")
	if declarations:
		out.append("Each of these was let through by a human at the moment they wanted it "
			"merged. That is a weaker check than it sounds, so they are re-listed here.")
		out.append("")
		out.append("| Commit | Block | Declared |")
		out.append("|---|---|---|")
		for sha, block, text in declarations:
			out.append(f"| `{sha}` | {block} | {text[:100]} |")
	else:
		out.append("None in this window.")
	out.append("")

	out.append("## 2. Waiting on you")
	out.append("")
	blocking = [i for i in items if i.get("blocks")]
	if blocking:
		for item in blocking:
			held = ", ".join(f"`{b}`" for b in item["blocks"])
			out.append(f"- **{item['title']}** (asked {item['asked']}) — holding {held}. "
				f"[Full question](../rulings/requests/OPEN.md#{item['anchor']})")
	else:
		out.append("Nothing blocking.")
	out.append("")
	advisory = [i for i in items if not i.get("blocks")]
	if advisory:
		out.append("Advisory, not blocking anything today:")
		out.append("")
		for item in advisory:
			out.append(f"- {item['title']} (asked {item['asked']})")
		out.append("")

	out.append("## 3. Waiting on Brendan")
	out.append("")
	pending = [a for a in approvals["approvals"] if a["status"] == "pending"]
	if pending:
		for entry in pending:
			cost = ""
			if entry.get("spends_credits"):
				credits = entry.get("estimated_credits")
				cost = f" **Spends {credits} credits.**" if credits else \
					" **Spends credits, not yet costed.**"
			out.append(f"- **{entry['id']}** — {entry['what']}{cost}")
	else:
		out.append("Nothing pending.")
	out.append("")

	out.append("## 4. State of the queue")
	out.append("")
	by_status: dict[str, list[str]] = {}
	for task in tasks:
		by_status.setdefault(task["status"], []).append(task["id"])
	for status in ("in_flight", "review", "ready", "blocked", "done"):
		if status in by_status:
			out.append(f"- **{status}** ({len(by_status[status])}): "
				+ ", ".join(f"`{i}`" for i in sorted(by_status[status])))
	out.append("")

	out.append("## 5. Merged in this window")
	out.append("")
	if merges:
		for sha, subject in merges:
			out.append(f"- `{sha}` {subject}")
	else:
		out.append("Nothing merged in this window.")
	out.append("")

	out.append("## 6. What to look for that no check can see")
	out.append("")
	out.append("The gate checks arithmetic, the suite checks behaviour and CI checks both. "
		"None of them can see:")
	out.append("")
	out.append("- A requirement from your plan that was implemented in a narrower form than "
		"you specified, where the narrower form passes its own tests.")
	out.append("- A detail you supplied in planning that was dropped because it was "
		"inconvenient, with nothing recording that it was dropped.")
	out.append("- Art that satisfies every manifest and still does not read as Redwall.")
	out.append("- A task in the queue whose title has drifted from what you actually asked "
		"for, so the work is correct against the title and wrong against you.")
	out.append("- Work the queue does not contain at all. Absence is the failure mode "
		"nothing in this repository can detect.")
	out.append("")

	OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
	print(f"review_packet: wrote {OUT.relative_to(ROOT)} "
		f"({len(declarations)} declared exception(s), {len(blocking)} blocking question(s), "
		f"{len(pending)} approval(s) pending)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
