extends RefCounted
## Generated by publish_qualified_stone.py (ADR 1206). Do not edit.

const CATALOG_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stone-v5/structure.ugconn"
const CATALOG_SHA: String = "7ea0d26c6420075536ab3e542273b13dd2b45a7f1f0cc8cdd11e620af77907d6"
const CATALOG_REVISION: int = 1
const GROUPING_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stone-v5/assemblies.ugasmb"
const GROUPING_SHA: String = "c185a5c4ff0e256f7af134d26cd25d077951276853ab5fcb02f08c0b3c202904"
const GROUPING_REVISION: int = 1
const RECIPE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stone-v5/recipes.ugrecp"
const RECIPE_SHA: String = "2009f54ca7059b4cbc52486bc2fe2962eeda6cca1b69729bb994cafe04ccb5ef"
const RECIPE_REVISION: int = 1
const FRONTIER_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stone-v5/frontier.ugfront"
const FRONTIER_SHA: String = "2d5c36163ed5e5f8e96a3f1b0611d85937c075abcb8b02c7d7f01f7cf0738660"
const FRONTIER_REVISION: int = 4
const WORKPIECES_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stone-v5/workpieces.ugwipc"
const WORKPIECES_SHA: String = "ba98db4330ead65cdda4a5bc2d66ce72271621699ca960b272911a53140d246e"
const WORKPIECES_REVISION: int = 1
const GROUND_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stone-v5/ground-pace.ugconn"
const GROUND_SHA: String = "7fc1eeb45200292dd90e5659c494159485e56b0b487cbfc5c70d1346b2c6dc13"
const PROFILE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-stone-v5/mole-worker.ugprof"
const PROFILE_SHA: String = "30c3dc1f5e9162f5530f410c437ed6f85d28dc6879f88dec81cb193ea87b0df5"
const CONTENT_REVISION: int = 6
const ACTOR_SHA: String = "adc617642313ac004c050d4877ef0b9f4024bb9c88e3ea92ce9a924471bd5ab9"
const INSTALL_COUNT: int = 2
const STATION_COUNT: int = 8
const CUT_COUNT: int = 2
const BEARING_COUNT: int = 10
const ENDPOINT_COUNT: int = 14
const EPISODE_COUNT: int = 6
const CATALOG_DIGEST_0: int = 6126901433755410558
const CATALOG_DIGEST_1: int = 4445460898470865718
const CATALOG_DIGEST_2: int = -3618628971172023086
const CATALOG_DIGEST_3: int = -3024314522817913135
const GROUND_DIGEST_0: int = 3254132560974758271
const GROUND_DIGEST_1: int = -7776145610551980327
const GROUND_DIGEST_2: int = -4197499678814902907
const GROUND_DIGEST_3: int = 1431237250579107271
