extends SceneTree
const Farming := preload("res://scripts/core/farming.gd")
const Case := preload("res://test/framework/test_case.gd")
const MAX_I32: int = 2147483647
const MAX_I64: int = 9223372036854775807
func _initialize() -> void:
	call_deferred("_run")
func _run() -> void:
	var c: Case = Case.new()
	var farm: Farming = Farming.new()
	c.assert_true(farm.restore_tile_family_history(0,Farming.FAMILY_CEREAL,MAX_I32).ok,"public maximum streak")
	var made: Farming.OpResult = farm.create_plot_at_tile(0,Farming.SOIL_LOAM,1)
	c.assert_true(made.ok,"real plot")
	var row: int = made.value
	var ref: Vector2i = made.ref
	c.assert_equal(farm.family_streak_of(row).value,MAX_I32,"creation copies retained streak")
	c.assert_equal(farm.health_of(row).value,10000,"empty plot starts healthy")
	c.assert_equal(farm.growth_milli_hours_of(row).value,0,"empty growth")
	c.assert_true(farm.apply_compost(row,1).ok,"public compost")
	c.assert_equal(farm.compost_milli_of(row).value,2000,"current-season mirror")
	c.assert_true(farm.plant(row,Farming.CROP_GRAIN,MAX_I32,Farming.SEASON_SPRING,1).ok,"public max sow day with independently supplied season")
	c.assert_equal(farm.sow_day_of(row).value,MAX_I32,"stored max day")
	c.assert_equal(farm.state_of(row).value,Farming.STATE_SOWN,"sown")
	c.assert_equal(farm.health_of(row).value,10000,"sown health")
	c.assert_true(farm.cancel_sowing(row).ok,"cancel committed sowing")
	c.assert_equal(farm.sow_day_of(row).value,0,"cancellation clears sow day")
	c.assert_equal(farm.crop_id_of(row).value,Farming.CROP_NONE,"cancellation clears crop")
	c.assert_equal(farm.compost_milli_of(row).value,2000,"compost retained")
	c.assert_equal(farm.family_streak_of(row).value,MAX_I32,"history retained")
	c.assert_true(farm.plant(row,Farming.CROP_GRAIN,MAX_I32,Farming.SEASON_SPRING,1).ok,"replant at max day")
	c.assert_true(farm.begin_growing(row).ok,"productive sow completion")
	var ripe_tick: int = 0
	for hour: int in 192:
		ripe_tick = (hour+1)*750
		c.assert_true(farm.advance_growth_hour(row,100,ripe_tick).ok,"public growth hour")
	c.assert_equal(farm.state_of(row).value,Farming.STATE_RIPE,"ripe by growth")
	c.assert_equal(farm.growth_milli_hours_of(row).value,192000,"growth target")
	c.assert_equal(farm.health_of(row).value,10000,"healthy ripe crop")
	c.assert_true(farm.apply_ripe_expiry(row,ripe_tick+120*750).ok,"expiry after120 hours")
	c.assert_equal(farm.state_of(row).value,Farming.STATE_WITHERED,"expired crop withered")
	c.assert_equal(farm.health_of(row).value,10000,"WITHERED does not imply zero health")
	c.assert_equal(farm.growth_milli_hours_of(row).value,192000,"expired growth retained")
	c.assert_true(farm.clear_withered(row).ok,"clear expired crop")
	c.assert_equal(farm.state_of(row).value,Farming.STATE_EMPTY,"cleared empty")
	c.assert_equal(farm.growth_milli_hours_of(row).value,0,"clearing resets growth")
	c.assert_true(farm.plant(row,Farming.CROP_GRAIN,1,Farming.SEASON_SPRING,1).ok,"plant for health loss")
	c.assert_true(farm.begin_growing(row).ok,"begin health-loss crop")
	c.assert_true(farm.apply_health_loss(row,MAX_I64).ok,"max public health loss stays representable")
	c.assert_equal(farm.state_of(row).value,Farming.STATE_WITHERED,"health death")
	c.assert_equal(farm.health_of(row).value,0,"health clamped zero")
	c.assert_equal(farm.growth_milli_hours_of(row).value,0,"health wither can precede any growth")
	c.assert_true(farm.destroy(ref).ok,"delete designation")
	c.assert_false(farm.health_of(row).ok,"inactive health not publicly readable")
	c.assert_equal(farm.tile_family_streak_of(0).value,MAX_I32,"tile history outlives plot")
	c.assert_equal(farm.tile_compost_season_of(0).value,0,"tile compost history retained")
	made = farm.create_plot_at_tile(0,Farming.SOIL_LOAM,1)
	c.assert_true(made.ok,"recreate designation")
	row = made.value
	c.assert_equal(farm.health_of(row).value,10000,"recreated row health reset")
	c.assert_equal(farm.family_streak_of(row).value,MAX_I32,"recreated history copied")
	c.assert_equal(farm.compost_milli_of(row).value,2000,"recreated seasonal mirror")
	c.assert_true(farm.plant(row,Farming.CROP_GRAIN,1,Farming.SEASON_SPRING,1).ok,"plant harvest crop")
	c.assert_true(farm.begin_growing(row).ok,"grow harvest crop")
	for hour: int in 192:
		ripe_tick = (hour+1)*750
		c.assert_true(farm.advance_growth_hour(row,100,ripe_tick).ok,"harvest crop growth")
	c.assert_true(farm.harvest(row,2,ripe_tick,1000).ok,"public successful harvest")
	c.assert_equal(farm.family_streak_of(row).value,MAX_I32,"streak saturates instead of wraps")
	c.assert_equal(farm.tile_family_streak_of(0).value,MAX_I32,"tile streak matches saturated plot")
	c.assert_true(farm.refresh_compost_mirrors_for_day(13).ok,"next season mirror refresh")
	c.assert_equal(farm.compost_milli_of(row).value,0,"mirror resets in new season")
	c.assert_equal(farm.tile_compost_season_of(0).value,0,"refresh preserves old application season")
	farm.clear()
	print("FARMING_PUBLIC_HISTORY_PROBE assertions=%d failures=%d" % [c.assertions,c.failures.size()])
	for failure: String in c.failures: print(failure)
	quit(0 if c.failures.is_empty() else 1)
