extends RefCounted
## Generated by publish_qualified_claw.py (ADR 1217 step 4e). Do not edit.

const CATALOG_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-claw-v6/structure.ugconn"
const CATALOG_SHA: String = "e13ce51dbf394c825fbd7a240ef2568dc9ea4ec5df58b7fa19e02794a72a89e6"
const CATALOG_REVISION: int = 1
const GROUPING_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-claw-v6/assemblies.ugasmb"
const GROUPING_SHA: String = "735451b535c515eb4038337cdaf80dddc1284472df26e8a17150d932678c5d70"
const GROUPING_REVISION: int = 1
const RECIPE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-claw-v6/recipes.ugrecp"
const RECIPE_SHA: String = "bc62795cf9e5294a139d4d482b2888e6c354efb167c0c2d895d9ccaf65e1a5ff"
const RECIPE_REVISION: int = 1
const FRONTIER_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-claw-v6/frontier.ugfront"
const FRONTIER_SHA: String = "0d81d4f439912f737a5848d29cbfce4ad612da30b85f2d7fe38b5c23e0e8dfc7"
const FRONTIER_REVISION: int = 5
const WORKPIECES_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-claw-v6/workpieces.ugwipc"
const WORKPIECES_SHA: String = "6082e62a139cc00a602ad992be55cce3a1c0a69490d66553c7cd9adb3f7c1a47"
const WORKPIECES_REVISION: int = 1
const GROUND_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-claw-v6/ground-pace.ugconn"
const GROUND_SHA: String = "7bcaec942694df24d5fb01cec08b87d2da7d8b6d5806b02715c75b453acd307c"
const PROFILE_PATH: String = "res://data/underground/first-entry-prefix-v1/qualified-claw-v6/mole-worker.ugprof"
const PROFILE_SHA: String = "c8e34f12865e05b735772bd9db1a836c65720db2d3a03e84e617a7c8c2589e3b"
const CONTENT_REVISION: int = 9
const ACTOR_SHA: String = "2b58852e0e39d3ae1c697ed5487081cead7ce80efc8a30662e469fd33059af5b"
const INSTALL_COUNT: int = 2
const STATION_COUNT: int = 8
const CUT_COUNT: int = 2
const BEARING_COUNT: int = 10
const ENDPOINT_COUNT: int = 14
const EPISODE_COUNT: int = 6
const CATALOG_DIGEST_0: int = -9057801257545810719
const CATALOG_DIGEST_1: int = -8262150323809108641
const CATALOG_DIGEST_2: int = -380737925378282807
const CATALOG_DIGEST_3: int = -1834888473943220199
const GROUND_DIGEST_0: int = 2657005198600096379
const GROUND_DIGEST_1: int = -3276496543682528299
const GROUND_DIGEST_2: int = 2859792740245011930
const GROUND_DIGEST_3: int = 8948878109740615445
