extends SceneTree
const Section := preload("res://scripts/core/save_section_component_columns.gd")
class BorrowedColumnsModel:
	extends RefCounted
	var b_present: PackedByteArray = PackedByteArray()
	var r_present: PackedByteArray = PackedByteArray()
	var f_present: PackedByteArray = PackedByteArray()
	var b_type_id: PackedInt32Array = PackedInt32Array()
	var b_tier: PackedInt32Array = PackedInt32Array()
	var b_origin_tile: PackedInt32Array = PackedInt32Array()
	var b_rotation: PackedInt32Array = PackedInt32Array()
	var b_state: PackedInt32Array = PackedInt32Array()
	var b_condition: PackedInt32Array = PackedInt32Array()
	var b_construction_slot: PackedInt32Array = PackedInt32Array()
	var b_construction_generation: PackedInt32Array = PackedInt32Array()
	var b_interior_id: PackedInt32Array = PackedInt32Array()
	var r_type: PackedInt32Array = PackedInt32Array()
	var r_building_slot: PackedInt32Array = PackedInt32Array()
	var r_building_generation: PackedInt32Array = PackedInt32Array()
	var r_tile_offset: PackedInt32Array = PackedInt32Array()
	var r_tile_count: PackedInt32Array = PackedInt32Array()
	var r_temperature_tenths: PackedInt32Array = PackedInt32Array()
	var r_furniture_mask: PackedInt32Array = PackedInt32Array()
	var r_occupants: PackedInt32Array = PackedInt32Array()
	var r_valid: PackedByteArray = PackedByteArray()
	var f_type_id: PackedInt32Array = PackedInt32Array()
	var f_room_slot: PackedInt32Array = PackedInt32Array()
	var f_room_generation: PackedInt32Array = PackedInt32Array()
	var f_origin_tile: PackedInt32Array = PackedInt32Array()
	var f_rotation: PackedInt32Array = PackedInt32Array()
	var f_user_slot: PackedInt32Array = PackedInt32Array()
	var f_user_generation: PackedInt32Array = PackedInt32Array()
	var f_condition: PackedInt32Array = PackedInt32Array()
	func _init(allocate_defaults: bool = true) -> void:
		if not allocate_defaults: return
		b_present.resize(1024)
		r_present.resize(16384)
		f_present.resize(81920)
		b_type_id.resize(1024)
		b_tier.resize(1024)
		b_origin_tile.resize(1024)
		b_rotation.resize(1024)
		b_state.resize(1024)
		b_condition.resize(1024)
		b_construction_slot.resize(1024)
		b_construction_generation.resize(1024)
		b_interior_id.resize(1024)
		r_type.resize(16384)
		r_building_slot.resize(16384)
		r_building_generation.resize(16384)
		r_tile_offset.resize(16384)
		r_tile_count.resize(16384)
		r_temperature_tenths.resize(16384)
		r_furniture_mask.resize(16384)
		r_occupants.resize(16384)
		r_valid.resize(16384)
		f_type_id.resize(81920)
		f_room_slot.resize(81920)
		f_room_generation.resize(81920)
		f_origin_tile.resize(81920)
		f_rotation.resize(81920)
		f_user_slot.resize(81920)
		f_user_generation.resize(81920)
		f_condition.resize(81920)
func _bind(frame: Section.FramedOwner, allocate: bool) -> BorrowedColumnsModel:
	var out: BorrowedColumnsModel = BorrowedColumnsModel.new(allocate)
	out.b_present = frame.u8_column(0)
	out.r_present = frame.u8_column(1)
	out.f_present = frame.u8_column(2)
	out.b_type_id = frame.i32_column(3)
	out.b_tier = frame.i32_column(4)
	out.b_origin_tile = frame.i32_column(5)
	out.b_rotation = frame.i32_column(6)
	out.b_state = frame.i32_column(7)
	out.b_condition = frame.i32_column(8)
	out.b_construction_slot = frame.i32_column(9)
	out.b_construction_generation = frame.i32_column(10)
	out.b_interior_id = frame.i32_column(11)
	out.r_type = frame.i32_column(12)
	out.r_building_slot = frame.i32_column(13)
	out.r_building_generation = frame.i32_column(14)
	out.r_tile_offset = frame.i32_column(15)
	out.r_tile_count = frame.i32_column(16)
	out.r_temperature_tenths = frame.i32_column(17)
	out.r_furniture_mask = frame.i32_column(18)
	out.r_occupants = frame.i32_column(19)
	out.r_valid = frame.u8_column(20)
	out.f_type_id = frame.i32_column(21)
	out.f_room_slot = frame.i32_column(22)
	out.f_room_generation = frame.i32_column(23)
	out.f_origin_tile = frame.i32_column(24)
	out.f_rotation = frame.i32_column(25)
	out.f_user_slot = frame.i32_column(26)
	out.f_user_generation = frame.i32_column(27)
	out.f_condition = frame.i32_column(28)
	return out
func _measure(frame: Section.FramedOwner, allocate: bool) -> Dictionary:
	var ballast: PackedByteArray = PackedByteArray()
	var previous_peak: int = OS.get_static_memory_peak_usage()
	var previous_usage: int = OS.get_static_memory_usage()
	ballast.resize(maxi(0,previous_peak-previous_usage)+1048576)
	var before: int = OS.get_static_memory_peak_usage()
	var image: BorrowedColumnsModel = _bind(frame,allocate)
	var after: int = OS.get_static_memory_peak_usage()
	assert(image.f_condition.size() == 81920)
	return {"allocate_defaults":allocate,"ballast_bytes":ballast.size(),"before_peak":before,"after_peak":after,"increment":after-before}
func _initialize() -> void:
	assert(ClassDB.class_has_method("OS","get_static_memory_usage"))
	assert(ClassDB.class_has_method("OS","get_static_memory_peak_usage"))
	var frame: Section.FramedOwner = Section.FramedOwner.new(0)
	var results: Array = [_measure(frame,false),_measure(frame,true),_measure(frame,false)]
	print("BORROW_VIEW_PROBE "+JSON.stringify(results))
	quit(0)
