extends RefCounted
## Generated by publish_claw_approach_runtime.py (ADR 1217 step 4e). Do not edit.

const WIRE_SHA: String = "c8e34f12865e05b735772bd9db1a836c65720db2d3a03e84e617a7c8c2589e3b"
const HANDLING_SOURCE_SHA: String = "b94d676e999c87dd399a4dc110674620a4fbc66f0ca07e494b8bedadac683b66"
const HAUL_SOURCE_SHA: String = "fa8dc668f7ae881d5fcc88a9dd1b6796b7f37466d0cca5e1994647e04a54dc71"
const STONE_SOURCE_SHA: String = "1756932c3839c3dbf2d66a715f65f5dfea7861ddafdf7f5921687b821040e6e6"
const CLAW_SOURCE_SHA: String = "2b58852e0e39d3ae1c697ed5487081cead7ce80efc8a30662e469fd33059af5b"
const PAW_SOURCE_SHA: String = "cbe80b76b3b9eb5fbd857865eac27b7a0c6f0fa251df53e52c471c457a865e2a"
const CLAW_WALK_ROW: int = 42
const CLAW_APPROACH_ROWS: PackedInt32Array = [43, 44, 45, 46]
const CLAW_RETREAT_ROWS: PackedInt32Array = [47, 48, 49, 50]
const CLAW_DIG_ROWS: PackedInt32Array = [51, 53, 55, 57]
const CLAW_TAP_ROWS: PackedInt32Array = [52, 54, 56, 58]
const PAW_HANDLING_ROW: int = 59
const CLAW_READY_KEY: int = 8
const CLAW_WALK_KEYS: int = 45
## Brendan, ADR 1217 step 4d: the READY fade never starts from these walk keys (inclusive).
const CLAW_FADE_BLOCKED_FIRST: int = 28
const CLAW_FADE_BLOCKED_LAST: int = 37
const CLAW_FADE_RESUME_KEY: int = 38
const ACTOR_SHA: String = "adc617642313ac004c050d4877ef0b9f4024bb9c88e3ea92ce9a924471bd5ab9"
const BASIS_SHA: String = "de8c3b04fde4bec30b0b85bf2bf82e01604e9c17cfcb3fdf4029af0f4d43ebf9"
const BASIS_PRODUCER: String = "e68ec74b02bb227a065d9881ca2c12fe3b1ef122f032e7bb1324213d3031813f"
const CONSUMER_COMMIT: String = "912de685b423c5eedd36ee68bc78f18670276cb7"
const PATHS: PackedStringArray = [
	"res://scripts/core/underground_profiles.gd",
	"res://scripts/core/underground_work_face.gd",
	"res://scripts/core/underground_connector_contacts.gd",
	"res://scripts/core/underground_routes.gd",
	"res://scripts/core/underground_world_routes.gd",
	"res://demo/cast/underground_actor.gd",
	"res://demo/cast/underground_actor_content.gd",
	"res://data/underground/mole-worker/mole_profile_driver.gd",
	"res://data/underground/mole-worker/work-approach-v1/source_program.gd",
	"res://data/underground/mole-worker/work-step-v1/source_program.gd",
]
const DIGESTS: PackedStringArray = [
	"4adcdc2be52254d7c9ca73f7790b64cdd58e62f35d512dbd6f47a9f573d17d28",
	"2e68481744124bc9aa56667112de2d223796069fd1966090f69fad37d63b9b26",
	"71a9b5d40a7ee416b5ee7891c5712a2c10f6d718df18ebf4485fe0c465c6b7fa",
	"1d13b09767ad6ce49cb149419a182bcf5c2e94f145dbaa5847336ebc84ce14d1",
	"02afcf4b5af55f73bf747113d6ab08b98adf7273bdfe2763d1957217deb204b2",
	"b0ef7640d2b5626eb95c162d19318d9b3985a51479d19dfdf9a38e0176a06e91",
	"388374964d20879b6b896021ebde7927e472634ea8a32b6834ec7b1b5042157f",
	"db7c2051d5d4d4b642a5c1442be4241de3dd4802780bcace6d91d44e5f643064",
	"bc79fbe61bfd23641d6602070d132df724f9975ac36c1555cef701b14d6ab2c4",
	"7134c58f0a48c8eb1184484f1caf41089696cc90083c5cd7038fafeb3fce7879",
]
