"""Extract actual GLB float32 vertex bounds; static source diagnostic only."""
from pathlib import Path
import struct,json,hashlib,math
r=Path('/Users/brendan/Developer/redwall-rts-loop-2026-09-19');rel='godot/assets/units/species_mouse_body_a_lod0.glb';b=(r/rel).read_bytes();magic,ver,length=struct.unpack_from('<4sII',b);assert magic==b'glTF' and ver==2 and length==len(b);offset=12;chunks={}
while offset<len(b):
 size,kind=struct.unpack_from('<I4s',b,offset);offset+=8;chunks[kind]=b[offset:offset+size];offset+=size
j=json.loads(chunks[b'JSON']);assert len(j['nodes'])==1 and j['nodes'][0].get('mesh')==0;assert not any(k in j['nodes'][0] for k in ['matrix','translation','rotation','scale','children']);assert not j.get('skins') and not j.get('animations');verts=[]
for primitive in j['meshes'][0]['primitives']:
 a=j['accessors'][primitive['attributes']['POSITION']];assert a['componentType']==5126 and a['type']=='VEC3' and 'sparse' not in a;v=j['bufferViews'][a['bufferView']];assert v['buffer']==0;start=v.get('byteOffset',0)+a.get('byteOffset',0);stride=v.get('byteStride',12);assert stride>=12
 for n in range(a['count']):verts.append(struct.unpack_from('<fff',chunks[b'BIN\x00'],start+n*stride))
lo=[min(v[i] for v in verts) for i in range(3)];hi=[max(v[i] for v in verts) for i in range(3)];ql=[math.floor(x*1024) for x in lo];qh=[math.ceil(x*1024) for x in hi];translated=[ql[0]+256,ql[2]+256]
record={'scope':'Actual static vertex bounds of the existing unskinned mouse asset; no approved profile, continuous sweep, margin, motion, turn, support or production fit qualification','source':rel,'sha256':hashlib.sha256(b).hexdigest(),'position_vertices':len(verts),'node_transform':'single mesh node, identity; no skin/animation','axis':'glTF +Y up; coordinates read directly from float32 POSITION buffers','static_min_metres_xyz':lo,'static_max_metres_xyz':hi,'static_min_units_xyz_outward':ql,'static_max_units_xyz_outward':qh,'baseline_offset_units_xz':[256,256],'translated_static_min_units_xz':translated,'placement_diagnostic':'At least one translated static minimum is negative; no larger north-west anchored clearance square contains this exact source pose at this offset.' if min(translated)<0 else 'Static minima nonnegative; not a sweep qualification','margin_and_interpolation_error':'Not authored or qualified; zero extra margin used only for a necessary static containment diagnostic','consequence':'Retain current admission refusal. Do not relocate residents, crop geometry or publish a clearance class from this diagnostic. Use in the reviewed G02 anchor/asset contract.'}
e=r/'docs/validation/evidence/starter-integration-planning-2026-09-20';(e/'mouse-static-vertex-diagnostic.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps(record,indent=2))
